from __future__ import annotations

from importlib import import_module
from typing import Any


__all__ = [
    "AgentAdapter",
    "Artifact",
    "AttemptOutcomeObservation",
    "AttemptStartEvidence",
    "A2A_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "A2A_REVIEW_AUTH_SCOPE",
    "A2AActivationPosture",
    "A2AAgentMetadata",
    "A2AApprovalBindingDecision",
    "A2AAuthPosture",
    "A2ABlockedReceipt",
    "A2AExactDelegationApprovalContext",
    "A2AExactDelegationApprovalBinding",
    "A2AHandoffProposalEnvelope",
    "A2AReplayAuditRecord",
    "A2ATrustPosture",
    "AwarenessEvidenceStatus",
    "CallableCapabilityAdapter",
    "CapabilityAdapter",
    "CapabilityApprovalGrant",
    "CapabilityAwarenessBinding",
    "CapabilityAwarenessCatalog",
    "CapabilityAwarenessEnvelope",
    "CapabilityAuthorityLevel",
    "CapabilityCatalogEntry",
    "CapabilityCostClass",
    "CapabilityEvent",
    "CapabilityEventSink",
    "CapabilityHealthReport",
    "CapabilityHealthStatus",
    "CapabilityHydrationResult",
    "CapabilityMatchEvidence",
    "CapabilityKind",
    "CapabilityLatencyClass",
    "CapabilityManifest",
    "CapabilityOutcomeContract",
    "CapabilityOutcomeProjection",
    "CapabilityOperationSchema",
    "CapabilityPack",
    "CapabilityPolicy",
    "CapabilityPrivacyLevel",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilityRunContext",
    "CapabilitySearchFilters",
    "CapabilitySelection",
    "CapabilityShortlist",
    "CapabilitySpec",
    "CatalogInjectionCase",
    "ChatShadowDecision",
    "ChatShadowEvidence",
    "ChatShadowInspection",
    "CompactCapabilityEntry",
    "ContextPolicy",
    "CoordinationMode",
    "CoordinationRiskLevel",
    "Coordinator",
    "DeterministicSelector",
    "HandoffAdapter",
    "HumanGateAdapter",
    "FileCoordinatorStateStore",
    "FamiliarityAssessment",
    "FamiliarityAssessmentEvidence",
    "FamiliarityDimensions",
    "FamiliarityReasonCode",
    "FamiliarityState",
    "HydratedCapabilityManifest",
    "HydrationSourceEvidence",
    "HydrationTokenAccounting",
    "InMemoryTelemetrySink",
    "InMemoryCoordinatorStateStore",
    "LLMSelector",
    "LocalApprovalAuthority",
    "LoggerCapabilityEventSink",
    "MCP_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "MCP_REVIEW_AUTH_SCOPE",
    "McpActivationPosture",
    "McpApprovalBindingDecision",
    "McpAuthPosture",
    "McpBlockedReceipt",
    "McpDiscoveryToolMetadata",
    "McpExactApprovalContext",
    "McpExactApprovalBinding",
    "McpPreviewContract",
    "McpReplayAuditRecord",
    "McpTransportPosture",
    "ManifestTokenCount",
    "NoOpTelemetrySink",
    "NoopCapabilityEventSink",
    "NotesStore",
    "OperatorCorrectionDecision",
    "OperatorCorrectionEvidence",
    "OutcomeEvaluationPolicy",
    "OutcomeLifecycleEvidence",
    "OutcomeLifecycleProjection",
    "OutcomeObservationClass",
    "OutcomePriorEvidence",
    "PolicyDecision",
    "PolicyDecisionStatus",
    "PolicyDeniedError",
    "PolicyEngine",
    "ProgressiveCapabilityCache",
    "QualitySignals",
    "ReviewerAdapter",
    "RiskLevel",
    "RetrievalCandidate",
    "RetrievalConstraints",
    "RuntimePolicy",
    "SafetyPolicy",
    "ShadowChatAction",
    "SideEffectLevel",
    "SimpleNotesStore",
    "TaskEnvelope",
    "TaskNode",
    "TaskNodeStatus",
    "TaskPlan",
    "TerminalReceiptEvidence",
    "TerminalReceiptStatus",
    "TerminalStatusBinding",
    "TerminalOutcomeEvidence",
    "TelemetryEvent",
    "TelemetrySink",
    "ToolAdapter",
    "WorkflowAdapter",
    "BLOCKED_FOUNDATION_CAPABILITY_NAMES",
    "as_registration",
    "assess_familiarity",
    "a2a_agent_card_to_metadata",
    "a2a_v1_agent_card_to_metadata",
    "a2a_agent_metadata_to_capability_candidate",
    "build_a2a_blocked_receipt",
    "build_a2a_handoff_proposal",
    "build_a2a_replay_audit_record",
    "build_capability_awareness_catalog",
    "build_attempt_start_evidence",
    "build_capability_outcome_contract",
    "build_catalog_injection_cases",
    "build_chat_shadow_inspection",
    "build_progressive_capability_cache",
    "build_outcome_evaluation_policy",
    "build_terminal_receipt_evidence",
    "capability_is_foundation_blocked",
    "capability",
    "default_foundation_capability_registry",
    "foundation_blocked_capability_specs",
    "discover_capabilities",
    "evaluate_chat_shadow",
    "evaluate_operator_correction",
    "get_capability_spec",
    "build_mcp_blocked_receipt",
    "build_mcp_preview_contract",
    "build_mcp_replay_audit_record",
    "evaluate_mcp_exact_approval_binding",
    "evaluate_a2a_exact_approval_binding",
    "mcp_tool_metadata_to_capability_candidate",
    "hydrate_capability_manifests",
    "operation_schema_from_manifest",
    "project_capability_outcomes",
    "project_outcome_lifecycle",
    "render_compact_catalog",
    "select_capabilities",
    "tool_capability",
    "validate_capability_awareness_catalog",
    "wrap_agent",
    "wrap_tool",
]


_EXPORT_GROUPS = {
    "ultimate_ai_agent.core.capabilities.chat_shadow": {
        "AwarenessEvidenceStatus",
        "CatalogInjectionCase",
        "ChatShadowDecision",
        "ChatShadowEvidence",
        "ChatShadowInspection",
        "ShadowChatAction",
        "build_chat_shadow_inspection",
        "build_catalog_injection_cases",
        "evaluate_chat_shadow",
    },
    "ultimate_ai_agent.core.capabilities.awareness": {
        "CapabilityAwarenessBinding",
        "CapabilityAwarenessCatalog",
        "CapabilityAwarenessEnvelope",
        "CapabilityOperationSchema",
        "build_capability_awareness_catalog",
        "operation_schema_from_manifest",
        "validate_capability_awareness_catalog",
    },
    "ultimate_ai_agent.core.capabilities.familiarity": {
        "CapabilityMatchEvidence",
        "FamiliarityAssessment",
        "FamiliarityAssessmentEvidence",
        "FamiliarityDimensions",
        "FamiliarityReasonCode",
        "FamiliarityState",
        "TerminalOutcomeEvidence",
        "assess_familiarity",
    },
    "ultimate_ai_agent.core.capabilities.outcomes": {
        "AttemptOutcomeObservation",
        "AttemptStartEvidence",
        "CapabilityOutcomeContract",
        "CapabilityOutcomeProjection",
        "OperatorCorrectionDecision",
        "OperatorCorrectionEvidence",
        "OutcomeEvaluationPolicy",
        "OutcomeLifecycleEvidence",
        "OutcomeLifecycleProjection",
        "OutcomeObservationClass",
        "OutcomePriorEvidence",
        "TerminalReceiptEvidence",
        "TerminalReceiptStatus",
        "TerminalStatusBinding",
        "build_attempt_start_evidence",
        "build_capability_outcome_contract",
        "build_outcome_evaluation_policy",
        "build_terminal_receipt_evidence",
        "evaluate_operator_correction",
        "project_capability_outcomes",
        "project_outcome_lifecycle",
    },
    "ultimate_ai_agent.core.capabilities.retrieval": {
        "CapabilityHydrationResult",
        "CapabilityShortlist",
        "CompactCapabilityEntry",
        "HydratedCapabilityManifest",
        "HydrationSourceEvidence",
        "HydrationTokenAccounting",
        "ManifestTokenCount",
        "ProgressiveCapabilityCache",
        "RetrievalCandidate",
        "RetrievalConstraints",
        "build_progressive_capability_cache",
        "discover_capabilities",
        "hydrate_capability_manifests",
    },
    "ultimate_ai_agent.core.capabilities.adapters": {
        "AgentAdapter",
        "CallableCapabilityAdapter",
        "CapabilityAdapter",
        "HandoffAdapter",
        "HumanGateAdapter",
        "ReviewerAdapter",
        "ToolAdapter",
        "WorkflowAdapter",
        "wrap_agent",
        "wrap_tool",
    },
    "ultimate_ai_agent.core.capabilities.catalog": {"render_compact_catalog"},
    "ultimate_ai_agent.core.capabilities.context": {"NotesStore", "SimpleNotesStore"},
    "ultimate_ai_agent.core.capabilities.coordinator": {
        "Coordinator",
        "PolicyDeniedError",
    },
    "ultimate_ai_agent.core.capabilities.approval": {
        "CapabilityApprovalGrant",
        "LocalApprovalAuthority",
    },
    "ultimate_ai_agent.core.capabilities.decorators": {
        "as_registration",
        "capability",
        "get_capability_spec",
        "tool_capability",
    },
    "ultimate_ai_agent.core.capabilities.defaults": {
        "BLOCKED_FOUNDATION_CAPABILITY_NAMES",
        "capability_is_foundation_blocked",
        "default_foundation_capability_registry",
        "foundation_blocked_capability_specs",
    },
    "ultimate_ai_agent.core.capabilities.a2a_gateway": {
        "A2A_DEFAULT_BLOCKED_AUTHORITY_REFS",
        "A2A_REVIEW_AUTH_SCOPE",
        "A2AActivationPosture",
        "A2AAgentMetadata",
        "A2AApprovalBindingDecision",
        "A2AAuthPosture",
        "A2ABlockedReceipt",
        "A2AExactDelegationApprovalContext",
        "A2AExactDelegationApprovalBinding",
        "A2AHandoffProposalEnvelope",
        "A2AReplayAuditRecord",
        "A2ATrustPosture",
        "a2a_agent_card_to_metadata",
        "a2a_v1_agent_card_to_metadata",
        "a2a_agent_metadata_to_capability_candidate",
        "build_a2a_blocked_receipt",
        "build_a2a_handoff_proposal",
        "build_a2a_replay_audit_record",
        "evaluate_a2a_exact_approval_binding",
    },
    "ultimate_ai_agent.core.capabilities.enums": {
        "CapabilityAuthorityLevel",
        "CapabilityCostClass",
        "CapabilityHealthStatus",
        "CapabilityKind",
        "CapabilityLatencyClass",
        "CapabilityPrivacyLevel",
        "CoordinationMode",
        "PolicyDecisionStatus",
        "SideEffectLevel",
        "TaskNodeStatus",
        "CoordinationRiskLevel",
    },
    "ultimate_ai_agent.core.capabilities.models": {
        "Artifact",
        "CapabilityCatalogEntry",
        "CapabilityHealthReport",
        "CapabilityManifest",
        "CapabilityPack",
        "CapabilityPolicy",
        "CapabilityRegistration",
        "CapabilityResult",
        "CapabilityRunContext",
        "CapabilitySearchFilters",
        "CapabilitySelection",
        "CapabilitySpec",
        "ContextPolicy",
        "PolicyDecision",
        "QualitySignals",
        "RiskLevel",
        "RuntimePolicy",
        "SafetyPolicy",
        "TaskEnvelope",
        "TaskNode",
        "TaskPlan",
        "TelemetryEvent",
    },
    "ultimate_ai_agent.core.capabilities.mcp_gateway": {
        "MCP_DEFAULT_BLOCKED_AUTHORITY_REFS",
        "MCP_REVIEW_AUTH_SCOPE",
        "McpActivationPosture",
        "McpApprovalBindingDecision",
        "McpAuthPosture",
        "McpBlockedReceipt",
        "McpDiscoveryToolMetadata",
        "McpExactApprovalContext",
        "McpExactApprovalBinding",
        "McpPreviewContract",
        "McpReplayAuditRecord",
        "McpTransportPosture",
        "build_mcp_blocked_receipt",
        "build_mcp_preview_contract",
        "build_mcp_replay_audit_record",
        "evaluate_mcp_exact_approval_binding",
        "mcp_tool_metadata_to_capability_candidate",
    },
    "ultimate_ai_agent.core.capabilities.observability": {
        "CapabilityEvent",
        "CapabilityEventSink",
        "LoggerCapabilityEventSink",
        "NoopCapabilityEventSink",
    },
    "ultimate_ai_agent.core.capabilities.policy": {"PolicyEngine"},
    "ultimate_ai_agent.core.capabilities.registry": {"CapabilityRegistry"},
    "ultimate_ai_agent.core.capabilities.selection": {
        "DeterministicSelector",
        "LLMSelector",
        "select_capabilities",
    },
    "ultimate_ai_agent.core.capabilities.state": {
        "FileCoordinatorStateStore",
        "InMemoryCoordinatorStateStore",
    },
    "ultimate_ai_agent.core.capabilities.telemetry": {
        "InMemoryTelemetrySink",
        "NoOpTelemetrySink",
        "TelemetrySink",
    },
}

_LAZY_EXPORTS = {
    name: module_name for module_name, names in _EXPORT_GROUPS.items() for name in names
}


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    attribute_name = "RiskLevel" if name == "CoordinationRiskLevel" else name
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
