from __future__ import annotations

from importlib import import_module
from typing import Any


__all__ = [
    "AgentAdapter",
    "Artifact",
    "A2A_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "A2A_REVIEW_AUTH_SCOPE",
    "A2AActivationPosture",
    "A2AAgentMetadata",
    "A2AApprovalBindingDecision",
    "A2AAuthPosture",
    "A2ABlockedReceipt",
    "A2AExactDelegationApprovalContext",
    "A2AExactDelegationApprovalBinding",
    "A2AHandoffProposalEnvelope",
    "A2AReplayAuditRecord",
    "A2ATrustPosture",
    "CallableCapabilityAdapter",
    "CapabilityAdapter",
    "CapabilityApprovalGrant",
    "CapabilityAuthorityLevel",
    "CapabilityCatalogEntry",
    "CapabilityCostClass",
    "CapabilityEvent",
    "CapabilityEventSink",
    "CapabilityHealthReport",
    "CapabilityHealthStatus",
    "CapabilityKind",
    "CapabilityLatencyClass",
    "CapabilityManifest",
    "CapabilityPack",
    "CapabilityPolicy",
    "CapabilityPrivacyLevel",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilityRunContext",
    "CapabilitySearchFilters",
    "CapabilitySelection",
    "CapabilitySpec",
    "ContextPolicy",
    "CoordinationMode",
    "CoordinationRiskLevel",
    "Coordinator",
    "DeterministicSelector",
    "HandoffAdapter",
    "HumanGateAdapter",
    "FileCoordinatorStateStore",
    "InMemoryTelemetrySink",
    "InMemoryCoordinatorStateStore",
    "LLMSelector",
    "LocalApprovalAuthority",
    "LoggerCapabilityEventSink",
    "MCP_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "MCP_REVIEW_AUTH_SCOPE",
    "McpActivationPosture",
    "McpApprovalBindingDecision",
    "McpAuthPosture",
    "McpBlockedReceipt",
    "McpDiscoveryToolMetadata",
    "McpExactApprovalContext",
    "McpExactApprovalBinding",
    "McpPreviewContract",
    "McpReplayAuditRecord",
    "McpTransportPosture",
    "NoOpTelemetrySink",
    "NoopCapabilityEventSink",
    "NotesStore",
    "PolicyDecision",
    "PolicyDecisionStatus",
    "PolicyDeniedError",
    "PolicyEngine",
    "QualitySignals",
    "ReviewerAdapter",
    "RiskLevel",
    "RuntimePolicy",
    "SafetyPolicy",
    "SideEffectLevel",
    "SimpleNotesStore",
    "TaskEnvelope",
    "TaskNode",
    "TaskNodeStatus",
    "TaskPlan",
    "TelemetryEvent",
    "TelemetrySink",
    "ToolAdapter",
    "WorkflowAdapter",
    "BLOCKED_FOUNDATION_CAPABILITY_NAMES",
    "as_registration",
    "a2a_agent_card_to_metadata",
    "a2a_v1_agent_card_to_metadata",
    "a2a_agent_metadata_to_capability_candidate",
    "build_a2a_blocked_receipt",
    "build_a2a_handoff_proposal",
    "build_a2a_replay_audit_record",
    "capability_is_foundation_blocked",
    "capability",
    "default_foundation_capability_registry",
    "foundation_blocked_capability_specs",
    "get_capability_spec",
    "build_mcp_blocked_receipt",
    "build_mcp_preview_contract",
    "build_mcp_replay_audit_record",
    "evaluate_mcp_exact_approval_binding",
    "evaluate_a2a_exact_approval_binding",
    "mcp_tool_metadata_to_capability_candidate",
    "render_compact_catalog",
    "select_capabilities",
    "tool_capability",
    "wrap_agent",
    "wrap_tool",
]


_EXPORT_GROUPS = {
    "ultimate_ai_agent.core.capabilities.adapters": {
        "AgentAdapter",
        "CallableCapabilityAdapter",
        "CapabilityAdapter",
        "HandoffAdapter",
        "HumanGateAdapter",
        "ReviewerAdapter",
        "ToolAdapter",
        "WorkflowAdapter",
        "wrap_agent",
        "wrap_tool",
    },
    "ultimate_ai_agent.core.capabilities.catalog": {"render_compact_catalog"},
    "ultimate_ai_agent.core.capabilities.context": {"NotesStore", "SimpleNotesStore"},
    "ultimate_ai_agent.core.capabilities.coordinator": {
        "Coordinator",
        "PolicyDeniedError",
    },
    "ultimate_ai_agent.core.capabilities.approval": {
        "CapabilityApprovalGrant",
        "LocalApprovalAuthority",
    },
    "ultimate_ai_agent.core.capabilities.decorators": {
        "as_registration",
        "capability",
        "get_capability_spec",
        "tool_capability",
    },
    "ultimate_ai_agent.core.capabilities.defaults": {
        "BLOCKED_FOUNDATION_CAPABILITY_NAMES",
        "capability_is_foundation_blocked",
        "default_foundation_capability_registry",
        "foundation_blocked_capability_specs",
    },
    "ultimate_ai_agent.core.capabilities.a2a_gateway": {
        "A2A_DEFAULT_BLOCKED_AUTHORITY_REFS",
        "A2A_REVIEW_AUTH_SCOPE",
        "A2AActivationPosture",
        "A2AAgentMetadata",
        "A2AApprovalBindingDecision",
        "A2AAuthPosture",
        "A2ABlockedReceipt",
        "A2AExactDelegationApprovalContext",
        "A2AExactDelegationApprovalBinding",
        "A2AHandoffProposalEnvelope",
        "A2AReplayAuditRecord",
        "A2ATrustPosture",
        "a2a_agent_card_to_metadata",
        "a2a_v1_agent_card_to_metadata",
        "a2a_agent_metadata_to_capability_candidate",
        "build_a2a_blocked_receipt",
        "build_a2a_handoff_proposal",
        "build_a2a_replay_audit_record",
        "evaluate_a2a_exact_approval_binding",
    },
    "ultimate_ai_agent.core.capabilities.enums": {
        "CapabilityAuthorityLevel",
        "CapabilityCostClass",
        "CapabilityHealthStatus",
        "CapabilityKind",
        "CapabilityLatencyClass",
        "CapabilityPrivacyLevel",
        "CoordinationMode",
        "PolicyDecisionStatus",
        "SideEffectLevel",
        "TaskNodeStatus",
        "CoordinationRiskLevel",
    },
    "ultimate_ai_agent.core.capabilities.models": {
        "Artifact",
        "CapabilityCatalogEntry",
        "CapabilityHealthReport",
        "CapabilityManifest",
        "CapabilityPack",
        "CapabilityPolicy",
        "CapabilityRegistration",
        "CapabilityResult",
        "CapabilityRunContext",
        "CapabilitySearchFilters",
        "CapabilitySelection",
        "CapabilitySpec",
        "ContextPolicy",
        "PolicyDecision",
        "QualitySignals",
        "RiskLevel",
        "RuntimePolicy",
        "SafetyPolicy",
        "TaskEnvelope",
        "TaskNode",
        "TaskPlan",
        "TelemetryEvent",
    },
    "ultimate_ai_agent.core.capabilities.mcp_gateway": {
        "MCP_DEFAULT_BLOCKED_AUTHORITY_REFS",
        "MCP_REVIEW_AUTH_SCOPE",
        "McpActivationPosture",
        "McpApprovalBindingDecision",
        "McpAuthPosture",
        "McpBlockedReceipt",
        "McpDiscoveryToolMetadata",
        "McpExactApprovalContext",
        "McpExactApprovalBinding",
        "McpPreviewContract",
        "McpReplayAuditRecord",
        "McpTransportPosture",
        "build_mcp_blocked_receipt",
        "build_mcp_preview_contract",
        "build_mcp_replay_audit_record",
        "evaluate_mcp_exact_approval_binding",
        "mcp_tool_metadata_to_capability_candidate",
    },
    "ultimate_ai_agent.core.capabilities.observability": {
        "CapabilityEvent",
        "CapabilityEventSink",
        "LoggerCapabilityEventSink",
        "NoopCapabilityEventSink",
    },
    "ultimate_ai_agent.core.capabilities.policy": {"PolicyEngine"},
    "ultimate_ai_agent.core.capabilities.registry": {"CapabilityRegistry"},
    "ultimate_ai_agent.core.capabilities.selection": {
        "DeterministicSelector",
        "LLMSelector",
        "select_capabilities",
    },
    "ultimate_ai_agent.core.capabilities.state": {
        "FileCoordinatorStateStore",
        "InMemoryCoordinatorStateStore",
    },
    "ultimate_ai_agent.core.capabilities.telemetry": {
        "InMemoryTelemetrySink",
        "NoOpTelemetrySink",
        "TelemetrySink",
    },
}

_LAZY_EXPORTS = {
    name: module_name for module_name, names in _EXPORT_GROUPS.items() for name in names
}


def __getattr__(name: str) -> Any:
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    attribute_name = "RiskLevel" if name == "CoordinationRiskLevel" else name
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
