from typing import Any
from ultimate_ai_agent.core.capabilities.catalog import render_compact_catalog
from ultimate_ai_agent.core.capabilities.context import NotesStore, SimpleNotesStore
from ultimate_ai_agent.core.capabilities.coordinator import Coordinator, PolicyDeniedError
from ultimate_ai_agent.core.capabilities.approval import CapabilityApprovalGrant, LocalApprovalAuthority
from ultimate_ai_agent.core.capabilities.decorators import as_registration, capability, get_capability_spec, tool_capability
from ultimate_ai_agent.core.capabilities.defaults import (
    BLOCKED_FOUNDATION_CAPABILITY_NAMES,
    capability_is_foundation_blocked,
    default_foundation_capability_registry,
    foundation_blocked_capability_specs,
)
from ultimate_ai_agent.core.capabilities.a2a_gateway import (
    A2A_DEFAULT_BLOCKED_AUTHORITY_REFS,
    A2A_REVIEW_AUTH_SCOPE,
    A2AActivationPosture,
    A2AAgentMetadata,
    A2AApprovalBindingDecision,
    A2AAuthPosture,
    A2ABlockedReceipt,
    A2AExactDelegationApprovalContext,
    A2AExactDelegationApprovalBinding,
    A2AHandoffProposalEnvelope,
    A2AReplayAuditRecord,
    A2ATrustPosture,
    a2a_agent_card_to_metadata,
    a2a_agent_metadata_to_capability_candidate,
    build_a2a_blocked_receipt,
    build_a2a_handoff_proposal,
    build_a2a_replay_audit_record,
    evaluate_a2a_exact_approval_binding,
    a2a_v1_agent_card_to_metadata,
)
from ultimate_ai_agent.core.capabilities.enums import (
    CapabilityAuthorityLevel,
    CapabilityCostClass,
    CapabilityHealthStatus,
    CapabilityKind,
    CapabilityLatencyClass,
    CapabilityPrivacyLevel,
    CoordinationMode,
    PolicyDecisionStatus,
    RiskLevel as CoordinationRiskLevel,
    SideEffectLevel,
    TaskNodeStatus,
)
from ultimate_ai_agent.core.capabilities.models import (
    Artifact,
    CapabilityCatalogEntry,
    CapabilityHealthReport,
    CapabilityManifest,
    CapabilityPack,
    CapabilityPolicy,
    CapabilityRegistration,
    CapabilityResult,
    CapabilityRunContext,
    CapabilitySearchFilters,
    CapabilitySelection,
    CapabilitySpec,
    ContextPolicy,
    PolicyDecision,
    QualitySignals,
    RiskLevel,
    RuntimePolicy,
    SafetyPolicy,
    TaskEnvelope,
    TaskNode,
    TaskPlan,
    TelemetryEvent,
)
from ultimate_ai_agent.core.capabilities.mcp_gateway import (
    MCP_DEFAULT_BLOCKED_AUTHORITY_REFS,
    MCP_REVIEW_AUTH_SCOPE,
    McpActivationPosture,
    McpApprovalBindingDecision,
    McpAuthPosture,
    McpBlockedReceipt,
    McpDiscoveryToolMetadata,
    McpExactApprovalContext,
    McpExactApprovalBinding,
    McpPreviewContract,
    McpReplayAuditRecord,
    McpTransportPosture,
    build_mcp_blocked_receipt,
    build_mcp_preview_contract,
    build_mcp_replay_audit_record,
    evaluate_mcp_exact_approval_binding,
    mcp_tool_metadata_to_capability_candidate,
)
from ultimate_ai_agent.core.capabilities.observability import (
    CapabilityEvent,
    CapabilityEventSink,
    LoggerCapabilityEventSink,
    NoopCapabilityEventSink,
)
from ultimate_ai_agent.core.capabilities.policy import PolicyEngine
from ultimate_ai_agent.core.capabilities.registry import CapabilityRegistry
from ultimate_ai_agent.core.capabilities.selection import DeterministicSelector, LLMSelector, select_capabilities
from ultimate_ai_agent.core.capabilities.state import FileCoordinatorStateStore, InMemoryCoordinatorStateStore
from ultimate_ai_agent.core.capabilities.telemetry import InMemoryTelemetrySink, NoOpTelemetrySink, TelemetrySink

__all__ = [
    "AgentAdapter",
    "Artifact",
    "A2A_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "A2A_REVIEW_AUTH_SCOPE",
    "A2AActivationPosture",
    "A2AAgentMetadata",
    "A2AApprovalBindingDecision",
    "A2AAuthPosture",
    "A2ABlockedReceipt",
    "A2AExactDelegationApprovalContext",
    "A2AExactDelegationApprovalBinding",
    "A2AHandoffProposalEnvelope",
    "A2AReplayAuditRecord",
    "A2ATrustPosture",
    "CallableCapabilityAdapter",
    "CapabilityAdapter",
    "CapabilityApprovalGrant",
    "CapabilityAuthorityLevel",
    "CapabilityCatalogEntry",
    "CapabilityCostClass",
    "CapabilityEvent",
    "CapabilityEventSink",
    "CapabilityHealthReport",
    "CapabilityHealthStatus",
    "CapabilityKind",
    "CapabilityLatencyClass",
    "CapabilityManifest",
    "CapabilityPack",
    "CapabilityPolicy",
    "CapabilityPrivacyLevel",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilityRunContext",
    "CapabilitySearchFilters",
    "CapabilitySelection",
    "CapabilitySpec",
    "ContextPolicy",
    "CoordinationMode",
    "CoordinationRiskLevel",
    "Coordinator",
    "DeterministicSelector",
    "HandoffAdapter",
    "HumanGateAdapter",
    "FileCoordinatorStateStore",
    "InMemoryTelemetrySink",
    "InMemoryCoordinatorStateStore",
    "LLMSelector",
    "LocalApprovalAuthority",
    "LoggerCapabilityEventSink",
    "MCP_DEFAULT_BLOCKED_AUTHORITY_REFS",
    "MCP_REVIEW_AUTH_SCOPE",
    "McpActivationPosture",
    "McpApprovalBindingDecision",
    "McpAuthPosture",
    "McpBlockedReceipt",
    "McpDiscoveryToolMetadata",
    "McpExactApprovalContext",
    "McpExactApprovalBinding",
    "McpPreviewContract",
    "McpReplayAuditRecord",
    "McpTransportPosture",
    "NoOpTelemetrySink",
    "NoopCapabilityEventSink",
    "NotesStore",
    "PolicyDecision",
    "PolicyDecisionStatus",
    "PolicyDeniedError",
    "PolicyEngine",
    "QualitySignals",
    "ReviewerAdapter",
    "RiskLevel",
    "RuntimePolicy",
    "SafetyPolicy",
    "SideEffectLevel",
    "SimpleNotesStore",
    "TaskEnvelope",
    "TaskNode",
    "TaskNodeStatus",
    "TaskPlan",
    "TelemetryEvent",
    "TelemetrySink",
    "ToolAdapter",
    "WorkflowAdapter",
    "BLOCKED_FOUNDATION_CAPABILITY_NAMES",
    "as_registration",
    "a2a_agent_card_to_metadata",
    "a2a_v1_agent_card_to_metadata",
    "a2a_agent_metadata_to_capability_candidate",
    "build_a2a_blocked_receipt",
    "build_a2a_handoff_proposal",
    "build_a2a_replay_audit_record",
    "capability_is_foundation_blocked",
    "capability",
    "default_foundation_capability_registry",
    "foundation_blocked_capability_specs",
    "get_capability_spec",
    "build_mcp_blocked_receipt",
    "build_mcp_preview_contract",
    "build_mcp_replay_audit_record",
    "evaluate_mcp_exact_approval_binding",
    "evaluate_a2a_exact_approval_binding",
    "mcp_tool_metadata_to_capability_candidate",
    "render_compact_catalog",
    "select_capabilities",
    "tool_capability",
    "wrap_agent",
    "wrap_tool",
]

_ADAPTER_EXPORTS = {
    "AgentAdapter",
    "CallableCapabilityAdapter",
    "CapabilityAdapter",
    "HandoffAdapter",
    "HumanGateAdapter",
    "ReviewerAdapter",
    "ToolAdapter",
    "WorkflowAdapter",
    "wrap_agent",
    "wrap_tool",
}

def __getattr__(name: str) -> Any:
    if name in _ADAPTER_EXPORTS:
        from ultimate_ai_agent.core.capabilities import adapters

        value = getattr(adapters, name)
        globals()[name] = value
        return value
    raise AttributeError(name)
