from typing import TYPE_CHECKING, Any

from ultimate_ai_agent.core.control_center.action_decisions import (
    ACTION_DECISION_REQUESTED_ACTION,
    FOUNDER_LOOP_ACTION_DECISION_BLOCKED_REFS,
    FOUNDER_LOOP_ACTION_DECISION_KINDS,
    FOUNDER_LOOP_ACTION_DECISION_ROUTE_REFS,
    FOUNDER_LOOP_ACTION_ENVELOPE_PROMOTION_STATUS,
    FOUNDER_LOOP_ACTION_ENVELOPE_ROUTE_REFS,
    FOUNDER_LOOP_ACTION_STATE_CONTRACT_REF,
    FOUNDER_LOOP_ACTION_STATUSES,
    FOUNDER_LOOP_VERTICAL_SLICE_CONTRACT_REF,
    FounderLoopActionDecisionReceipt,
    FounderLoopActionDecisionRequest,
    FounderLoopActionEnvelope,
    FounderLoopActionEnvelopePromotionReceipt,
    FounderLoopActionEnvelopePromotionRequest,
)
from ultimate_ai_agent.core.control_center.local_tasks import (
    FOUNDER_LOOP_LOCAL_TASK_BLOCKED_REFS,
    FOUNDER_LOOP_LOCAL_TASK_COMMIT_CONTRACT_REF,
    FOUNDER_LOOP_LOCAL_TASK_COMMIT_ROUTE_REF,
    FOUNDER_LOOP_LOCAL_TASK_CREATE_ACTION_KIND,
    FounderLoopLocalTaskCommitReceipt,
    FounderLoopLocalTaskCommitRequest,
)
from ultimate_ai_agent.core.control_center.today_loop import (
    TODAY_LOOP_LANE_ORDER,
    TODAY_LOOP_READ_MODEL_SOURCE,
    TODAY_LOOP_REQUIRED_BLOCKED_REFS,
    TODAY_LOOP_TIGHTENING_CONTRACT_REF,
    TodayLoopDigestItem,
    TodayLoopLane,
    TodayLoopReadModel,
    build_today_loop_read_model,
)
from ultimate_ai_agent.core.control_center.follow_up_tracker import (
    FOLLOW_UP_TRACKER_CATEGORY_ORDER,
    FOLLOW_UP_TRACKER_CONTRACT_REF,
    FOLLOW_UP_TRACKER_READ_MODEL_SOURCE,
    FOLLOW_UP_TRACKER_REQUIRED_BLOCKED_REFS,
    FollowUpTrackerItem,
    FollowUpTrackerReadModel,
    build_follow_up_tracker_read_model,
)
from ultimate_ai_agent.core.control_center.action_inbox_decision_lanes import (
    ACTION_INBOX_DECISION_LANE_CONTRACT_REF,
    ACTION_INBOX_DECISION_LANE_ORDER,
    ACTION_INBOX_DECISION_LANE_READ_MODEL_SOURCE,
    ACTION_INBOX_DECISION_LANE_REQUIRED_BLOCKED_REFS,
    ActionInboxDecisionLane,
    ActionInboxDecisionLaneItem,
    ActionInboxDecisionLaneReadModel,
    build_action_inbox_decision_lane_read_model,
)
from ultimate_ai_agent.core.control_center.plans_to_actions import (
    PLANS_TO_ACTIONS_BRIDGE_CONTRACT_REF,
    PLANS_TO_ACTIONS_BRIDGE_READ_MODEL_SOURCE,
    PLANS_TO_ACTIONS_BRIDGE_REQUIRED_BLOCKED_REFS,
    PlansToActionsBridgeItem,
    PlansToActionsBridgeReadModel,
    build_plans_to_actions_bridge_read_model,
)
from ultimate_ai_agent.core.control_center.morning_briefing import (
    MORNING_BRIEFING_V1_CONTRACT_REF,
    MORNING_BRIEFING_V1_READ_MODEL_SOURCE,
    MORNING_BRIEFING_V1_REQUIRED_BLOCKED_REFS,
    MorningBriefingV1ReadModel,
    build_morning_briefing_v1_read_model,
)
from ultimate_ai_agent.core.control_center.weekly_ceo_review import (
    WEEKLY_CEO_REVIEW_V1_CONTRACT_REF,
    WEEKLY_CEO_REVIEW_V1_READ_MODEL_SOURCE,
    WEEKLY_CEO_REVIEW_V1_REQUIRED_BLOCKED_REFS,
    WeeklyCeoReviewV1ReadModel,
    build_weekly_ceo_review_v1_read_model,
)
from ultimate_ai_agent.core.control_center.chat_to_loop_handoff import (
    CHAT_TO_LOOP_HANDOFF_CONTRACT_REF,
    CHAT_TO_LOOP_HANDOFF_OUTCOME_KINDS,
    CHAT_TO_LOOP_HANDOFF_READ_MODEL_SOURCE,
    CHAT_TO_LOOP_HANDOFF_REQUIRED_BLOCKED_REFS,
    ChatToLoopHandoffOutcome,
    ChatToLoopHandoffReadModel,
    build_chat_to_loop_handoff_read_model,
)
from ultimate_ai_agent.core.control_center.actions import (
    ControlCenterActionPreviewDecision,
    ControlCenterActionPreviewRequest,
    preview_control_center_action,
)

from ultimate_ai_agent.core.control_center.dashboard import (
    ApiSummary,
    ApprovalSummary,
    ControlCenterDashboardSnapshot,
    GateSummary,
    GovernedProviderInvocationReadiness,
    MobilePlanningSummary,
    OperatorLoopStepSummary,
    OperatorLoopSummary,
    PluginGovernanceSummary,
    PrivateMeshSummary,
    ProviderCredentialEnrollmentReadiness,
    ProviderCostGovernorBinding,
    ProviderCredentialReadinessPosture,
    ProviderCredentialReadinessItem,
    ProviderCredentialReadinessSummary,
    ProviderCredentialValidationReadiness,
    ProviderCredentialVaultAdapterReadiness,
    RemoteWorkerSummary,
    RuntimeReadinessSummary,
    StatusCard,
    build_control_center_dashboard,
    build_operator_loop_summary,
    build_provider_credential_readiness_summary,
)
from ultimate_ai_agent.core.control_center.enums import (
    ControlCenterActionDecisionStatus,
    ControlCenterActionKind,
    ControlCenterCapabilityStatus,
    ControlCenterRiskLevel,
    ControlCenterSurface,
)
from ultimate_ai_agent.core.control_center.manifest import (
    CONTROL_CENTER_ROUTES,
    ControlCenterManifest,
    ControlCenterSurfaceManifest,
    build_control_center_manifest,
)

if TYPE_CHECKING:
    from ultimate_ai_agent.core.control_center.founder_loop import (
        FounderLoopControlCenterService,
    )


def __getattr__(name: str) -> Any:
    if name == "FounderLoopControlCenterService":
        from ultimate_ai_agent.core.control_center.founder_loop import (
            FounderLoopControlCenterService,
        )

        return FounderLoopControlCenterService
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "ACTION_DECISION_REQUESTED_ACTION",
    "ACTION_INBOX_DECISION_LANE_CONTRACT_REF",
    "ACTION_INBOX_DECISION_LANE_ORDER",
    "ACTION_INBOX_DECISION_LANE_READ_MODEL_SOURCE",
    "ACTION_INBOX_DECISION_LANE_REQUIRED_BLOCKED_REFS",
    "ApiSummary",
    "ApprovalSummary",
    "CONTROL_CENTER_ROUTES",
    "ControlCenterActionDecisionStatus",
    "ControlCenterActionKind",
    "ControlCenterActionPreviewDecision",
    "ControlCenterActionPreviewRequest",
    "ControlCenterCapabilityStatus",
    "ControlCenterDashboardSnapshot",
    "ControlCenterManifest",
    "ControlCenterRiskLevel",
    "ControlCenterSurface",
    "ControlCenterSurfaceManifest",
    "FOUNDER_LOOP_ACTION_DECISION_BLOCKED_REFS",
    "FOUNDER_LOOP_ACTION_DECISION_KINDS",
    "FOUNDER_LOOP_ACTION_DECISION_ROUTE_REFS",
    "FOUNDER_LOOP_ACTION_ENVELOPE_PROMOTION_STATUS",
    "FOUNDER_LOOP_ACTION_ENVELOPE_ROUTE_REFS",
    "FOUNDER_LOOP_ACTION_STATE_CONTRACT_REF",
    "FOUNDER_LOOP_ACTION_STATUSES",
    "FOUNDER_LOOP_VERTICAL_SLICE_CONTRACT_REF",
    "FOUNDER_LOOP_LOCAL_TASK_BLOCKED_REFS",
    "FOUNDER_LOOP_LOCAL_TASK_COMMIT_CONTRACT_REF",
    "FOUNDER_LOOP_LOCAL_TASK_COMMIT_ROUTE_REF",
    "FOUNDER_LOOP_LOCAL_TASK_CREATE_ACTION_KIND",
    "FOLLOW_UP_TRACKER_CATEGORY_ORDER",
    "FOLLOW_UP_TRACKER_CONTRACT_REF",
    "FOLLOW_UP_TRACKER_READ_MODEL_SOURCE",
    "FOLLOW_UP_TRACKER_REQUIRED_BLOCKED_REFS",
    "MORNING_BRIEFING_V1_CONTRACT_REF",
    "MORNING_BRIEFING_V1_READ_MODEL_SOURCE",
    "MORNING_BRIEFING_V1_REQUIRED_BLOCKED_REFS",
    "PLANS_TO_ACTIONS_BRIDGE_CONTRACT_REF",
    "PLANS_TO_ACTIONS_BRIDGE_READ_MODEL_SOURCE",
    "PLANS_TO_ACTIONS_BRIDGE_REQUIRED_BLOCKED_REFS",
    "TODAY_LOOP_LANE_ORDER",
    "TODAY_LOOP_READ_MODEL_SOURCE",
    "TODAY_LOOP_REQUIRED_BLOCKED_REFS",
    "TODAY_LOOP_TIGHTENING_CONTRACT_REF",
    "WEEKLY_CEO_REVIEW_V1_CONTRACT_REF",
    "WEEKLY_CEO_REVIEW_V1_READ_MODEL_SOURCE",
    "WEEKLY_CEO_REVIEW_V1_REQUIRED_BLOCKED_REFS",
    "CHAT_TO_LOOP_HANDOFF_CONTRACT_REF",
    "CHAT_TO_LOOP_HANDOFF_OUTCOME_KINDS",
    "CHAT_TO_LOOP_HANDOFF_READ_MODEL_SOURCE",
    "CHAT_TO_LOOP_HANDOFF_REQUIRED_BLOCKED_REFS",
    "FounderLoopControlCenterService",
    "FounderLoopActionDecisionReceipt",
    "FounderLoopActionDecisionRequest",
    "FounderLoopActionEnvelope",
    "FounderLoopActionEnvelopePromotionReceipt",
    "FounderLoopActionEnvelopePromotionRequest",
    "FounderLoopLocalTaskCommitReceipt",
    "FounderLoopLocalTaskCommitRequest",
    "ActionInboxDecisionLane",
    "ActionInboxDecisionLaneItem",
    "ActionInboxDecisionLaneReadModel",
    "FollowUpTrackerItem",
    "FollowUpTrackerReadModel",
    "PlansToActionsBridgeItem",
    "PlansToActionsBridgeReadModel",
    "MorningBriefingV1ReadModel",
    "TodayLoopDigestItem",
    "TodayLoopLane",
    "TodayLoopReadModel",
    "WeeklyCeoReviewV1ReadModel",
    "ChatToLoopHandoffOutcome",
    "ChatToLoopHandoffReadModel",
    "GateSummary",
    "GovernedProviderInvocationReadiness",
    "MobilePlanningSummary",
    "OperatorLoopStepSummary",
    "OperatorLoopSummary",
    "PluginGovernanceSummary",
    "PrivateMeshSummary",
    "ProviderCredentialEnrollmentReadiness",
    "ProviderCostGovernorBinding",
    "ProviderCredentialReadinessPosture",
    "ProviderCredentialReadinessItem",
    "ProviderCredentialReadinessSummary",
    "ProviderCredentialValidationReadiness",
    "ProviderCredentialVaultAdapterReadiness",
    "RemoteWorkerSummary",
    "RuntimeReadinessSummary",
    "StatusCard",
    "build_control_center_dashboard",
    "build_operator_loop_summary",
    "build_provider_credential_readiness_summary",
    "build_control_center_manifest",
    "build_action_inbox_decision_lane_read_model",
    "build_follow_up_tracker_read_model",
    "build_morning_briefing_v1_read_model",
    "build_plans_to_actions_bridge_read_model",
    "build_today_loop_read_model",
    "build_weekly_ceo_review_v1_read_model",
    "build_chat_to_loop_handoff_read_model",
    "preview_control_center_action",
]
