from typing import List

from pydantic import BaseModel, ConfigDict, Field

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


class FoundationGateCriterion(BaseModel):
    criterion_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    severity: str = Field(..., min_length=1)
    required: bool = True
    category: FoundationGateCategory
    evaluator_ref: str = Field(..., min_length=1)
    pass_condition: str = Field(..., min_length=1)
    failure_message: str = Field(..., min_length=1)

    model_config = ConfigDict(use_enum_values=True, extra="forbid")


def _criterion(
    criterion_id: str,
    name: str,
    category: FoundationGateCategory,
    evaluator_ref: str,
    pass_condition: str,
    failure_message: str,
    severity: str = "high",
) -> FoundationGateCriterion:
    return FoundationGateCriterion(
        criterion_id=criterion_id,
        name=name,
        description=pass_condition,
        severity=severity,
        required=True,
        category=category,
        evaluator_ref=evaluator_ref,
        pass_condition=pass_condition,
        failure_message=failure_message,
    )


def default_foundation_gate_criteria() -> List[FoundationGateCriterion]:
    return [
        _criterion(
            "versioning_consistent",
            "Versioning Consistency",
            FoundationGateCategory.versioning,
            "FoundationGateEvaluator.check_versioning_consistent",
            "VERSION.md, pyproject.toml, package __version__, README start refs, and release docs agree.",
            "Versioned baseline files are inconsistent.",
        ),
        _criterion(
            "release_docs_present",
            "Release Documentation Present",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_release_docs_present",
            "M6 import README, master plan, release notes, and implementation plan are present.",
            "M6 release documentation is missing.",
        ),
        _criterion(
            "foundation_modules_present",
            "Foundation Modules Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_foundation_modules_present",
            "M1 through M6 foundation packages and scripts exist.",
            "Required foundation module files are missing.",
        ),
        _criterion(
            "blocked_modules_absent",
            "Blocked Modules Absent",
            FoundationGateCategory.blocked_modules,
            "FoundationGateEvaluator.check_blocked_modules_absent",
            "Scanners, companion proactivity, Skill Factory, self-improvement, autopilot, SDK/A2A delegation, and browser automation runtimes are absent.",
            "A module blocked for M6 exists in runtime source.",
            "critical",
        ),
        _criterion(
            "forbidden_runtime_integrations_absent",
            "Forbidden Runtime Integrations Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_forbidden_runtime_integrations_absent",
            "Runtime source has no real provider, model, web, vector DB, pgvector, embedding, or production truth imports.",
            "Forbidden runtime integration import or call was detected.",
            "critical",
        ),
        _criterion(
            "shell_execution_absent",
            "Runtime Shell Execution Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_shell_execution_absent",
            "Runtime source does not load process-spawning modules or execute shell commands.",
            "Runtime source contains shell execution capability.",
            "critical",
        ),
        _criterion(
            "broad_filesystem_scanning_absent",
            "Broad Filesystem Scanning Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_broad_filesystem_scanning_absent",
            "Runtime source does not use broad filesystem walks or home-directory traversal.",
            "Runtime source contains broad filesystem scanning.",
            "critical",
        ),
        _criterion(
            "secret_hygiene_clean",
            "Secret Hygiene Clean",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_secret_hygiene_clean",
            "Gate outputs and runtime source contain no raw secrets, private keys, or secret assignment payloads.",
            "Secret-like content was detected.",
            "critical",
        ),
        _criterion(
            "tool_broker_blocks_advanced_adapters",
            "Tool Broker Blocks Advanced Adapters",
            FoundationGateCategory.tool_broker,
            "FoundationGateEvaluator.check_tool_broker_blocks_advanced_adapters",
            "MCP, A2A, SDK adapter, and Skill tool categories remain blocked by the Tool Broker.",
            "An advanced adapter category was not blocked.",
            "critical",
        ),
        _criterion(
            "truth_evidence_contracts_valid",
            "Truth Evidence Contracts Valid",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_truth_evidence_contracts_valid",
            "Truth source and evidence governance contracts require references for supported claims.",
            "Truth/evidence contract validation failed.",
        ),
        _criterion(
            "memory_file_contracts_valid",
            "Memory and File Contracts Valid",
            FoundationGateCategory.memory,
            "FoundationGateEvaluator.check_memory_file_contracts_valid",
            "Memory remains recall-only and file references reject unsafe paths and secrets.",
            "Memory/file contract validation failed.",
        ),
        _criterion(
            "m5_shadow_replay_passes",
            "M5 Shadow Replay Passes",
            FoundationGateCategory.rollback,
            "FoundationGateEvaluator.check_m5_shadow_replay_passes",
            "The M5 local/dev kernel trace replays with ordered events, receipt, rollback, memory refs, and no secret leakage.",
            "M5 shadow replay failed.",
            "critical",
        ),
        _criterion(
            "m7_modules_present",
            "M7 Modules Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m7_modules_present",
            "M7 model router and cost/resource governor policy modules exist.",
            "Required M7 module files are missing.",
        ),
        _criterion(
            "model_router_decision_only",
            "Model Router Decision Only",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_model_router_decision_only",
            "Model Router produces deterministic metadata-only route decisions without model/provider execution.",
            "Model Router decision-only contract failed.",
            "critical",
        ),
        _criterion(
            "cost_governor_blocks_over_budget",
            "Cost Governor Blocks Over Budget",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_cost_governor_blocks_over_budget",
            "Cost Governor denies over-budget routes deterministically.",
            "Cost Governor over-budget denial failed.",
            "critical",
        ),
        _criterion(
            "m7_arbitrary_approval_ref_rejected",
            "M7 Arbitrary Approval Ref Rejected",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_arbitrary_approval_ref_rejected",
            "Arbitrary approval_ref values do not authorize sensitive cloud model routes.",
            "Arbitrary approval_ref authorized a sensitive cloud route.",
            "critical",
        ),
        _criterion(
            "m7_context_budget_exhaustion_blocks_route",
            "M7 Context Budget Exhaustion Blocks Route",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_context_budget_exhaustion_blocks_route",
            "Exhausted available history budget prevents model route selection.",
            "Exhausted context budget allowed a model route.",
            "critical",
        ),
        _criterion(
            "m7_soft_budget_warning_allows_route",
            "M7 Soft Budget Warning Allows Route",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_m7_soft_budget_warning_allows_route",
            "Soft budget overages remain allowed with warning.",
            "Soft budget overage did not allow with warning.",
            "critical",
        ),
        _criterion(
            "m7_hard_budget_denies_route",
            "M7 Hard Budget Denies Route",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_m7_hard_budget_denies_route",
            "Hard budget overages deny routes.",
            "Hard budget overage did not deny the route.",
            "critical",
        ),
        _criterion(
            "m7_cost_warnings_visible_in_route_decision",
            "M7 Cost Warnings Visible In Route Decision",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_cost_warnings_visible_in_route_decision",
            "Route decisions preserve soft-budget warning reason codes.",
            "Route decision did not preserve cost warning reason codes.",
            "critical",
        ),
        _criterion(
            "api_manifest_endpoint_present",
            "API Manifest Endpoint Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_api_manifest_endpoint_present",
            "/api/manifest exposes typed metadata for the current API boundary.",
            "API manifest endpoint is missing or invalid.",
        ),
        _criterion(
            "openapi_contract_valid",
            "OpenAPI Contract Valid",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_openapi_contract_valid",
            "OpenAPI generation succeeds, matches the active version, and route inventory is valid.",
            "OpenAPI contract verification failed.",
            "critical",
        ),
        _criterion(
            "api_operation_ids_unique",
            "API Operation IDs Unique",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_api_operation_ids_unique",
            "All API routes have unique stable operation IDs.",
            "API operation IDs are missing or duplicated.",
            "critical",
        ),
        _criterion(
            "forbidden_runtime_routes_absent",
            "Forbidden Runtime Routes Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_forbidden_runtime_routes_absent",
            "API boundary exposes no runtime model-call, provider-call, web-fetch, browser, scanner, or tool-execution routes.",
            "Forbidden runtime route was detected.",
            "critical",
        ),
        _criterion(
            "agents_md_guidance_present",
            "AGENTS Guidance Present",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_agents_md_guidance_present",
            "AGENTS.md and API boundary docs define workspace and API contract standards.",
            "AGENTS.md or API boundary documentation is missing.",
        ),
        _criterion(
            "runtime_agent_config_loading_absent",
            "Runtime Agent Config Loading Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_runtime_agent_config_loading_absent",
            "Runtime source does not load AGENTS.md, agent config files, or workspace config at request time.",
            "Runtime agent configuration loading was detected.",
            "critical",
        ),
        _criterion(
            "m8_model_runtime_files_present",
            "M8 Model Runtime Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_model_runtime_files_present",
            "M8 simulated model runtime contracts, validation, simulator, and adapter modules exist.",
            "Required M8 model runtime files are missing.",
        ),
        _criterion(
            "m8_runtime_kinds_stub_only",
            "M8 Runtime Kinds Stub Only",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_runtime_kinds_stub_only",
            "Model runtime adapter kinds are limited to simulated and stub variants.",
            "A non-stub model runtime kind was detected.",
            "critical",
        ),
        _criterion(
            "m8_model_runtime_no_real_calls",
            "M8 Model Runtime No Real Calls",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_model_runtime_no_real_calls",
            "Model runtime source has no provider SDK, network, tokenizer, billing, shell, or live runtime call path.",
            "A real model/runtime integration was detected in M8 source.",
            "critical",
        ),
        _criterion(
            "m8_simulation_endpoint_safe",
            "M8 Simulation Endpoint Safe",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_simulation_endpoint_safe",
            "/model-runtime/simulate exists and is explicitly simulated.",
            "The M8 simulation endpoint is missing or unsafe.",
            "critical",
        ),
        _criterion(
            "m8_runtime_responses_simulated_only",
            "M8 Runtime Responses Simulated Only",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_runtime_responses_simulated_only",
            "Model runtime responses are marked simulated and are not truth authority.",
            "A model runtime response was not clearly simulated.",
            "critical",
        ),
        _criterion(
            "m8_runtime_secret_prompt_blocked",
            "M8 Runtime Secret Prompt Blocked",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_runtime_secret_prompt_blocked",
            "Secret-like prompt summaries are rejected before simulation.",
            "Secret-like runtime prompt content was accepted.",
            "critical",
        ),
        _criterion(
            "m8_api_validation_secret_echo_absent",
            "M8 API Validation Secret Echo Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_api_validation_secret_echo_absent",
            "M8 API validation errors do not echo secret-like manifest or request payload values.",
            "M8 API validation errors echoed secret-like input.",
            "critical",
        ),
        _criterion(
            "m85_approval_authority_files_present",
            "M8.5 Approval Authority Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m85_approval_authority_files_present",
            "M8.5 approval request, grant, validation, authority, policy, and receipt modules exist.",
            "Required M8.5 approval authority files are missing.",
            "critical",
        ),
        _criterion(
            "m85_arbitrary_approval_refs_rejected",
            "M8.5 Arbitrary Approval Refs Rejected",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_arbitrary_approval_refs_rejected",
            "LocalApprovalAuthority rejects arbitrary approval_ref strings.",
            "An arbitrary approval_ref was accepted as authority.",
            "critical",
        ),
        _criterion(
            "m85_local_approval_grant_validates",
            "M8.5 Local Approval Grant Validates",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_local_approval_grant_validates",
            "A scoped LocalApprovalAuthority grant validates for its exact subject/action/resource.",
            "A valid local/dev approval grant did not validate.",
            "critical",
        ),
        _criterion(
            "m85_expired_revoked_approval_denies",
            "M8.5 Expired Revoked Approval Denies",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_expired_revoked_approval_denies",
            "Expired and revoked approval grants are denied.",
            "Expired or revoked approval was accepted.",
            "critical",
        ),
        _criterion(
            "m85_router_uses_valid_approval_grant",
            "M8.5 Router Uses Valid Approval Grant",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m85_router_uses_valid_approval_grant",
            "Model Router can use a valid local/dev approval grant for sensitive cloud route metadata decisions.",
            "Model Router did not honor a valid approval grant.",
            "critical",
        ),
        _criterion(
            "m85_runtime_factory_rejects_arbitrary_approval",
            "M8.5 Runtime Factory Rejects Arbitrary Approval",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_runtime_factory_rejects_arbitrary_approval",
            "Model runtime request factory rejects non-test approval refs without a validated approval decision.",
            "Model runtime factory accepted an arbitrary approval ref.",
            "critical",
        ),
        _criterion(
            "m85_tool_broker_rejects_arbitrary_approval",
            "M8.5 Tool Broker Rejects Arbitrary Approval",
            FoundationGateCategory.tool_broker,
            "FoundationGateEvaluator.check_m85_tool_broker_rejects_arbitrary_approval",
            "Tool Broker keeps high-risk actions approval-required for arbitrary approval refs.",
            "Tool Broker accepted an arbitrary approval ref.",
            "critical",
        ),
        _criterion(
            "m85_no_real_auth_oauth_network",
            "M8.5 No Real Auth OAuth Network",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_no_real_auth_oauth_network",
            "Approval authority source has no production auth, OAuth, network, provider SDK, or persistence imports.",
            "M8.5 added real auth, OAuth, network, or persistence code.",
            "critical",
        ),
        _criterion(
            "m85_approval_api_secret_echo_absent",
            "M8.5 Approval API Secret Echo Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_approval_api_secret_echo_absent",
            "Approval API validation errors do not echo secret-like payload values.",
            "Approval API validation echoed secret-like input.",
            "critical",
        ),
        _criterion(
            "m9_loopback_runtime_files_present",
            "M9 Loopback Runtime Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m9_loopback_runtime_files_present",
            "M9 loopback endpoint, policy, transport, and local adapter files exist.",
            "Required M9 loopback runtime files are missing.",
            "critical",
        ),
        _criterion(
            "m9_non_loopback_endpoints_denied",
            "M9 Non Loopback Endpoints Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_non_loopback_endpoints_denied",
            "Remote hosts, URL credentials, and secret-like query parameters are denied.",
            "A non-loopback or credential-bearing endpoint was accepted.",
            "critical",
        ),
        _criterion(
            "m9_non_loopback_policy_override_denied",
            "M9 Non Loopback Policy Override Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_non_loopback_policy_override_denied",
            "Caller-supplied allowed_hosts and deny_non_loopback=false cannot authorize remote hosts.",
            "A caller policy override authorized a non-loopback endpoint.",
            "critical",
        ),
        _criterion(
            "m9_loopback_policy_model_rejects_hostile_inputs",
            "M9 Loopback Policy Model Rejects Hostile Inputs",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_loopback_policy_model_rejects_hostile_inputs",
            "LoopbackRuntimePolicy rejects deny_non_loopback=false and non-loopback allowed_hosts.",
            "Loopback runtime policy accepted a hostile weakening input.",
            "critical",
        ),
        _criterion(
            "m9_public_and_private_ip_endpoints_denied",
            "M9 Public And Private IP Endpoints Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_public_and_private_ip_endpoints_denied",
            "Private LAN and public IP endpoints are denied by loopback endpoint validation.",
            "A private LAN or public IP endpoint was accepted.",
            "critical",
        ),
        _criterion(
            "m9_approval_api_uses_public_authority_helper",
            "M9 Approval API Uses Public Authority Helper",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_approval_api_uses_public_authority_helper",
            "Approval API loads validation grants through a public LocalApprovalAuthority helper.",
            "Approval API mutates LocalApprovalAuthority private grant state directly.",
            "critical",
        ),
        _criterion(
            "m9_arbitrary_approval_refs_denied",
            "M9 Arbitrary Approval Refs Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_arbitrary_approval_refs_denied",
            "Arbitrary approval_ref strings cannot authorize local loopback execution.",
            "An arbitrary approval_ref authorized local loopback execution.",
            "critical",
        ),
        _criterion(
            "m9_fake_transport_only_in_gate",
            "M9 Fake Transport Only In Gate",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_fake_transport_only_in_gate",
            "Foundation Gate uses fake transport only and M9 runtime code has no requests/httpx/provider SDK/tokenizer/billing imports.",
            "M9 introduced a real provider, network, tokenizer, billing, or gate transport path.",
            "critical",
        ),
        _criterion(
            "m9_simulated_fallback_available",
            "M9 Simulated Fallback Available",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m9_simulated_fallback_available",
            "Blocked local loopback execution returns simulated fallback when policy requires it.",
            "M9 simulated fallback is unavailable.",
            "critical",
        ),
        _criterion(
            "m9_model_output_not_truth_authority",
            "M9 Model Output Not Truth Authority",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_m9_model_output_not_truth_authority",
            "Local loopback and fallback responses are marked non-authoritative.",
            "M9 model output was treated as truth authority.",
            "critical",
        ),
    ]
