from typing import List

from pydantic import BaseModel, ConfigDict, Field

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


class FoundationGateCriterion(BaseModel):
    criterion_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=1)
    severity: str = Field(..., min_length=1)
    required: bool = True
    category: FoundationGateCategory
    evaluator_ref: str = Field(..., min_length=1)
    pass_condition: str = Field(..., min_length=1)
    failure_message: str = Field(..., min_length=1)

    model_config = ConfigDict(use_enum_values=True, extra="forbid")


def _criterion(
    criterion_id: str,
    name: str,
    category: FoundationGateCategory,
    evaluator_ref: str,
    pass_condition: str,
    failure_message: str,
    severity: str = "high",
) -> FoundationGateCriterion:
    return FoundationGateCriterion(
        criterion_id=criterion_id,
        name=name,
        description=pass_condition,
        severity=severity,
        required=True,
        category=category,
        evaluator_ref=evaluator_ref,
        pass_condition=pass_condition,
        failure_message=failure_message,
    )


def default_foundation_gate_criteria() -> List[FoundationGateCriterion]:
    return [
        _criterion(
            "versioning_consistent",
            "Versioning Consistency",
            FoundationGateCategory.versioning,
            "FoundationGateEvaluator.check_versioning_consistent",
            "VERSION.md, pyproject.toml, package __version__, README start refs, and release docs agree.",
            "Versioned baseline files are inconsistent.",
        ),
        _criterion(
            "release_docs_present",
            "Release Documentation Present",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_release_docs_present",
            "M6 import README, master plan, release notes, and implementation plan are present.",
            "M6 release documentation is missing.",
        ),
        _criterion(
            "foundation_modules_present",
            "Foundation Modules Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_foundation_modules_present",
            "M1 through M6 foundation packages and scripts exist.",
            "Required foundation module files are missing.",
        ),
        _criterion(
            "blocked_modules_absent",
            "Blocked Modules Absent",
            FoundationGateCategory.blocked_modules,
            "FoundationGateEvaluator.check_blocked_modules_absent",
            "Scanners, companion proactivity, Skill Factory, self-improvement, autopilot, SDK/A2A delegation, and browser automation runtimes are absent.",
            "A module blocked for M6 exists in runtime source.",
            "critical",
        ),
        _criterion(
            "forbidden_runtime_integrations_absent",
            "Forbidden Runtime Integrations Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_forbidden_runtime_integrations_absent",
            "Runtime source has no real provider, model, web, vector DB, pgvector, embedding, or production truth imports.",
            "Forbidden runtime integration import or call was detected.",
            "critical",
        ),
        _criterion(
            "shell_execution_absent",
            "Runtime Shell Execution Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_shell_execution_absent",
            "Runtime source does not load process-spawning modules or execute shell commands.",
            "Runtime source contains shell execution capability.",
            "critical",
        ),
        _criterion(
            "broad_filesystem_scanning_absent",
            "Broad Filesystem Scanning Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_broad_filesystem_scanning_absent",
            "Runtime source does not use broad filesystem walks or home-directory traversal.",
            "Runtime source contains broad filesystem scanning.",
            "critical",
        ),
        _criterion(
            "secret_hygiene_clean",
            "Secret Hygiene Clean",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_secret_hygiene_clean",
            "Gate outputs and runtime source contain no raw secrets, private keys, or secret assignment payloads.",
            "Secret-like content was detected.",
            "critical",
        ),
        _criterion(
            "tool_broker_blocks_advanced_adapters",
            "Tool Broker Blocks Advanced Adapters",
            FoundationGateCategory.tool_broker,
            "FoundationGateEvaluator.check_tool_broker_blocks_advanced_adapters",
            "MCP, A2A, SDK adapter, and Skill tool categories remain blocked by the Tool Broker.",
            "An advanced adapter category was not blocked.",
            "critical",
        ),
        _criterion(
            "truth_evidence_contracts_valid",
            "Truth Evidence Contracts Valid",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_truth_evidence_contracts_valid",
            "Truth source and evidence governance contracts require references for supported claims.",
            "Truth/evidence contract validation failed.",
        ),
        _criterion(
            "memory_file_contracts_valid",
            "Memory and File Contracts Valid",
            FoundationGateCategory.memory,
            "FoundationGateEvaluator.check_memory_file_contracts_valid",
            "Memory remains recall-only and file references reject unsafe paths and secrets.",
            "Memory/file contract validation failed.",
        ),
        _criterion(
            "m5_shadow_replay_passes",
            "M5 Shadow Replay Passes",
            FoundationGateCategory.rollback,
            "FoundationGateEvaluator.check_m5_shadow_replay_passes",
            "The M5 local/dev kernel trace replays with ordered events, receipt, rollback, memory refs, and no secret leakage.",
            "M5 shadow replay failed.",
            "critical",
        ),
        _criterion(
            "m7_modules_present",
            "M7 Modules Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m7_modules_present",
            "M7 model router and cost/resource governor policy modules exist.",
            "Required M7 module files are missing.",
        ),
        _criterion(
            "model_router_decision_only",
            "Model Router Decision Only",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_model_router_decision_only",
            "Model Router produces deterministic metadata-only route decisions without model/provider execution.",
            "Model Router decision-only contract failed.",
            "critical",
        ),
        _criterion(
            "cost_governor_blocks_over_budget",
            "Cost Governor Blocks Over Budget",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_cost_governor_blocks_over_budget",
            "Cost Governor denies over-budget routes deterministically.",
            "Cost Governor over-budget denial failed.",
            "critical",
        ),
        _criterion(
            "m7_arbitrary_approval_ref_rejected",
            "M7 Arbitrary Approval Ref Rejected",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_arbitrary_approval_ref_rejected",
            "Arbitrary approval_ref values do not authorize sensitive cloud model routes.",
            "Arbitrary approval_ref authorized a sensitive cloud route.",
            "critical",
        ),
        _criterion(
            "m7_context_budget_exhaustion_blocks_route",
            "M7 Context Budget Exhaustion Blocks Route",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_context_budget_exhaustion_blocks_route",
            "Exhausted available history budget prevents model route selection.",
            "Exhausted context budget allowed a model route.",
            "critical",
        ),
        _criterion(
            "m7_soft_budget_warning_allows_route",
            "M7 Soft Budget Warning Allows Route",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_m7_soft_budget_warning_allows_route",
            "Soft budget overages remain allowed with warning.",
            "Soft budget overage did not allow with warning.",
            "critical",
        ),
        _criterion(
            "m7_hard_budget_denies_route",
            "M7 Hard Budget Denies Route",
            FoundationGateCategory.cost_governor,
            "FoundationGateEvaluator.check_m7_hard_budget_denies_route",
            "Hard budget overages deny routes.",
            "Hard budget overage did not deny the route.",
            "critical",
        ),
        _criterion(
            "m7_cost_warnings_visible_in_route_decision",
            "M7 Cost Warnings Visible In Route Decision",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m7_cost_warnings_visible_in_route_decision",
            "Route decisions preserve soft-budget warning reason codes.",
            "Route decision did not preserve cost warning reason codes.",
            "critical",
        ),
        _criterion(
            "api_manifest_endpoint_present",
            "API Manifest Endpoint Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_api_manifest_endpoint_present",
            "/api/manifest exposes typed metadata for the current API boundary.",
            "API manifest endpoint is missing or invalid.",
        ),
        _criterion(
            "openapi_contract_valid",
            "OpenAPI Contract Valid",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_openapi_contract_valid",
            "OpenAPI generation succeeds, matches the active version, and route inventory is valid.",
            "OpenAPI contract verification failed.",
            "critical",
        ),
        _criterion(
            "api_operation_ids_unique",
            "API Operation IDs Unique",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_api_operation_ids_unique",
            "All API routes have unique stable operation IDs.",
            "API operation IDs are missing or duplicated.",
            "critical",
        ),
        _criterion(
            "forbidden_runtime_routes_absent",
            "Forbidden Runtime Routes Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_forbidden_runtime_routes_absent",
            "API boundary exposes no runtime model-call, provider-call, web-fetch, browser, scanner, or tool-execution routes.",
            "Forbidden runtime route was detected.",
            "critical",
        ),
        _criterion(
            "agents_md_guidance_present",
            "AGENTS Guidance Present",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_agents_md_guidance_present",
            "AGENTS.md and API boundary docs define workspace and API contract standards.",
            "AGENTS.md or API boundary documentation is missing.",
        ),
        _criterion(
            "runtime_agent_config_loading_absent",
            "Runtime Agent Config Loading Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_runtime_agent_config_loading_absent",
            "Runtime source does not load AGENTS.md, agent config files, or workspace config at request time.",
            "Runtime agent configuration loading was detected.",
            "critical",
        ),
        _criterion(
            "m8_model_runtime_files_present",
            "M8 Model Runtime Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_model_runtime_files_present",
            "M8 simulated model runtime contracts, validation, simulator, and adapter modules exist.",
            "Required M8 model runtime files are missing.",
        ),
        _criterion(
            "m8_runtime_kinds_stub_only",
            "M8 Runtime Kinds Stub Only",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_runtime_kinds_stub_only",
            "Model runtime adapter kinds are limited to simulated and stub variants.",
            "A non-stub model runtime kind was detected.",
            "critical",
        ),
        _criterion(
            "m8_model_runtime_no_real_calls",
            "M8 Model Runtime No Real Calls",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_model_runtime_no_real_calls",
            "Model runtime source has no provider SDK, network, tokenizer, billing, shell, or live runtime call path.",
            "A real model/runtime integration was detected in M8 source.",
            "critical",
        ),
        _criterion(
            "m8_simulation_endpoint_safe",
            "M8 Simulation Endpoint Safe",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_simulation_endpoint_safe",
            "/model-runtime/simulate exists and is explicitly simulated.",
            "The M8 simulation endpoint is missing or unsafe.",
            "critical",
        ),
        _criterion(
            "m8_runtime_responses_simulated_only",
            "M8 Runtime Responses Simulated Only",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m8_runtime_responses_simulated_only",
            "Model runtime responses are marked simulated and are not truth authority.",
            "A model runtime response was not clearly simulated.",
            "critical",
        ),
        _criterion(
            "m8_runtime_secret_prompt_blocked",
            "M8 Runtime Secret Prompt Blocked",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_runtime_secret_prompt_blocked",
            "Secret-like prompt summaries are rejected before simulation.",
            "Secret-like runtime prompt content was accepted.",
            "critical",
        ),
        _criterion(
            "m8_api_validation_secret_echo_absent",
            "M8 API Validation Secret Echo Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m8_api_validation_secret_echo_absent",
            "M8 API validation errors do not echo secret-like manifest or request payload values.",
            "M8 API validation errors echoed secret-like input.",
            "critical",
        ),
        _criterion(
            "m85_approval_authority_files_present",
            "M8.5 Approval Authority Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m85_approval_authority_files_present",
            "M8.5 approval request, grant, validation, authority, policy, and receipt modules exist.",
            "Required M8.5 approval authority files are missing.",
            "critical",
        ),
        _criterion(
            "m85_arbitrary_approval_refs_rejected",
            "M8.5 Arbitrary Approval Refs Rejected",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_arbitrary_approval_refs_rejected",
            "LocalApprovalAuthority rejects arbitrary approval_ref strings.",
            "An arbitrary approval_ref was accepted as authority.",
            "critical",
        ),
        _criterion(
            "m85_local_approval_grant_validates",
            "M8.5 Local Approval Grant Validates",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_local_approval_grant_validates",
            "A scoped LocalApprovalAuthority grant validates for its exact subject/action/resource.",
            "A valid local/dev approval grant did not validate.",
            "critical",
        ),
        _criterion(
            "m85_expired_revoked_approval_denies",
            "M8.5 Expired Revoked Approval Denies",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_expired_revoked_approval_denies",
            "Expired and revoked approval grants are denied.",
            "Expired or revoked approval was accepted.",
            "critical",
        ),
        _criterion(
            "m85_router_uses_valid_approval_grant",
            "M8.5 Router Uses Valid Approval Grant",
            FoundationGateCategory.model_router,
            "FoundationGateEvaluator.check_m85_router_uses_valid_approval_grant",
            "Model Router can use a valid local/dev approval grant for sensitive cloud route metadata decisions.",
            "Model Router did not honor a valid approval grant.",
            "critical",
        ),
        _criterion(
            "m85_runtime_factory_rejects_arbitrary_approval",
            "M8.5 Runtime Factory Rejects Arbitrary Approval",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_runtime_factory_rejects_arbitrary_approval",
            "Model runtime request factory rejects non-test approval refs without a validated approval decision.",
            "Model runtime factory accepted an arbitrary approval ref.",
            "critical",
        ),
        _criterion(
            "m85_tool_broker_rejects_arbitrary_approval",
            "M8.5 Tool Broker Rejects Arbitrary Approval",
            FoundationGateCategory.tool_broker,
            "FoundationGateEvaluator.check_m85_tool_broker_rejects_arbitrary_approval",
            "Tool Broker keeps high-risk actions approval-required for arbitrary approval refs.",
            "Tool Broker accepted an arbitrary approval ref.",
            "critical",
        ),
        _criterion(
            "m85_no_real_auth_oauth_network",
            "M8.5 No Real Auth OAuth Network",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_no_real_auth_oauth_network",
            "Approval authority source has no production auth, OAuth, network, provider SDK, or persistence imports.",
            "M8.5 added real auth, OAuth, network, or persistence code.",
            "critical",
        ),
        _criterion(
            "m85_approval_api_secret_echo_absent",
            "M8.5 Approval API Secret Echo Absent",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m85_approval_api_secret_echo_absent",
            "Approval API validation errors do not echo secret-like payload values.",
            "Approval API validation echoed secret-like input.",
            "critical",
        ),
        _criterion(
            "m9_loopback_runtime_files_present",
            "M9 Loopback Runtime Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m9_loopback_runtime_files_present",
            "M9 loopback endpoint, policy, transport, and local adapter files exist.",
            "Required M9 loopback runtime files are missing.",
            "critical",
        ),
        _criterion(
            "m9_non_loopback_endpoints_denied",
            "M9 Non Loopback Endpoints Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_non_loopback_endpoints_denied",
            "Remote hosts, URL credentials, and secret-like query parameters are denied.",
            "A non-loopback or credential-bearing endpoint was accepted.",
            "critical",
        ),
        _criterion(
            "m9_non_loopback_policy_override_denied",
            "M9 Non Loopback Policy Override Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_non_loopback_policy_override_denied",
            "Caller-supplied allowed_hosts and deny_non_loopback=false cannot authorize remote hosts.",
            "A caller policy override authorized a non-loopback endpoint.",
            "critical",
        ),
        _criterion(
            "m9_loopback_policy_model_rejects_hostile_inputs",
            "M9 Loopback Policy Model Rejects Hostile Inputs",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_loopback_policy_model_rejects_hostile_inputs",
            "LoopbackRuntimePolicy rejects deny_non_loopback=false and non-loopback allowed_hosts.",
            "Loopback runtime policy accepted a hostile weakening input.",
            "critical",
        ),
        _criterion(
            "m9_public_and_private_ip_endpoints_denied",
            "M9 Public And Private IP Endpoints Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_public_and_private_ip_endpoints_denied",
            "Private LAN and public IP endpoints are denied by loopback endpoint validation.",
            "A private LAN or public IP endpoint was accepted.",
            "critical",
        ),
        _criterion(
            "m9_approval_api_uses_public_authority_helper",
            "M9 Approval API Uses Public Authority Helper",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_approval_api_uses_public_authority_helper",
            "Approval API loads validation grants through a public LocalApprovalAuthority helper.",
            "Approval API mutates LocalApprovalAuthority private grant state directly.",
            "critical",
        ),
        _criterion(
            "m9_arbitrary_approval_refs_denied",
            "M9 Arbitrary Approval Refs Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_arbitrary_approval_refs_denied",
            "Arbitrary approval_ref strings cannot authorize local loopback execution.",
            "An arbitrary approval_ref authorized local loopback execution.",
            "critical",
        ),
        _criterion(
            "m9_fake_transport_only_in_gate",
            "M9 Fake Transport Only In Gate",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m9_fake_transport_only_in_gate",
            "Foundation Gate uses fake transport only and M9 runtime code has no requests/httpx/provider SDK/tokenizer/billing imports.",
            "M9 introduced a real provider, network, tokenizer, billing, or gate transport path.",
            "critical",
        ),
        _criterion(
            "m9_simulated_fallback_available",
            "M9 Simulated Fallback Available",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m9_simulated_fallback_available",
            "Blocked local loopback execution returns simulated fallback when policy requires it.",
            "M9 simulated fallback is unavailable.",
            "critical",
        ),
        _criterion(
            "m9_model_output_not_truth_authority",
            "M9 Model Output Not Truth Authority",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_m9_model_output_not_truth_authority",
            "Local loopback and fallback responses are marked non-authoritative.",
            "M9 model output was treated as truth authority.",
            "critical",
        ),
        _criterion(
            "m10_manual_smoke_files_present",
            "M10 Manual Smoke Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m10_manual_smoke_files_present",
            "Manual local loopback smoke policy, transport, script, and tests exist.",
            "Required M10 manual smoke files are missing.",
            "critical",
        ),
        _criterion(
            "m10_stdlib_network_isolated",
            "M10 Stdlib Network Isolated",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m10_stdlib_network_isolated",
            "Stdlib network import is isolated to the manual loopback smoke transport.",
            "M10 introduced broad runtime network or provider imports.",
            "critical",
        ),
        _criterion(
            "m10_gate_and_verify_do_not_call_smoke_script",
            "M10 Gate And Verify Do Not Call Smoke Script",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m10_gate_and_verify_do_not_call_smoke_script",
            "Foundation Gate and verify_all do not invoke the manual smoke script.",
            "Gate or verification invokes manual local loopback smoke execution.",
            "critical",
        ),
        _criterion(
            "m10_public_api_has_no_smoke_execute_endpoint",
            "M10 Public API Has No Smoke Execute Endpoint",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m10_public_api_has_no_smoke_execute_endpoint",
            "Public API exposes smoke validation only and no smoke execute endpoint.",
            "Public API exposes a real local loopback smoke execution route.",
            "critical",
        ),
        _criterion(
            "m10_fixed_prompt_and_loopback_policy_enforced",
            "M10 Fixed Prompt And Loopback Policy Enforced",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m10_fixed_prompt_and_loopback_policy_enforced",
            "Manual smoke rejects arbitrary prompts and non-loopback endpoints.",
            "Manual smoke accepted arbitrary prompt content or a non-loopback endpoint.",
            "critical",
        ),
        _criterion(
            "m10_smoke_approval_required",
            "M10 Smoke Approval Required",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m10_smoke_approval_required",
            "Manual smoke requires a scoped valid local approval decision.",
            "Manual smoke permitted missing or arbitrary approval refs.",
            "critical",
        ),
        _criterion(
            "m10_smoke_response_not_truth_authority",
            "M10 Smoke Response Not Truth Authority",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_m10_smoke_response_not_truth_authority",
            "Manual smoke responses are marked non-authoritative and omit prompt content.",
            "Manual smoke response was treated as truth authority or leaked prompt content.",
            "critical",
        ),
        _criterion(
            "m105_remote_worker_files_present",
            "M10.5 Remote Worker Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m105_remote_worker_files_present",
            "Remote worker foundation schemas, policies, registries, dry-run code, and tests exist.",
            "Required M10.5 remote worker foundation files are missing.",
            "critical",
        ),
        _criterion(
            "m105_remote_capabilities_default_safe",
            "M10.5 Remote Capabilities Default Safe",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_remote_capabilities_default_safe",
            "Remote worker risky capabilities default false and cannot approve actions or run critical work.",
            "Remote worker risky capabilities default unsafe or permit remote approval.",
            "critical",
        ),
        _criterion(
            "m105_unknown_node_and_transport_denied",
            "M10.5 Unknown Node And Transport Denied",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_unknown_node_and_transport_denied",
            "Unknown remote nodes and transports are denied.",
            "Unknown remote node or transport was accepted.",
            "critical",
        ),
        _criterion(
            "m105_planned_transports_disabled",
            "M10.5 Planned Transports Disabled",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_planned_transports_disabled",
            "Planned tailnet and LAN transports remain disabled and metadata-only.",
            "A planned remote transport was enabled.",
            "critical",
        ),
        _criterion(
            "m105_dry_run_dispatches_nothing",
            "M10.5 Dry Run Dispatches Nothing",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_dry_run_dispatches_nothing",
            "Remote worker dry-runs create inert results with no job transfer, tool call, network connection, or subagent launch.",
            "Remote worker dry-run performed a forbidden action.",
            "critical",
        ),
        _criterion(
            "m105_no_remote_network_or_background_execution",
            "M10.5 No Remote Network Or Background Execution",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_no_remote_network_or_background_execution",
            "Remote worker source contains no live network, process, listener, scheduler, or background runtime imports.",
            "Remote worker source contains live network or background execution code.",
            "critical",
        ),
        _criterion(
            "m105_no_remote_subagents_tools_or_approvals",
            "M10.5 No Remote Subagents Tools Or Approvals",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_no_remote_subagents_tools_or_approvals",
            "Remote workers cannot launch subagents, execute tools, or approve actions.",
            "Remote worker policy permits subagents, tool execution, or approval.",
            "critical",
        ),
        _criterion(
            "m105_remote_output_untrusted",
            "M10.5 Remote Output Untrusted",
            FoundationGateCategory.truth,
            "FoundationGateEvaluator.check_m105_remote_output_untrusted",
            "Remote dry-run output is marked untrusted and never treated as control authority.",
            "Remote worker output was treated as trusted authority.",
            "critical",
        ),
        _criterion(
            "m105_api_routes_are_dry_run_only",
            "M10.5 API Routes Are Dry Run Only",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m105_api_routes_are_dry_run_only",
            "Remote worker API exposes status, validation, and dry-run routes only.",
            "Remote worker API exposes a live execution route.",
            "critical",
        ),
        _criterion(
            "m105_docs_foundation_only",
            "M10.5 Docs Foundation Only",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_m105_docs_foundation_only",
            "Release docs state M10.5 is foundation-only with no live remote networking or execution.",
            "M10.5 docs are missing or imply live remote execution.",
            "critical",
        ),
        _criterion(
            "m105_remote_tailnet_enable_flag_rejected",
            "M10.5 Remote Tailnet Enable Flag Rejected",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_remote_tailnet_enable_flag_rejected",
            "Remote worker policy rejects remote_tailnet_enabled=true as unsupported in M10.5.",
            "Remote worker policy accepted remote_tailnet_enabled=true as supported.",
            "critical",
        ),
        _criterion(
            "m105_remote_personal_data_enable_flag_rejected",
            "M10.5 Remote Personal Data Enable Flag Rejected",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_remote_personal_data_enable_flag_rejected",
            "Remote worker policy rejects remote_personal_data_enabled=true as unsupported in M10.5.",
            "Remote worker policy accepted remote_personal_data_enabled=true as supported.",
            "critical",
        ),
        _criterion(
            "m105_remote_worker_api_extra_fields_forbidden",
            "M10.5 Remote Worker API Extra Fields Forbidden",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m105_remote_worker_api_extra_fields_forbidden",
            "Remote worker API wrapper models reject unexpected top-level fields without leaking secret-like values.",
            "Remote worker API wrapper models accepted extra fields or leaked secret-like input.",
            "critical",
        ),
        _criterion(
            "m143_private_mesh_taxonomy_open_source_first",
            "v0.14.3 Private Mesh Taxonomy Open Source First",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m143_private_mesh_taxonomy_open_source_first",
            "Private mesh taxonomy includes planned Headscale, generic WireGuard, and Tailscale metadata with open-source-first selection policy.",
            "Private mesh taxonomy is missing open-source-first planned provider metadata.",
            "critical",
        ),
        _criterion(
            "m143_planned_mesh_transports_disabled",
            "v0.14.3 Planned Mesh Transports Disabled",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m143_planned_mesh_transports_disabled",
            "Planned private mesh transports remain disabled, planned-only, no-network, no-credential, and no-dispatch.",
            "A planned private mesh transport was enabled or dispatch/network capable.",
            "critical",
        ),
        _criterion(
            "m143_no_live_mesh_integrations",
            "v0.14.3 No Live Mesh Integrations",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m143_no_live_mesh_integrations",
            "No Headscale, Tailscale, WireGuard, mesh command, private IP, auth key, node key, token, or live network integration exists.",
            "A live private mesh integration or private transport secret marker was detected.",
            "critical",
        ),
        _criterion(
            "m11_runtime_readiness_files_present",
            "M11 Runtime Readiness Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m11_runtime_readiness_files_present",
            "Runtime readiness contracts, matrix, smoke report validation, API tests, and docs are present.",
            "M11 runtime readiness package, tests, or docs are missing.",
            "critical",
        ),
        _criterion(
            "m11_runtime_capability_matrix_safe",
            "M11 Runtime Capability Matrix Safe",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_runtime_capability_matrix_safe",
            "Capability matrix marks live/cloud/remote/mobile/plugin surfaces as dry-run, planned-disabled, manual-only, simulated-only, or blocked.",
            "Capability matrix implies new runtime execution, cloud, secrets, or provider readiness.",
            "critical",
        ),
        _criterion(
            "m11_manual_smoke_report_validation_safe",
            "M11 Manual Smoke Report Validation Safe",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_manual_smoke_report_validation_safe",
            "Manual smoke report validation accepts safe summaries and rejects raw prompts, secrets, remote endpoints, execution claims, and authoritative model output.",
            "Manual smoke report validation accepted unsafe report content.",
            "critical",
        ),
        _criterion(
            "m11_no_production_readiness_claim",
            "M11 No Production Readiness Claim",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_no_production_readiness_claim",
            "Readiness report remains non-production and non-authoritative.",
            "Runtime readiness report claims production, real model, remote execution, mobile sensor, plugin, or truth authority readiness.",
            "critical",
        ),
        _criterion(
            "m11_runtime_api_status_validation_only",
            "M11 Runtime API Status Validation Only",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m11_runtime_api_status_validation_only",
            "Runtime API exposes only readiness, capability matrix, and smoke-report validation routes with no execute/run/connect/dispatch/enable route.",
            "Runtime API exposes a forbidden runtime execution or plugin enablement route.",
            "critical",
        ),
        _criterion(
            "m11_no_smoke_script_execution_in_gate",
            "M11 No Smoke Script Execution In Gate",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_no_smoke_script_execution_in_gate",
            "verify_all.py and run_foundation_gate.py do not execute the manual local loopback smoke script.",
            "Gate or verifier invokes local_loopback_smoke.py.",
            "critical",
        ),
        _criterion(
            "m11_no_runtime_expansion_imports",
            "M11 No Runtime Expansion Imports",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_no_runtime_expansion_imports",
            "Runtime readiness code has no provider SDK, network, tokenizer, billing, shell, or eval/exec capability.",
            "Runtime readiness code imports or calls forbidden runtime expansion APIs.",
            "critical",
        ),
        _criterion(
            "m11_no_remote_mesh_mobile_or_plugin_enablement",
            "M11 No Remote Mesh Mobile Or Plugin Enablement",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m11_no_remote_mesh_mobile_or_plugin_enablement",
            "M11 does not enable live remote mesh/tailnet, mobile sensors, Codex plugins, native builds, or computer-use automation.",
            "M11 source/docs imply live mesh, mobile sensor, plugin, native build, or computer-use enablement.",
            "critical",
        ),
        _criterion(
            "m12_control_center_files_present",
            "M12 Control Center Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m12_control_center_files_present",
            "Control Center contracts, API tests, no-execution tests, docs, and release docs are present.",
            "M12 Control Center files are missing.",
            "critical",
        ),
        _criterion(
            "m12_control_center_manifest_read_only",
            "M12 Control Center Manifest Read Only",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m12_control_center_manifest_read_only",
            "Control Center manifest surfaces are read-only, preview-only, validation-only, planned-disabled, blocked, or not implemented.",
            "Control Center manifest implies execution, plugin, mobile, remote, model, provider, or frontend capability.",
            "critical",
        ),
        _criterion(
            "m12_control_center_dashboard_secret_safe",
            "M12 Control Center Dashboard Secret Safe",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m12_control_center_dashboard_secret_safe",
            "Control Center dashboard is summary-only and contains no secret-like values or production readiness claims.",
            "Control Center dashboard leaks unsafe data or claims production/runtime readiness.",
            "critical",
        ),
        _criterion(
            "m12_control_center_action_preview_no_execution",
            "M12 Control Center Action Preview No Execution",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m12_control_center_action_preview_no_execution",
            "Control Center action previews never execute and deny execute, remote, mobile, plugin, credential, mutation, model, and provider claims.",
            "Control Center action preview allowed execution or unsafe capability claims.",
            "critical",
        ),
        _criterion(
            "m12_control_center_api_read_only",
            "M12 Control Center API Read Only",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m12_control_center_api_read_only",
            "Control Center API exposes only read-only and preview-only routes with no execute/run/connect/dispatch/enable route.",
            "Control Center API exposes an unsafe execution route or unsafe route metadata.",
            "critical",
        ),
        _criterion(
            "m12_no_frontend_dependencies",
            "M12 No Root Frontend Dependencies",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m12_no_frontend_dependencies",
            "No root frontend package, node_modules, Vite/Next/shadcn/Tailwind, iOS, or macOS build setup is added to the Python Agent Core.",
            "Root frontend or native build dependency/configuration was added.",
            "critical",
        ),
        _criterion(
            "m12_no_runtime_network_mobile_plugin_expansion",
            "M12 No Runtime Network Mobile Plugin Expansion",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m12_no_runtime_network_mobile_plugin_expansion",
            "Control Center source has no runtime execution, network, provider, tokenizer, billing, remote dispatch, mobile sensor, plugin enablement, shell, or browser automation capability.",
            "Control Center source contains forbidden runtime/network/mobile/plugin expansion capability.",
            "critical",
        ),
        _criterion(
            "m13_web_control_center_files_present",
            "M13 Web Control Center Files Present",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m13_web_control_center_files_present",
            "M13 React/Vite shell, typed API layer, mock fixtures, tests, docs, and safety policy files are present.",
            "M13 Web Control Center shell files are missing.",
            "critical",
        ),
        _criterion(
            "m13_web_shell_read_only_preview_only",
            "M13 Web Shell Read Only Preview Only",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_web_shell_read_only_preview_only",
            "Frontend dependencies and source remain limited to a local read-only/preview-only shell with no unsafe controls or integrations.",
            "M13 frontend source or dependencies imply execution, plugin, remote, mobile, native, browser, Chrome, or provider capability.",
            "critical",
        ),
        _criterion(
            "m13_action_preview_ui_posts_only_to_preview",
            "M13 Action Preview UI Posts Only To Preview",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_action_preview_ui_posts_only_to_preview",
            "The frontend declares exactly one POST target and it is /control-center/actions/preview.",
            "M13 frontend declares an unsafe or additional POST target.",
            "critical",
        ),
        _criterion(
            "m13_mock_data_safe_non_authoritative",
            "M13 Mock Data Safe Non Authoritative",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_mock_data_safe_non_authoritative",
            "Mock frontend fixtures are visibly mock, non-authoritative, and keep runtime, remote, mobile, plugin, and native capabilities disabled or blocked.",
            "M13 mock frontend data claims unsafe authority or leaks secret-like values.",
            "critical",
        ),
        _criterion(
            "m13_no_tracked_generated_or_native_artifacts",
            "M13 No Tracked Generated Or Native Artifacts",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_no_tracked_generated_or_native_artifacts",
            "Frontend build output, node_modules, coverage, env files, and native/mobile project artifacts remain ignored/untracked and native files are absent.",
            "M13 generated, env, or native/mobile artifacts are present in the release boundary.",
            "critical",
        ),
        _criterion(
            "m13_backend_api_contract_unchanged",
            "M13 Backend API Contract Unchanged",
            FoundationGateCategory.contracts,
            "FoundationGateEvaluator.check_m13_backend_api_contract_unchanged",
            "Backend API path count stays at 74 with the existing read-only/preview-only Control Center routes and no new execution route.",
            "M13 changed backend API route count or exposed unsafe Control Center routes.",
            "critical",
        ),
        _criterion(
            "m13_frontend_no_sensitive_browser_apis",
            "M13 Frontend No Sensitive Browser APIs",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_frontend_no_sensitive_browser_apis",
            "Frontend implementation uses no browser storage, credential, cookie, clipboard write, notification, push, camera, microphone, or location APIs.",
            "M13 frontend source uses sensitive browser storage, credentials, cookies, clipboard write, notification, push, camera, microphone, or location APIs.",
            "critical",
        ),
        _criterion(
            "m13_control_center_frontend_safety_verifier_passes",
            "M13 Control Center Frontend Safety Verifier Passes",
            FoundationGateCategory.security,
            "FoundationGateEvaluator.check_m13_control_center_frontend_safety_verifier_passes",
            "scripts/verify_control_center_frontend.py passes and is wired into the release safety boundary.",
            "Control Center frontend safety verifier failed or is missing.",
            "critical",
        ),
        _criterion(
            "documentation_integrity_current",
            "Documentation Integrity Current",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_documentation_integrity_current",
            "Documentation index, canonical map, active release docs, private mesh docs, mobile planning docs, and active version references are present without unsafe implementation claims.",
            "Active documentation is missing or claims planned/disabled capabilities are implemented.",
            "critical",
        ),
        _criterion(
            "codex_plugin_governance_docs_present",
            "Codex Plugin Governance Docs Present",
            FoundationGateCategory.documentation,
            "FoundationGateEvaluator.check_codex_plugin_governance_docs_present",
            "Codex plugin inventory, risk policy, canonical governance doc, and enablement backlog are present and keep high-risk plugins disabled/future-only.",
            "Codex plugin governance docs are missing or imply plugin enablement.",
            "critical",
        ),
    ]
