import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  BadgeAlert,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Bell,
  BellRing,
  Bluetooth,
  Bold,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  BriefcaseBusiness,
  Bug,
  Building2,
  Cable,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  ChartColumn,
  ChartLine,
  ChartNoAxesColumn,
  ChartPie,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleEllipsis,
  CircleHelp,
  CircleMinus,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleStop,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSun,
  CloudUpload,
  Code2,
  Command,
  Contact,
  Copy,
  Cpu,
  Database,
  DollarSign,
  Dot,
  Download,
  Edit3,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileCheck2,
  FileClock,
  FileCode2,
  FileImage,
  FileInput,
  FileJson,
  FileLock2,
  FileOutput,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Filter,
  Fingerprint,
  Flag,
  Folder,
  FolderCheck,
  FolderClock,
  FolderCog,
  FolderOpen,
  Forward,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitCompareArrows,
  GitMerge,
  GitPullRequestDraft,
  Globe2,
  Goal,
  GripVertical,
  Hand,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  History,
  Home,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Laptop,
  Layers3,
  Link,
  ListChecks,
  ListFilter,
  ListPlus,
  ListTodo,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailOpen,
  Map as MapIcon,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  Move,
  Network,
  Newspaper,
  OctagonAlert,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Phone,
  Pin,
  Play,
  Plug,
  Plus,
  Radio,
  ReceiptText,
  Redo2,
  RefreshCw,
  Reply,
  Rocket,
  RotateCcw,
  Rss,
  Save,
  Scale,
  ScanEye,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  Signal,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareCheck,
  SquarePen,
  Sun,
  Table2,
  Tag,
  Target,
  Terminal,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Undo2,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserRoundPlus,
  Users,
  Video,
  WandSparkles,
  Webhook,
  Wifi,
  WifiOff,
  Workflow,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const ICON_CATEGORIES = [
  "navigation",
  "actions",
  "planning",
  "business",
  "communication",
  "trust",
  "runtime",
  "files",
  "weather",
  "status",
  "general",
] as const;

export type IconCategory = (typeof ICON_CATEGORIES)[number];

export const ICON_COMPONENTS = {
  "activity": Activity,
  "alarm-clock": AlarmClock,
  "archive": Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "at-sign": AtSign,
  "badge-alert": BadgeAlert,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "ban": Ban,
  "bell": Bell,
  "bell-ring": BellRing,
  "bluetooth": Bluetooth,
  "bold": Bold,
  "book-open": BookOpen,
  "bookmark": Bookmark,
  "bot": Bot,
  "box": Box,
  "boxes": Boxes,
  "braces": Braces,
  "brain": Brain,
  "brain-circuit": BrainCircuit,
  "briefcase-business": BriefcaseBusiness,
  "bug": Bug,
  "building-2": Building2,
  "cable": Cable,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "camera": Camera,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-no-axes-column": ChartNoAxesColumn,
  "chart-pie": ChartPie,
  "check": Check,
  "check-check": CheckCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "circle-ellipsis": CircleEllipsis,
  "circle-help": CircleHelp,
  "circle-minus": CircleMinus,
  "circle-pause": CirclePause,
  "circle-play": CirclePlay,
  "circle-plus": CirclePlus,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  "clipboard": Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud": Cloud,
  "cloud-download": CloudDownload,
  "cloud-lightning": CloudLightning,
  "cloud-off": CloudOff,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  "cloud-upload": CloudUpload,
  "code-2": Code2,
  "command": Command,
  "contact": Contact,
  "copy": Copy,
  "cpu": Cpu,
  "database": Database,
  "dollar-sign": DollarSign,
  "dot": Dot,
  "download": Download,
  "edit-3": Edit3,
  "ellipsis": Ellipsis,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "file": File,
  "file-archive": FileArchive,
  "file-check-2": FileCheck2,
  "file-clock": FileClock,
  "file-code-2": FileCode2,
  "file-image": FileImage,
  "file-input": FileInput,
  "file-json": FileJson,
  "file-lock-2": FileLock2,
  "file-output": FileOutput,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "file-warning": FileWarning,
  "filter": Filter,
  "fingerprint": Fingerprint,
  "flag": Flag,
  "folder": Folder,
  "folder-check": FolderCheck,
  "folder-clock": FolderClock,
  "folder-cog": FolderCog,
  "folder-open": FolderOpen,
  "forward": Forward,
  "gauge": Gauge,
  "git-branch": GitBranch,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-compare-arrows": GitCompareArrows,
  "git-merge": GitMerge,
  "git-pull-request-draft": GitPullRequestDraft,
  "globe-2": Globe2,
  "goal": Goal,
  "grip-vertical": GripVertical,
  "hand": Hand,
  "handshake": Handshake,
  "hard-drive": HardDrive,
  "hash": Hash,
  "headphones": Headphones,
  "heart": Heart,
  "heart-pulse": HeartPulse,
  "history": History,
  "home": Home,
  "house": House,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "key-round": KeyRound,
  "laptop": Laptop,
  "layers-3": Layers3,
  "link": Link,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "list-plus": ListPlus,
  "list-todo": ListTodo,
  "loader-circle": LoaderCircle,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "mail-check": MailCheck,
  "mail-open": MailOpen,
  "map": MapIcon,
  "map-pin": MapPin,
  "maximize-2": Maximize2,
  "menu": Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "mic": Mic,
  "minimize-2": Minimize2,
  "minus": Minus,
  "monitor": Monitor,
  "moon": Moon,
  "more-horizontal": MoreHorizontal,
  "move": Move,
  "network": Network,
  "newspaper": Newspaper,
  "octagon-alert": OctagonAlert,
  "package": Package,
  "paperclip": Paperclip,
  "pause": Pause,
  "pencil": Pencil,
  "phone": Phone,
  "pin": Pin,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "radio": Radio,
  "receipt-text": ReceiptText,
  "redo-2": Redo2,
  "refresh-cw": RefreshCw,
  "reply": Reply,
  "rocket": Rocket,
  "rotate-ccw": RotateCcw,
  "rss": Rss,
  "save": Save,
  "scale": Scale,
  "scan-eye": ScanEye,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "shapes": Shapes,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-question": ShieldQuestion,
  "signal": Signal,
  "sliders-horizontal": SlidersHorizontal,
  "sparkles": Sparkles,
  "square": Square,
  "square-check": SquareCheck,
  "square-pen": SquarePen,
  "sun": Sun,
  "table-2": Table2,
  "tag": Tag,
  "target": Target,
  "terminal": Terminal,
  "trash-2": Trash2,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "undo-2": Undo2,
  "unlock": Unlock,
  "upload": Upload,
  "user": User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-round-plus": UserRoundPlus,
  "users": Users,
  "video": Video,
  "wand-sparkles": WandSparkles,
  "webhook": Webhook,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "workflow": Workflow,
  "wrench": Wrench,
  "x": X,
  "zap": Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_COMPONENTS;

export const ICON_NAMES = Object.freeze(
  Object.keys(ICON_COMPONENTS) as IconName[],
);

const ICON_CATEGORY_INDEX: Record<
  Exclude<IconCategory, "general">,
  readonly IconName[]
> = {
  navigation: ["home", "house", "rocket", "menu", "command", "search", "settings", "sliders-horizontal", "more-horizontal", "ellipsis", "chevron-down", "chevron-left", "chevron-right", "chevron-up", "arrow-down", "arrow-left", "arrow-right", "arrow-up", "external-link", "maximize-2", "minimize-2", "zoom-in", "zoom-out"],
  actions: ["check", "check-check", "plus", "minus", "x", "play", "pause", "save", "pencil", "edit-3", "copy", "archive", "trash-2", "undo-2", "redo-2", "rotate-ccw", "refresh-cw", "upload", "download", "send", "reply", "forward", "move", "grip-vertical", "filter", "list-filter", "list-plus", "circle-plus", "circle-minus", "circle-play", "circle-pause", "circle-stop", "circle-check", "circle-check-big", "circle-x", "square", "square-check", "square-pen", "log-in", "log-out", "pin"],
  planning: ["target", "goal", "flag", "calendar", "calendar-days", "calendar-check", "calendar-clock", "clock", "alarm-clock", "list-todo", "list-checks", "clipboard", "clipboard-list", "clipboard-check", "inbox", "map", "map-pin", "git-branch", "workflow"],
  business: ["activity", "user", "users", "user-check", "user-cog", "user-round-plus", "contact", "building-2", "briefcase-business", "handshake", "badge-dollar-sign", "dollar-sign", "trending-down", "trending-up", "chart-column", "chart-line", "chart-no-axes-column", "chart-pie", "heart", "heart-pulse", "scale", "tag", "at-sign", "phone"],
  communication: ["mail", "mail-check", "mail-open", "message-circle", "message-square", "messages-square", "bell", "bell-ring", "newspaper", "rss", "globe-2", "video", "mic", "headphones", "paperclip", "link", "wifi", "wifi-off", "radio"],
  trust: ["shield", "shield-alert", "shield-check", "shield-question", "lock", "unlock", "key-round", "fingerprint", "eye", "eye-off", "scan-eye", "badge-check", "badge-alert", "ban", "triangle-alert", "octagon-alert", "circle-alert", "info", "circle-help", "file-check-2", "file-warning", "receipt-text", "history", "database", "hard-drive"],
  runtime: ["bot", "box", "boxes", "brain", "brain-circuit", "sparkles", "wand-sparkles", "cpu", "server", "terminal", "code-2", "braces", "cable", "plug", "network", "wrench", "bug", "gauge", "git-commit-horizontal", "git-compare-arrows", "git-merge", "git-pull-request-draft", "package", "zap", "bluetooth", "monitor", "laptop", "cloud-upload", "cloud-download", "webhook"],
  files: ["file", "file-archive", "file-clock", "file-code-2", "file-image", "file-input", "file-json", "file-lock-2", "file-output", "file-search", "file-spreadsheet", "file-text", "folder", "folder-check", "folder-clock", "folder-cog", "folder-open", "book-open", "bookmark", "image", "camera", "table-2", "layers-3", "hash"],
  weather: ["sun", "moon", "cloud", "cloud-lightning", "cloud-off", "cloud-rain", "cloud-sun"],
  status: ["loader-circle", "circle", "circle-ellipsis", "circle-help", "circle-alert", "circle-check", "circle-check-big", "circle-x", "dot", "signal"],
};

export const ICON_ALIASES = {
  act: "list-checks",
  actions: "circle-check",
  approve: "circle-check",
  "arrow-forward": "arrow-right",
  block: "shield",
  briefing: "map",
  chat: "message-square",
  "check-circle": "circle-check",
  cube: "box",
  db: "database",
  det: "info",
  edit: "pencil",
  effect: "activity",
  ev: "file",
  evidence: "file-text",
  export: "upload",
  gear: "settings",
  globe: "globe-2",
  memory: "brain",
  model: "box",
  net: "globe-2",
  plan: "list-todo",
  plans: "list-todo",
  rec: "receipt-text",
  receipt: "receipt-text",
  req: "list-checks",
  review: "eye",
  route: "workflow",
  run: "play",
  safe: "shield-check",
  "shield-verified": "shield-check",
  sliders: "sliders-horizontal",
  source: "database",
  spark: "sparkles",
  src: "database",
  state: "circle-check",
  term: "terminal",
  today: "sun",
  trash: "trash-2",
  undo: "undo-2",
  user: "user",
  "user-circle": "user",
  warn: "triangle-alert",
  warning: "triangle-alert",
  write: "pencil",
  you: "user",
} as const satisfies Record<string, IconName>;

export type IconAlias = keyof typeof ICON_ALIASES;
export type IconReference = IconName | IconAlias;

export interface IconDefinition {
  readonly aliases: readonly IconAlias[];
  readonly categories: readonly IconCategory[];
  readonly component: LucideIcon;
  readonly directional: boolean;
  readonly keywords: readonly string[];
  readonly label: string;
  readonly name: IconName;
}

const DIRECTIONAL_ICONS = new Set<IconName>([
  "arrow-left",
  "arrow-right",
  "chevron-left",
  "chevron-right",
  "external-link",
  "forward",
  "log-in",
  "log-out",
  "redo-2",
  "reply",
  "undo-2",
]);

const aliasEntries = Object.entries(ICON_ALIASES) as Array<
  [IconAlias, IconName]
>;

function humanizeIconName(name: IconName): string {
  return name
    .split("-")
    .map((part) => {
      if (/^\d+$/.test(part)) {
        return part;
      }
      if (part === "rss") {
        return "RSS";
      }
      if (part === "cpu") {
        return "CPU";
      }
      if (part === "wifi") {
        return "Wi-Fi";
      }
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join(" ");
}

function categoriesForIcon(name: IconName): readonly IconCategory[] {
  const categories = Object.entries(ICON_CATEGORY_INDEX)
    .filter(([, names]) => names.includes(name))
    .map(([category]) => category as IconCategory);
  return categories.length > 0 ? categories : ["general"];
}

function aliasesForIcon(name: IconName): readonly IconAlias[] {
  return aliasEntries
    .filter(([, target]) => target === name)
    .map(([alias]) => alias);
}

export const ICON_DEFINITIONS: readonly IconDefinition[] = Object.freeze(
  ICON_NAMES.map((name) => {
    const aliases = aliasesForIcon(name);
    const label = humanizeIconName(name);
    return Object.freeze({
      aliases,
      categories: categoriesForIcon(name),
      component: ICON_COMPONENTS[name],
      directional: DIRECTIONAL_ICONS.has(name),
      keywords: Object.freeze([
        name,
        label.toLowerCase(),
        ...aliases,
      ]),
      label,
      name,
    });
  }),
);

const ICON_DEFINITION_MAP = new Map(
  ICON_DEFINITIONS.map((definition) => [definition.name, definition]),
);

export function isIconName(value: string): value is IconName {
  return Object.prototype.hasOwnProperty.call(ICON_COMPONENTS, value);
}

export function resolveIconName(reference: IconReference): IconName {
  if (isIconName(reference)) {
    return reference;
  }
  return ICON_ALIASES[reference];
}

export function getIconDefinition(
  reference: IconReference,
): IconDefinition {
  const name = resolveIconName(reference);
  const definition = ICON_DEFINITION_MAP.get(name);
  if (!definition) {
    throw new Error(`Unknown Control Center icon: ${reference}`);
  }
  return definition;
}

export function searchIconDefinitions({
  category = "all",
  query = "",
}: {
  category?: IconCategory | "all";
  query?: string;
} = {}): readonly IconDefinition[] {
  const normalizedQuery = query.trim().toLowerCase();
  return ICON_DEFINITIONS.filter((definition) => {
    const matchesCategory =
      category === "all" || definition.categories.includes(category);
    const matchesQuery =
      normalizedQuery === "" ||
      definition.keywords.some((keyword) =>
        keyword.includes(normalizedQuery),
      );
    return matchesCategory && matchesQuery;
  });
}
