import { useState } from "react";
import { Avatar, Badge, Button, Icon, MetaRow, Panel, SearchField, Tabs } from "./primitives";
import { WORKSPACE_PREFIX } from "./model";

type MessengerView = "founder" | "personal" | "dm" | "group" | "threads" | "search" | "room-info" | "invite" | "room-settings" | "sessions" | "intelligence" | "recovery" | "dark" | "calling" | "setup";

const messengerViews: Array<[MessengerView, string]> = [
  ["founder", "Founder HQ"], ["personal", "Personal Circle"], ["dm", "Direct message"], ["group", "Group room"], ["threads", "Threads"], ["search", "Search & attention"], ["room-info", "Room information"], ["invite", "Create & invite"], ["room-settings", "Room settings"], ["sessions", "Sessions & recovery"], ["intelligence", "UAA intelligence"], ["recovery", "Failure recovery"], ["dark", "Dark theme"], ["calling", "Calling"], ["setup", "Setup & sign in"],
];

export function MessengerSurface() {
  const initial = new URLSearchParams(window.location.search).get("view") as MessengerView | null;
  const [view, setViewState] = useState<MessengerView>(messengerViews.some(([id]) => id === initial) ? initial! : "founder");
  const setView = (next: MessengerView) => {
    setViewState(next);
    window.history.replaceState({}, "", `${WORKSPACE_PREFIX}/messenger?view=${next}`);
  };
  const dark = view === "dark";
  return (
    <div className={`ns-messenger-app ${dark ? "dark" : ""} ${view === "recovery" ? "recovery" : ""}`}>
      {view === "recovery" ? <div className="ns-offline-banner"><Icon name="circle-alert" size={16} /> Offline preview · No connector runtime <small>No successful sync has occurred</small><Button disabled title="No Matrix connector runtime is connected">Retry unavailable</Button></div> : null}
      <MessengerGlobalRail view={view} onView={setView} />
      <MessengerTopbar view={view} onView={setView} />
      {view === "setup" ? <MessengerSetup /> : view === "sessions" ? <SessionsView /> : view === "room-settings" ? <RoomSettingsView /> : view === "invite" ? <InviteView /> : view === "search" ? <SearchView /> : <ConversationWorkspace view={view} onView={setView} />}
      <footer className="ns-messenger-status"><span><Icon name="users" size={16} /> {view === "personal" ? "Personal Circle" : "Founder HQ"} · preview</span><span>{view === "recovery" ? "Local cache only" : "No Matrix account connected"}</span><span>No message sent</span><span><Icon name="lock" size={15} /> Local only</span><span><Icon name="ban" size={15} /> External actions blocked</span></footer>
    </div>
  );
}

function MessengerGlobalRail({ onView, view }: { onView: (view: MessengerView) => void; view: MessengerView }) {
  return <aside className="ns-messenger-global"><div className="ns-window-controls"><span /><span /><span /></div><strong className="ns-messenger-brand">UAA Messenger</strong><small>Matrix client</small><a href={`${WORKSPACE_PREFIX}/today`}><Icon name="arrow-left" size={13} /> Back to Control Center</a><button className={!(["personal"].includes(view)) ? "active" : ""} onClick={() => onView("founder")} type="button"><Icon name="house" size={19} /> Home</button><button onClick={() => onView("search")} type="button"><Icon name="mail" size={19} /> All Messages</button><hr /><small>Spaces</small><button className={view !== "personal" ? "active" : ""} onClick={() => onView("founder")} type="button"><Icon name="users" size={19} /> Founder HQ</button><button className={view === "personal" ? "active" : ""} onClick={() => onView("personal")} type="button"><Icon name="network" size={19} /> Personal Circle <Badge tone="blue">2</Badge></button><button onClick={() => onView("invite")} type="button"><Icon name="circle-plus" size={19} /> Add</button><button onClick={() => onView("search")} type="button"><Icon name="globe-2" size={19} /> Explore</button><button className="account" onClick={() => onView("sessions")} type="button"><Avatar initials="SR" tone="gray" /></button></aside>;
}

function MessengerTopbar({ onView, view }: { onView: (view: MessengerView) => void; view: MessengerView }) {
  return <header className="ns-messenger-topbar"><SearchField placeholder="Search messages, people, and rooms" /><button onClick={() => onView("search")} type="button"><Icon name="mail" size={17} /> Unread <Badge tone="blue">7</Badge></button><button onClick={() => onView("search")} type="button"><Icon name="at-sign" size={17} /> Mentions</button><span><Icon name={view === "recovery" ? "wifi-off" : "circle-check"} size={16} tone={view === "recovery" ? "warning" : "success"} /> {view === "recovery" ? "Local cache" : "Local ready"}</span><span><Icon name="shield" size={16} tone="warning" /> Ask before changes</span><span><Icon name="lock" size={15} /> Private</span><a href={`${WORKSPACE_PREFIX}/decisions`}>Review 3 decisions</a></header>;
}

function ConversationWorkspace({ onView, view }: { onView: (view: MessengerView) => void; view: MessengerView }) {
  const personal = view === "personal";
  const dm = view === "dm" || view === "calling";
  const group = view === "group";
  const roomName = personal ? "Family Plans" : dm ? "Morgan Lee" : group ? "Founder Ops" : view === "intelligence" ? "customer-alpha" : "UAA Development";
  return <>
    <RoomRail personal={personal} onView={onView} view={view} />
    <section className="ns-conversation">
      <header><div>{group ? <Icon name="hash" size={18} /> : dm ? <Avatar initials="ML" tone="orange" /> : null}<span><h1>{roomName}</h1><small>{personal ? "Schedules, errands, and shared plans" : dm ? "Direct message · encryption target" : "Engineering, product, and design · Preview data"}</small></span></div><nav><button onClick={() => onView("calling")} type="button"><Icon name="phone" size={18} /></button><button onClick={() => onView("calling")} type="button"><Icon name="video" size={18} /></button><button onClick={() => onView("search")} type="button"><Icon name="search" size={18} /></button><button onClick={() => onView("threads")} type="button"><Icon name="message-square" size={18} /></button><button onClick={() => onView("room-info")} type="button"><Icon name="info" size={18} /></button><ViewMenu onView={onView} /></nav></header>
      {view === "calling" ? <CallingPanel /> : <MessageTimeline personal={personal} recovery={view === "recovery"} />}
      <div className="ns-message-composer"><span>Preview only · messaging backend not connected</span><Icon name="paperclip" size={18} /><Icon name="circle-plus" size={18} /><strong>B</strong><Icon name="list-checks" size={18} /><Icon name="mic" size={18} /><button aria-label="Send message unavailable" disabled title="No Matrix send contract is connected" type="button"><Icon name="send" size={18} /></button></div>
    </section>
    <MessengerInspector onView={onView} view={view} />
  </>;
}

function RoomRail({ onView, personal, view }: { onView: (view: MessengerView) => void; personal: boolean; view: MessengerView }) {
  const rooms = personal ? ["family-plans", "weekend-trip", "home-projects", "photos", "book-club"] : ["uaa-development", "founder-ops", "customer-alpha", "product-design", "announcements"];
  return <aside className="ns-room-rail"><header><strong>{personal ? "Personal Circle" : "Founder HQ"}</strong><Badge tone="neutral">Preview data</Badge></header><SearchField placeholder="Find people and rooms" /><small>Rooms</small>{rooms.map((room, index) => <button className={(view === "group" && room === "founder-ops") || (view === "intelligence" && room === "customer-alpha") || (view === "room-info" && room === "product-design") || (view === "founder" && index === 0) || (view === "personal" && index === 0) ? "active" : ""} key={room} onClick={() => onView(room === "founder-ops" ? "group" : room === "product-design" ? "room-info" : room === "customer-alpha" ? "intelligence" : personal ? "personal" : "founder")} type="button"><Icon name="hash" size={14} /> {room}{index === 1 ? <Badge tone="blue">2</Badge> : null}</button>)}<small>Direct messages</small><button className={view === "dm" || view === "calling" ? "active" : ""} onClick={() => onView("dm")} type="button"><Avatar initials="ML" tone="orange" /> Morgan Lee <Badge tone="blue">1</Badge></button><button disabled title="Preview direct message" type="button"><Avatar initials="JD" tone="teal" /> Jordan Diaz</button><small>Low priority</small><button disabled title="Preview room" type="button"><Icon name="hash" size={14} /> archive-2024 <Icon name="bell" size={14} /></button><button disabled title="Preview room" type="button"><Icon name="hash" size={14} /> random <Icon name="bell" size={14} /></button></aside>;
}

const messageRows = [
  ["AC", "Avery Chen", "9:02 AM", "Good morning team! Quick update: CRM v3 is shaping up well. The data model is locked and we’re moving into integration tests this week."],
  ["RM", "Riley Morgan", "9:15 AM", "Also, the Messenger north-star render is almost ready for review. Will share a preview in a bit."],
  ["AC", "Avery Chen", "9:21 AM", "Here’s the latest Messenger render. Feedback welcome!"],
  ["ML", "Morgan Lee", "9:32 AM", "Looks great! The left panel feels lighter and the hierarchy is much clearer."],
  ["JD", "Jordan Diaz", "9:41 AM", "Agreed. Let’s plan to review with the design council tomorrow."],
  ["KM", "Kendall Moore", "9:48 AM", "Reminder: Please add open questions for the standup. Thanks!"],
];

function MessageTimeline({ personal, recovery }: { personal: boolean; recovery: boolean }) {
  const rows = personal ? messageRows.map((row, index) => index === 0 ? ["AF", "Ashley Foster", "9:01 AM", "How about a family dinner this weekend? I’m thinking Saturday evening so everyone has time to get there."] : row) : messageRows;
  return <div className="ns-message-timeline"><div className="ns-day-divider">Today</div>{rows.map((row, index) => <article className={`${index === rows.length - 1 ? "selected" : ""} ${recovery && index === 1 ? "failed" : ""}`} key={`${row[1]}-${row[2]}`}><Avatar initials={row[0]} tone={["purple", "teal", "purple", "orange", "teal", "green"][index] as "purple"} /><div><header><strong>{row[1]}</strong><time>{row[2]}</time></header><p>{row[3]}</p>{recovery && index === 1 ? <span className="ns-failed-send"><Icon name="triangle-alert" size={14} /> Not sent · Retry · Edit · Discard</span> : <div className="ns-reactions"><button disabled title="Reaction writes are not connected" type="button">👍 {index + 1}</button><button disabled title="Reaction writes are not connected" type="button">☺</button></div>}</div></article>)}</div>;
}

function MessengerInspector({ onView, view }: { onView: (view: MessengerView) => void; view: MessengerView }) {
  if (view === "threads") return <aside className="ns-messenger-inspector"><header><h2>Threads · 4</h2><button onClick={() => onView("founder")} type="button">Return to room</button></header>{["Right rail density", "Messaging composer", "Attachment preview", "Standup cadence"].map((item, i) => <button className={i === 0 ? "active" : ""} key={item} type="button"><Avatar initials={["ML", "AC", "RM", "JD"][i]} tone="purple" /><span><strong>{item}</strong><small>{5 - i} replies · 9:{32 + i * 3} AM</small></span></button>)}<Panel title="Right rail density"><p>The right rail feels a bit wide on 1440px. Thoughts on tightening it?</p><p>Avery: I think 320px is the sweet spot.</p><p>Riley: Keep context without crowding.</p></Panel></aside>;
  if (view === "room-info") return <aside className="ns-messenger-inspector"><header><h2>Room information</h2><Icon name="x" size={16} /></header><Tabs active="Overview" items={["Overview", "People", "Files", "Links", "Pins"]} /><div className="ns-room-profile"><Avatar initials="PD" tone="purple" /><h3>Product Design</h3><p>Private · 18 members</p></div><Panel title="About"><p>Design system, components, and product experiences.</p><MetaRow icon="users" label="Space" value="Founder HQ" /><MetaRow icon="lock" label="Access" value="Private" /><MetaRow icon="shield-check" label="Encryption" value="End-to-end target" /></Panel><div className="ns-grid-actions"><Button disabled title="Preview roster">People 18</Button><Button disabled title="Preview files">Files 12</Button><Button disabled title="Preview links">Links 9</Button><Button onClick={() => onView("threads")}>Threads 6</Button></div><Button onClick={() => onView("room-settings")} icon="settings">Open room settings</Button></aside>;
  if (view === "intelligence") return <aside className="ns-messenger-inspector intelligence"><header><h2><Icon name="sparkles" size={17} /> UAA Intelligence</h2><Icon name="x" size={16} /></header><div className="ns-intelligence-grid"><Panel title="Unread summary"><strong>4 messages</strong><small>Source: 4 · High</small></Panel><Panel title="Open questions"><strong>2</strong><small>Source: 2 · High</small></Panel><Panel title="Decisions"><strong>1</strong><small>Source: 1 · High</small></Panel><Panel title="Commitments"><strong>3</strong><small>Source: 3 · High</small></Panel></div><Panel title="Proposed actions"><p>Propose calendar event</p><p>Draft follow-up</p><p>Add shared task</p></Panel><Panel title="Propose calendar event"><MetaRow icon="mail" label="Source messages" value="3" /><MetaRow icon="users" label="Participants" value="3 safe refs" /><MetaRow icon="clock" label="Time candidate" value="Tue, 2:00 PM" /><MetaRow icon="shield" label="Authority" value="Approval required" tone="orange" /><Button disabled title="No calendar proposal envelope is connected" tone="primary">Review proposal unavailable</Button></Panel></aside>;
  if (view === "recovery") return <aside className="ns-messenger-inspector"><header><h2><Icon name="circle-alert" size={17} /> Recovery</h2></header><Panel title="Connection status"><MetaRow icon="wifi-off" label="Connection" value="Offline" tone="red" /><MetaRow icon="server" label="Homeserver" value="Not connected" tone="red" /><MetaRow icon="database" label="Local cache" value="Preview" tone="orange" /><MetaRow icon="lock" label="Encryption keys" value="Unavailable" tone="red" /></Panel><Panel title="Safe actions">{["Check connection", "Retry sync", "Review failed sends", "Open session verification", "Export diagnostics (redacted)"].map((item, i) => <button disabled key={item} title="No connector recovery runtime is connected" type="button"><span>{i + 1}</span>{item}<Icon name="chevron-right" size={14} /></button>)}</Panel></aside>;
  return <aside className="ns-messenger-inspector"><header><Tabs active="UAA" items={["Room", "UAA"]} /></header><Panel title="Unread summary"><strong>7 unread messages</strong><p>Most recent from Kendall Moore at 9:48 AM</p></Panel><Panel title="Open questions"><p>1. When will CRM v3 integration tests be complete?</p><p>2. Which metrics should we track?</p></Panel><Panel title="Decision"><p>Proceed with CRM v3 integration tests this week.</p></Panel><Panel title="Commitments"><p>☑ Share Messenger render v1.2</p><p>☑ Prepare design council review</p></Panel><Panel title="Suggested actions"><p>Create standup agenda · High</p><p>Draft release notes · High</p><p>Confirm design council time · Medium</p></Panel><label className="ns-ask-uaa"><input placeholder="Ask UAA..." /></label></aside>;
}

function ViewMenu({ onView }: { onView: (view: MessengerView) => void }) { const [open, setOpen] = useState(false); return <div className="ns-view-menu"><button aria-label="Messenger reference states" onClick={() => setOpen((v) => !v)} type="button"><Icon name="ellipsis" size={18} /></button>{open ? <div>{messengerViews.map(([id, label]) => <button key={id} onClick={() => { onView(id); setOpen(false); }} type="button">{label}</button>)}</div> : null}</div>; }

function CallingPanel() { return <div className="ns-calling-panel"><Panel title="Start a call"><div className="ns-segmented"><button className="active" disabled title="Call configuration is preview-only" type="button">Voice</button><button disabled title="Call configuration is preview-only" type="button">Video</button></div><strong>Participants</strong><div className="ns-call-participant"><Avatar initials="ML" tone="orange" /> Morgan Lee</div><strong>Availability</strong><MetaRow icon="radio" label="Matrix call" value="Planned" /><MetaRow icon="video" label="FaceTime · external handoff" value="Available only as external handoff" /><MetaRow icon="globe-2" label="Other providers" value="Not connected" /><strong>Device & settings</strong><MetaRow icon="mic" label="Microphone" value="Permission not requested" /><MetaRow icon="camera" label="Camera" value="Permission not requested" /><MetaRow icon="radio" label="Recording" value="Off · cannot be enabled" /><div className="ns-info-callout"><Icon name="shield" size={17} /><span>External action · review required · no active lease.</span></div><div className="ns-inline-actions"><Button disabled title="No call runtime is connected">Cancel</Button><Button disabled title="No call runtime is connected">Test devices · local preview</Button><Button disabled title="No external call-launch contract is connected" tone="primary">Review call launch</Button></div></Panel></div>; }

function InviteView() { return <section className="ns-messenger-special"><div><h1>New conversation</h1><Tabs active="Direct message" items={["Direct message", "Room"]} /><p>Invite people to a private conversation. Recipients may be on another homeserver.</p><SearchField placeholder="Search people by name or safe Matrix identifier" />{[["AC", "Avery Chen"], ["RM", "Riley Morgan"], ["ML", "Morgan Lee"]].map(([initials, name]) => <div className="ns-directory-row" key={name}><Avatar initials={initials} tone="purple" /><strong>{name}</strong><span>Online</span><Button disabled title="Directory selection is preview-only">Add</Button></div>)}<strong>Selected recipients (2)</strong><div className="ns-tag-list"><Badge tone="neutral">Avery Chen ×</Badge><Badge tone="neutral">Morgan Lee ×</Badge></div><Panel title="Room option preview"><label>Room name<input placeholder="e.g. Design Review" /></label><label>Topic<input placeholder="e.g. Share updates and feedback" /></label><label>Space<select><option>Choose a space</option></select></label></Panel></div><aside><Panel title="Review invitation"><MetaRow icon="users" label="Destination" value="Founder HQ" /><MetaRow icon="lock" label="Privacy" value="Direct / private" /><MetaRow icon="shield-check" label="Encryption" value="On target" /><MetaRow icon="sparkles" label="AI access" value="Off" /><MetaRow icon="send" label="Send autonomously" value="Never" /><div className="ns-info-callout"><Icon name="info" size={16} /><span>Invitations are external actions. Review exact recipients before sending.</span></div><Button disabled title="No Matrix invitation contract is connected" tone="primary">Review invitation unavailable</Button></Panel></aside></section>; }

function SearchView() { return <section className="ns-messenger-special ns-search-view"><div><h1>Search</h1><Tabs active="Messages" items={["Messages", "People", "Rooms", "Files"]} /><div className="ns-tag-list"><Badge tone="neutral">All results</Badge><Badge tone="neutral">Unread 7</Badge><Badge tone="neutral">Mentions 2</Badge><Badge tone="neutral">Invites 1</Badge></div>{["Re: Q2 planning – calendar proposal", "Draft: leadership sync – calendar proposal", "Calendar proposal – feedback summary", "Calendar proposal v2.docx", "Exec review – calendar proposal"].map((item, index) => <div className="ns-search-result" key={item}><input checked={index === 0} readOnly type="checkbox" /><Avatar initials={["RM", "AC", "JD", "ML", "KM"][index]} tone="teal" /><span><strong>{item}</strong><small>Founder HQ / Product Design · local index preview</small></span><Button disabled title="No backend message context is connected">Open in context</Button></div>)}</div><aside><Panel title="Result"><h2>Re: Q2 planning – calendar proposal</h2><p>Riley Morgan · Founder HQ / Product Design</p><Button disabled title="No backend message context is connected">Open in context</Button></Panel><Panel title="Related references"><MetaRow icon="users" label="CRM" value="Deal: North Star Integration" /><MetaRow icon="calendar" label="Calendar" value="Q2 Planning Review" /><MetaRow icon="table-2" label="Work Board" value="Q2 Planning" /></Panel></aside></section>; }

function RoomSettingsView() { return <section className="ns-messenger-special ns-room-settings-view"><aside><h1>Room settings<br />Founder Ops</h1>{["General", "Security & Privacy", "Permissions", "Notifications", "History", "UAA access", "Advanced"].map((item, i) => <button className={i === 0 ? "active" : ""} disabled title="Settings sections are preview-only" key={item} type="button">{item}</button>)}</aside><div><h1>General</h1><p>Basic information and visibility.</p><label>Room name<input defaultValue="Founder Ops" /></label><label>Topic<textarea defaultValue="Operations and execution for Founder HQ initiatives." /></label><label>Space<select><option>Founder HQ</option></select></label><label>Room alias · safe reference only<input defaultValue="founder-ops" /></label><Button disabled tone="primary">Review changes</Button></div><aside><Panel title="Change inspector"><Badge tone="neutral">Unsaved changes · 1</Badge><p>1 field will be updated.</p><MetaRow icon="edit-3" label="Room alias" value="founder-ops" /><MetaRow icon="shield" label="Authority" value="Approval required" tone="orange" /><Button disabled title="No room-settings mutation contract is connected" tone="primary">Review unavailable</Button></Panel><Panel title="Room status"><MetaRow icon="lock" label="Private room" value="Private" tone="green" /><MetaRow icon="shield-check" label="Encryption target" value="Encrypted" tone="green" /></Panel></aside></section>; }

function SessionsView() { return <section className="ns-messenger-special ns-sessions-view"><div><h1>Account security</h1><p>Manage sessions, device verification, and recovery options.</p><Tabs active="Sessions" items={["Profile", "Notifications", "Appearance", "Security & Privacy", "Sessions", "Voice & Video", "Help"]} /><Panel title="Security recommendations"><MetaRow icon="shield-check" label="Set up secure backup" value="Review setup" /><MetaRow icon="triangle-alert" label="Verify this session" value="Review verification setup" tone="orange" /></Panel><Panel title="Current session"><MetaRow icon="laptop" label="This Mac · Preview" value="Not registered" tone="red" /></Panel><Panel title="Other sessions">{[["Desktop · Mac", "Verified target"], ["Mobile · iPhone", "Unverified target"], ["Browser · Chrome", "Inactive target"]].map(([label, state]) => <MetaRow icon="monitor" key={label} label={label} value={state} tone={state === "Verified target" ? "green" : state === "Unverified target" ? "orange" : undefined} />)}</Panel></div><aside><Panel title="Recovery posture"><MetaRow icon="clock" label="Cross-signing" value="Planned" /><MetaRow icon="triangle-alert" label="Secure backup" value="Not configured" tone="orange" /><MetaRow icon="circle-x" label="Recovery key" value="Not present" tone="red" /><MetaRow icon="circle-help" label="Key storage" value="Backend undecided" /></Panel><Panel title="Recovery actions"><Button disabled title="No secure-backup setup contract is connected">Review secure-backup setup</Button><Button disabled>Verify with another device</Button><Button tone="danger" disabled>Reset identity · blocked</Button></Panel></aside></section>; }

function MessengerSetup() { return <section className="ns-messenger-special ns-messenger-setup"><aside className="ns-setup-steps">{["Server", "Account", "Security", "Review"].map((item, i) => <div className={i === 0 ? "active" : ""} key={item}><span>{i + 1}</span><strong>{item}</strong><small>{["Choose a homeserver", "Sign in or create", "Protect your data", "Confirm connection"][i]}</small></div>)}</aside><div><h1>Connect Messenger</h1><p>Use an existing Matrix account or choose a homeserver.</p><Panel title="1 · Homeserver"><p>Choose where your account lives.</p><div className="ns-grid-actions"><Button disabled title="No Matrix account connection contract is connected" tone="primary">Recommended · existing Matrix account</Button><Button disabled title="No Matrix account connection contract is connected">Custom homeserver</Button><Button disabled title="No Matrix account connection contract is connected">Self-host later</Button></div><label>Server<input defaultValue="matrix.example" /></label><Button disabled title="No network compatibility-check contract is connected">Check compatibility</Button><small>Status: Not checked</small></Panel><Panel title="Sign-in method"><div className="ns-grid-actions"><Button disabled icon="lock" title="No credential contract is connected">Password</Button><Button disabled icon="shield-check" title="No SSO contract is connected">Single sign-on</Button><Button disabled icon="key-round">Token import · blocked</Button></div></Panel><div className="ns-inline-actions"><Button disabled title="No setup draft has been started">Cancel</Button><Button disabled title="No Matrix connection contract is connected" tone="primary">Review connection</Button></div></div><aside><Panel title="Review"><MetaRow icon="server" label="Server" value="matrix.example" /><MetaRow icon="user" label="Account" value="Not provided" /><MetaRow icon="lock" label="Credential storage" value="Platform secure store · planned" /><MetaRow icon="shield" label="Crypto store" value="Local encrypted store" /><MetaRow icon="cloud" label="Network authority" value="Approval required" tone="orange" /><MetaRow icon="globe-2" label="Data residency" value="Server-defined" /></Panel></aside></section>; }
