from __future__ import annotations

from typing import Any


_CLAWHUB_SOURCE_REF = "source-ref:skill-marketplace:clawhub"
_HERMES_SOURCE_REF = "source-ref:skill-marketplace:hermes"


def _clawhub(
    *,
    rank: int,
    slug: str,
    name: str,
    summary: str,
    category: str,
    version: str,
    updated_at: str,
    stars: int,
    downloads: int,
    installs: int,
    comments: int,
) -> dict[str, Any]:
    return {
        "skill_ref": f"skill-candidate-ref:clawhub:{slug}",
        "source_ref": _CLAWHUB_SOURCE_REF,
        "source_record_ref": f"source-record-ref:clawhub:{slug}",
        "source_kind": "clawhub",
        "source_label": "ClawHub",
        "slug": slug,
        "display_name": name,
        "safe_summary": summary,
        "category": category,
        "version": version,
        "license_label": "Not provided",
        "source_updated_at": updated_at,
        "source_rank": rank,
        "rank_label": f"#{rank} this week",
        "star_count": stars,
        "download_count": downloads,
        "install_count": installs,
        "comment_count": comments,
    }


def _hermes(
    *,
    slug: str,
    name: str,
    summary: str,
    category: str,
    version: str,
    license_label: str,
    updated_at: str,
) -> dict[str, Any]:
    return {
        "skill_ref": f"skill-candidate-ref:hermes:{slug}",
        "source_ref": _HERMES_SOURCE_REF,
        "source_record_ref": f"source-record-ref:hermes:{slug}",
        "source_kind": "hermes",
        "source_label": "Hermes",
        "slug": slug,
        "display_name": name,
        "safe_summary": summary,
        "category": category,
        "version": version,
        "license_label": license_label,
        "source_updated_at": updated_at,
        "source_rank": None,
        "rank_label": "Not provided by source",
        "star_count": None,
        "download_count": None,
        "install_count": None,
        "comment_count": None,
        "average_rating": None,
        "rating_count": None,
    }


RUNTIME_SKILL_MARKETPLACE_CATALOG_SNAPSHOT: dict[str, Any] = {
    "snapshot_ref": "skill-marketplace-catalog-snapshot-ref:2026-07-13",
    "captured_at": "2026-07-13T23:00:00Z",
    "sources": [
        {
            "source_ref": _CLAWHUB_SOURCE_REF,
            "source_kind": "clawhub",
            "display_label": "ClawHub",
            "captured_at": "2026-07-13T23:00:00Z",
            "source_version_ref": "source-version-ref:clawhub:2026-07-13",
            "record_count": 12,
            "rank_signal": "weekly_trending",
            "score_signal": "stars",
        },
        {
            "source_ref": _HERMES_SOURCE_REF,
            "source_kind": "hermes",
            "display_label": "Hermes",
            "captured_at": "2026-07-13T23:00:00Z",
            "source_version_ref": (
                "source-version-ref:hermes:"
                "2ccfdb2db4eedf385f6c5b3fe722e183cee1b6de"
            ),
            "record_count": 19,
            "rank_signal": "not_provided",
            "score_signal": "not_provided",
        },
    ],
    "entries": [
        _clawhub(
            rank=1,
            slug="sonoscli",
            name="Sonoscli",
            summary="Control Sonos speakers for discovery, status, playback, volume, and grouping.",
            category="Uncategorized",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=56,
            downloads=85988,
            installs=2811,
            comments=1,
        ),
        _clawhub(
            rank=2,
            slug="gog",
            name="Gog",
            summary="Google Workspace CLI for Gmail, Calendar, Drive, Contacts, Sheets, and Docs.",
            category="Gmail",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=940,
            downloads=188728,
            installs=5459,
            comments=36,
        ),
        _clawhub(
            rank=3,
            slug="github",
            name="GitHub",
            summary="Interact with GitHub through the gh CLI for issues, pull requests, CI runs, and API queries.",
            category="GitHub",
            version="1.0.0",
            updated_at="2026-06-12T12:48:37.834Z",
            stars=651,
            downloads=192948,
            installs=7621,
            comments=7,
        ),
        _clawhub(
            rank=4,
            slug="weather",
            name="Weather",
            summary="Get current weather and forecasts without an API key.",
            category="Current Weather",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=422,
            downloads=163843,
            installs=6489,
            comments=6,
        ),
        _clawhub(
            rank=5,
            slug="openai-whisper",
            name="OpenAI Whisper",
            summary="Local speech-to-text with the Whisper CLI and no API key.",
            category="Speech-to-Text",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=332,
            downloads=85973,
            installs=2966,
            comments=2,
        ),
        _clawhub(
            rank=6,
            slug="skill-creator",
            name="Skill Creator",
            summary="Guide for creating or updating modular skills with focused workflows and supporting resources.",
            category="Uncategorized",
            version="0.1.0",
            updated_at="2026-05-17T03:07:05.295Z",
            stars=327,
            downloads=94686,
            installs=3425,
            comments=3,
        ),
        _clawhub(
            rank=7,
            slug="notion",
            name="Notion",
            summary="Use the Notion API to manage pages, databases, and blocks.",
            category="Notion",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=266,
            downloads=95085,
            installs=3228,
            comments=3,
        ),
        _clawhub(
            rank=8,
            slug="obsidian",
            name="Obsidian",
            summary="Work with Obsidian vaults and plain Markdown notes through the Obsidian CLI.",
            category="Uncategorized",
            version="1.0.0",
            updated_at="2026-05-18T20:48:40.034Z",
            stars=443,
            downloads=104928,
            installs=4110,
            comments=9,
        ),
        _clawhub(
            rank=9,
            slug="gemini",
            name="Gemini",
            summary="Use the Gemini CLI for one-shot questions, summaries, and generation.",
            category="Uncategorized",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=56,
            downloads=35365,
            installs=1477,
            comments=5,
        ),
        _clawhub(
            rank=10,
            slug="mcporter",
            name="Mcporter",
            summary="Inspect, configure, authenticate, and call MCP servers and tools through the mcporter CLI.",
            category="Uncategorized",
            version="1.0.0",
            updated_at="2026-05-18T20:48:39.429Z",
            stars=196,
            downloads=68135,
            installs=2173,
            comments=1,
        ),
        _clawhub(
            rank=11,
            slug="nano-banana-pro",
            name="Nano Banana Pro",
            summary="Generate or edit images through Gemini image tooling with text and image inputs.",
            category="Image Generation",
            version="1.0.1",
            updated_at="2026-05-18T20:48:27.565Z",
            stars=413,
            downloads=104979,
            installs=3103,
            comments=1,
        ),
        _clawhub(
            rank=12,
            slug="model-usage",
            name="Model Usage",
            summary="Summarize per-model usage and cost from local CodexBar cost data.",
            category="Json",
            version="1.0.0",
            updated_at="2026-05-11T07:48:49.679Z",
            stars=113,
            downloads=38589,
            installs=1590,
            comments=1,
        ),
        _hermes(
            slug="arxiv",
            name="arXiv",
            summary="Search arXiv papers by keyword, author, category, or identifier.",
            category="Research",
            version="1.0.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="blogwatcher",
            name="Blogwatcher",
            summary="Monitor blogs and RSS or Atom feeds through the blogwatcher CLI.",
            category="Research",
            version="2.0.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="llm-wiki",
            name="LLM Wiki",
            summary="Build and query an interlinked Markdown knowledge base for language-model topics.",
            category="Research",
            version="2.1.0",
            license_label="MIT",
            updated_at="2026-06-10T22:10:11Z",
        ),
        _hermes(
            slug="polymarket",
            name="Polymarket",
            summary="Query Polymarket markets, prices, order books, and history.",
            category="Research",
            version="1.0.0",
            license_label="Not provided",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="research-paper-writing",
            name="Research Paper Writing Pipeline",
            summary="Write machine-learning papers for major conferences from experiment design through submission.",
            category="Research",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-06-28T19:47:50Z",
        ),
        _hermes(
            slug="airtable",
            name="Airtable",
            summary="Use the Airtable REST API for record operations, filters, and upserts.",
            category="Productivity",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-06-10T22:10:11Z",
        ),
        _hermes(
            slug="google-workspace",
            name="Google Workspace",
            summary="Work with Gmail, Calendar, Drive, Docs, and Sheets through CLI or Python tooling.",
            category="Productivity",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="maps",
            name="Maps",
            summary="Geocode places and inspect points of interest, routes, and time zones.",
            category="Productivity",
            version="1.2.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="nano-pdf",
            name="Nano PDF",
            summary="Edit PDF text, titles, and typographical errors through a natural-language CLI.",
            category="Productivity",
            version="1.0.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="notion",
            name="Notion",
            summary="Manage Notion pages, databases, and Markdown through API and CLI tooling.",
            category="Productivity",
            version="2.0.0",
            license_label="MIT",
            updated_at="2026-06-10T22:10:11Z",
        ),
        _hermes(
            slug="ocr-and-documents",
            name="OCR and Documents",
            summary="Extract text from PDFs and scanned documents.",
            category="Productivity",
            version="2.3.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="powerpoint",
            name="PowerPoint",
            summary="Create, read, and edit presentation decks, slides, notes, and templates.",
            category="Productivity",
            version="Not provided",
            license_label="Proprietary terms provided by source",
            updated_at="2026-05-08T21:27:40Z",
        ),
        _hermes(
            slug="teams-meeting-pipeline",
            name="Teams Meeting Pipeline",
            summary="Operate the Teams meeting summary pipeline and inspect Microsoft Graph subscription posture.",
            category="Productivity",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-06-10T22:10:11Z",
        ),
        _hermes(
            slug="plan",
            name="Plan",
            summary="Write an actionable plan with bite-sized tasks and no execution.",
            category="Software Development",
            version="2.0.0",
            license_label="MIT",
            updated_at="2026-06-04T13:11:22Z",
        ),
        _hermes(
            slug="systematic-debugging",
            name="Systematic Debugging",
            summary="Use a four-phase root-cause process to understand bugs before fixing them.",
            category="Software Development",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-06-21T06:23:47Z",
        ),
        _hermes(
            slug="test-driven-development",
            name="Test-Driven Development",
            summary="Use red, green, and refactor cycles with tests written before implementation.",
            category="Software Development",
            version="1.1.0",
            license_label="MIT",
            updated_at="2026-06-21T06:23:47Z",
        ),
        _hermes(
            slug="requesting-code-review",
            name="Requesting Code Review",
            summary="Run pre-commit review, security scanning, quality gates, and bounded automatic fixes.",
            category="Software Development",
            version="2.0.0",
            license_label="MIT",
            updated_at="2026-06-04T13:11:22Z",
        ),
        _hermes(
            slug="simplify-code",
            name="Simplify Code",
            summary="Review and simplify recent code changes through a multi-agent cleanup workflow.",
            category="Software Development",
            version="1.0.0",
            license_label="MIT",
            updated_at="2026-06-19T14:35:36Z",
        ),
        _hermes(
            slug="jupyter-live-kernel",
            name="Jupyter Live Kernel",
            summary="Run iterative Python work through a live Jupyter kernel.",
            category="Data Science",
            version="1.0.0",
            license_label="MIT",
            updated_at="2026-05-08T21:27:40Z",
        ),
    ],
    "entry_count": 31,
}
