from __future__ import annotations

from typing import Any, Callable

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


def criteria(build: Callable[..., Any]) -> list[Any]:
    return [
        build(
                    "m131_autonomy_mode4_scoped_work_session_contracts",
                    "M131 Autonomy Mode 4 Scoped Work Session",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m131_autonomy_mode4_scoped_work_session_contracts",
                    "M131 defines a contract-only, review-only Mode 4 scoped work session with exact actor, resource, capability, allowlist, duration, policy, approval, risk, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M131 Mode 4 scoped work session contracts are missing, weak, unsafe, not exact-bound, or imply session start, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, background work, routes, controls, dependencies, M132 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m131_autonomy_mode4_scoped_work_session_static_safety",
                    "M131 Autonomy Mode 4 Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m131_autonomy_mode4_scoped_work_session_static_safety",
                    "M131 source keeps Mode 4 scoped work sessions contract-only, review-only, scoped-work-session-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M131 source contains forbidden Mode 4 runtime, session start, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, background, scheduler, model, memory, context, route, control, dependency, M132, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m131_autonomy_mode4_scoped_work_session_route_boundary",
                    "M131 Autonomy Mode 4 Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m131_autonomy_mode4_scoped_work_session_route_boundary",
                    "M131 adds no Mode 4, scoped work session start, autonomous action, shell, command, browser, network, plugin, connector runtime, mobile, remote, background, scheduler, model, memory, context, or production authority routes.",
                    "M131 route boundary drifted or exposed Mode 4 runtime, session start, autonomous action, execution, browser, network, plugin, connector, mobile, remote, background, scheduler, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m131_roadmap_currentness",
                    "M131 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m131_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M131 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M131 or imply M140 higher-autonomy red-team freeze, trusted recurring workflow runtime, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m132_trusted_recurring_workflow_contracts",
                    "M132 Trusted Recurring Workflow",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m132_trusted_recurring_workflow_contracts",
                    "M132 defines a contract-only, review-only Mode 5 trusted recurring workflow with exact scope, M131, M97, M98, cadence, approval renewal, expiration, stop condition, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M132 trusted recurring workflow contracts are missing, weak, unsafe, not exact-bound, or imply workflow start, recurrence activation, scheduler, background worker, long-running supervisor, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M133 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m132_trusted_recurring_workflow_static_safety",
                    "M132 Trusted Recurring Workflow Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m132_trusted_recurring_workflow_static_safety",
                    "M132 source keeps Mode 5 trusted recurring workflows contract-only, review-only, trusted-recurring-workflow-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M132 source contains forbidden Mode 5 runtime, workflow start, recurrence, scheduler, background worker, supervisor, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, model, memory, context, route, control, dependency, M133, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m132_trusted_recurring_workflow_route_boundary",
                    "M132 Trusted Recurring Workflow Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m132_trusted_recurring_workflow_route_boundary",
                    "M132 adds no Mode 5, trusted recurring workflow start, recurrence, scheduler, background, supervisor, autonomous action, shell, command, browser, network, plugin, connector runtime, mobile, remote, model, memory, context, or production authority routes.",
                    "M132 route boundary drifted or exposed Mode 5 runtime, workflow start, recurrence, scheduler, supervisor, autonomous action, execution, browser, network, plugin, connector, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m132_roadmap_currentness",
                    "M132 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m132_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M132 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M132 or imply M140 higher-autonomy red-team freeze, scheduler/runtime authority, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m133_long_running_task_supervisor_contracts",
                    "M133 Long-Running Task Supervisor",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m133_long_running_task_supervisor_contracts",
                    "M133 defines a contract-only, review-only long-running task supervisor with exact scope, Mode 5, M132, M131, supervisor plan, task state, heartbeat, checkpoint, context budget, pause/resume/stop, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M133 long-running task supervisor contracts are missing, weak, unsafe, not exact-bound, or imply supervisor start, supervisor runtime, task supervision, heartbeat monitor, checkpoint scheduler, resume/recovery execution, human checkpoint scheduling, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M134 work, M135 recovery work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m133_long_running_task_supervisor_static_safety",
                    "M133 Long-Running Task Supervisor Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m133_long_running_task_supervisor_static_safety",
                    "M133 source keeps long-running task supervision contract-only, review-only, long-running-supervisor-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M133 source contains forbidden supervisor runtime, supervisor start, heartbeat monitor, checkpoint scheduler, resume/recovery execution, human checkpoint scheduling, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, model, memory, context, route, control, dependency, M134, M135, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m133_long_running_task_supervisor_route_boundary",
                    "M133 Long-Running Task Supervisor Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m133_long_running_task_supervisor_route_boundary",
                    "M133 adds no supervisor start, task supervision, heartbeat, checkpoint scheduling, resume, recovery, human checkpoint scheduling, scheduler, background, autonomous action, shell, command, browser, network, plugin, connector runtime, mobile, remote, model, memory, context, or production authority routes.",
                    "M133 route boundary drifted or exposed supervisor runtime, supervisor start, heartbeat, checkpoint scheduling, resume, recovery, human checkpoint scheduling, execution, browser, network, plugin, connector, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m133_roadmap_currentness",
                    "M133 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m133_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M133 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M133 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m134_human_checkpoint_scheduling_contracts",
                    "M134 Human Checkpoint Scheduling",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m134_human_checkpoint_scheduling_contracts",
                    "M134 defines a contract-only, review-only human checkpoint scheduling contract with exact scope, Mode 5, M133, M132, checkpoint plan, schedule plan, checkpoint window, reviewer, consent, expiration, reminder, escalation, pause/stop, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M134 human checkpoint scheduling contracts are missing, weak, unsafe, not exact-bound, or imply checkpoint scheduling, prompt, notification delivery, reminder runtime, calendar write, approval capture, escalation runtime, supervisor/recovery execution, scheduler/background worker, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M135 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m134_human_checkpoint_scheduling_static_safety",
                    "M134 Human Checkpoint Scheduling Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m134_human_checkpoint_scheduling_static_safety",
                    "M134 source keeps human checkpoint scheduling contract-only, review-only, human-checkpoint-scheduling-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M134 source contains forbidden checkpoint scheduler, prompt, notification, reminder, calendar, approval, escalation, supervisor/recovery, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, model, memory, context, route, control, dependency, M135, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m134_human_checkpoint_scheduling_route_boundary",
                    "M134 Human Checkpoint Scheduling Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m134_human_checkpoint_scheduling_route_boundary",
                    "M134 adds no human checkpoint scheduling, prompt, notification, reminder, calendar, approval, escalation, recovery, scheduler, background, autonomous action, shell, command, browser, network, plugin, connector runtime, mobile, remote, model, memory, context, or production authority routes.",
                    "M134 route boundary drifted or exposed human checkpoint scheduling, prompt, notification, reminder, calendar, approval, escalation, recovery, execution, browser, network, plugin, connector, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m134_roadmap_currentness",
                    "M134 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m134_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M134 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M134 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m135_autonomous_recovery_planner_contracts",
                    "M135 Autonomous Recovery Planner",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m135_autonomous_recovery_planner_contracts",
                    "M135 defines a contract-only, review-only autonomous recovery planner contract with exact scope, Mode 5, M134, M133, M132, failure signal, recovery trigger, recovery strategy, recovery steps, rollback, resume, checkpoint, human checkpoint, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M135 autonomous recovery planner contracts are missing, weak, unsafe, not exact-bound, or imply recovery execution, retry execution, resume execution, rollback execution, supervisor runtime, scheduler/background worker, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M136 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m135_autonomous_recovery_planner_static_safety",
                    "M135 Autonomous Recovery Planner Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m135_autonomous_recovery_planner_static_safety",
                    "M135 source keeps autonomous recovery planning contract-only, review-only, autonomous-recovery-planner-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M135 source contains forbidden recovery runtime, retry, resume, rollback, supervisor, checkpoint scheduler, prompt, notification, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, model, memory, context, route, control, dependency, M136, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m135_autonomous_recovery_planner_route_boundary",
                    "M135 Autonomous Recovery Planner Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m135_autonomous_recovery_planner_route_boundary",
                    "M135 adds no autonomous recovery planner, recovery execution, retry, resume, rollback, scheduler, background, autonomous action, shell, command, browser, network, plugin, connector runtime, mobile, remote, model, memory, context, or production authority routes.",
                    "M135 route boundary drifted or exposed autonomous recovery planning, recovery execution, retry, resume, rollback, execution, browser, network, plugin, connector, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m135_roadmap_currentness",
                    "M135 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m135_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M135 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M135 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m136_cross_tool_dependency_execution_contracts",
                    "M136 Cross-Tool Dependency Execution",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m136_cross_tool_dependency_execution_contracts",
                    "M136 defines a contract-only, review-only cross-tool dependency execution contract with exact scope, Mode 5, M135, M134, M133, M132, dependency graph, acyclic dependency edges, dependency order, safe tool, dry-run plan, human checkpoint, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M136 cross-tool dependency execution contracts are missing, weak, unsafe, not exact-bound, or imply dependency execution, dependency resolver runtime, cross-tool runtime, parallel tool execution, tool state handoff, tool output routing, recovery execution, supervisor runtime, scheduler/background worker, autonomous actions, execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M137 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m136_cross_tool_dependency_execution_static_safety",
                    "M136 Cross-Tool Dependency Execution Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m136_cross_tool_dependency_execution_static_safety",
                    "M136 source keeps cross-tool dependency execution contract-only, review-only, cross-tool-dependency-execution-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M136 source contains forbidden dependency execution, resolver, cross-tool runtime, parallel tool execution, tool state handoff, tool output routing, recovery, supervisor, checkpoint scheduler, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, account, mobile, remote, model, memory, context, route, control, dependency, M137, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m136_cross_tool_dependency_execution_route_boundary",
                    "M136 Cross-Tool Dependency Execution Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m136_cross_tool_dependency_execution_route_boundary",
                    "M136 adds no cross-tool dependency execution, dependency resolver, tool execution, connector runtime, browser action, scheduler, background, autonomous action, shell, command, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M136 route boundary drifted or exposed cross-tool dependency execution, dependency resolver, tool execution, connector runtime, browser action, execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m136_roadmap_currentness",
                    "M136 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m136_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M136 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M136 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m137_browser_connector_combined_workflow_contracts",
                    "M137 Autonomous Browser + Connector Combined Workflows",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m137_browser_connector_combined_workflow_contracts",
                    "M137 defines a contract-only, review-only browser + connector combined workflow contract with exact scope, Mode 5, M136, M135, M134, M133, M132, browser plan, connector plan, dependency graph, dependency order, approval bundle, human checkpoint, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M137 browser + connector combined workflow contracts are missing, weak, unsafe, not exact-bound, or imply combined workflow runtime, browser action, connector action, account auth, dependency execution, tool/shell/network/browser/plugin/connector/mobile/remote runtime, routes, controls, dependencies, M139 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m137_browser_connector_combined_workflow_static_safety",
                    "M137 Browser + Connector Combined Workflow Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m137_browser_connector_combined_workflow_static_safety",
                    "M137 source keeps browser + connector combined workflow contract-only, review-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M137 source contains forbidden combined workflow runtime, browser action, connector action, account auth, dependency execution, autonomous action, execution, tool, shell, command, filesystem, network, browser, plugin, connector, mobile, remote, model, memory, context, route, control, dependency, M139, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m137_browser_connector_combined_workflow_route_boundary",
                    "M137 Browser + Connector Combined Workflow Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m137_browser_connector_combined_workflow_route_boundary",
                    "M137 adds no combined workflow, browser action, connector action, account auth, dependency execution, tool execution, scheduler, background, autonomous action, shell, command, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M137 route boundary drifted or exposed combined workflow runtime, browser action, connector action, account auth, dependency execution, execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m137_roadmap_currentness",
                    "M137 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m137_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M137 through Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M137 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m138_autonomous_error_handling_guardrails_contracts",
                    "M138 Autonomous Error Handling Guardrails",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m138_autonomous_error_handling_guardrails_contracts",
                    "M138 defines contract-only, review-only autonomous error handling guardrail records with exact scope, Mode 5, M137, M136, M135, M134, M133, M132, error signal, guardrail policy, retry, fallback, escalation, recovery, rollback, resume, human checkpoint, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M138 autonomous error handling guardrail contracts are missing, weak, unsafe, not exact-bound, or imply error handling runtime, retry, rollback, resume, recovery, fallback, escalation, dependency execution, browser/connector/tool/shell/network/plugin/mobile/remote runtime, routes, controls, dependencies, M139 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m138_autonomous_error_handling_guardrails_static_safety",
                    "M138 Autonomous Error Handling Guardrails Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m138_autonomous_error_handling_guardrails_static_safety",
                    "M138 source keeps autonomous error handling guardrails contract-only, review-only, autonomous-error-handling-guardrails-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M138 source contains forbidden error handling runtime, retry, rollback, resume, recovery, fallback, escalation, loop recovery, dependency execution, browser action, connector action, autonomous action, execution, tool, shell, command, filesystem, network, plugin, mobile, remote, model, memory, context, route, control, dependency, M139, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m138_autonomous_error_handling_guardrails_route_boundary",
                    "M138 Autonomous Error Handling Guardrails Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m138_autonomous_error_handling_guardrails_route_boundary",
                    "M138 adds no autonomous error handling guardrail, retry, rollback, resume, recovery, fallback, escalation, loop recovery, dependency execution, browser action, connector action, tool execution, scheduler, background, autonomous action, shell, command, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M138 route boundary drifted or exposed error handling runtime, retry, rollback, resume, recovery, fallback, escalation, execution, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m138_roadmap_currentness",
                    "M138 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m138_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M138 and Checkpoint M139 implemented and keep M140-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M138 or imply M140 higher-autonomy red-team freeze, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m139_autonomy_abuse_loop_detection_contracts",
                    "M139 Autonomy Abuse/Loop Detection",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m139_autonomy_abuse_loop_detection_contracts",
                    "M139 defines contract-only, review-only autonomy abuse/loop detection records with exact scope, Mode 5, M138, M137, M136, M135, M134, M133, M132, abuse signal, loop signal, pattern policy, threshold policy, intervention, escalation, human checkpoint, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M139 autonomy abuse/loop detection contracts are missing, weak, unsafe, not exact-bound, or imply abuse/loop detector runtime, loop monitor, intervention, recovery/retry/rollback/resume execution, dependency execution, browser/connector/tool/shell/network/plugin/mobile/remote runtime, routes, controls, dependencies, M140 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m139_autonomy_abuse_loop_detection_static_safety",
                    "M139 Autonomy Abuse/Loop Detection Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m139_autonomy_abuse_loop_detection_static_safety",
                    "M139 source keeps autonomy abuse/loop detection contract-only, review-only, autonomy-abuse-loop-detection-only, safe-ref-only, exact-bound, no-effect, and route-free.",
                    "M139 source contains forbidden abuse detection, loop detection, monitor, detector runtime, loop intervention, recovery, retry, rollback, resume, dependency execution, browser action, connector action, autonomous action, execution, tool, shell, command, filesystem, network, plugin, mobile, remote, model, memory, context, route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m139_autonomy_abuse_loop_detection_route_boundary",
                    "M139 Autonomy Abuse/Loop Detection Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m139_autonomy_abuse_loop_detection_route_boundary",
                    "M139 adds no autonomy abuse/loop detection, detector, monitor, intervention, recovery, retry, rollback, resume, dependency execution, browser action, connector action, tool execution, scheduler, background, autonomous action, shell, command, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M139 route boundary drifted or exposed abuse/loop detection runtime, monitor, intervention, recovery, execution, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m139_roadmap_currentness",
                    "M139 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m139_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M139 and Checkpoint M140 implemented and keep M141-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M139 or imply M141 multi-user product boundary, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m140_higher_autonomy_red_team_freeze_contracts",
                    "M140 Higher-Autonomy Red-Team Freeze",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m140_higher_autonomy_red_team_freeze_contracts",
                    "M140 defines contract-only, review-only, freeze-only higher-autonomy red-team freeze records exact-bound to accepted M131-M139 refs, red-team checklist refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M140 higher-autonomy red-team freeze contracts are missing, weak, unsafe, not exact-bound, or imply red-team runtime, red-team harness execution, adversarial test execution, broad autonomy, execution, routes, controls, dependencies, M141 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m140_higher_autonomy_red_team_freeze_static_safety",
                    "M140 Higher-Autonomy Red-Team Freeze Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m140_higher_autonomy_red_team_freeze_static_safety",
                    "M140 source keeps higher-autonomy red-team freeze contract-only, review-only, freeze-only, deterministic, local-only, safe-ref-only, no-effect, and route-free.",
                    "M140 source contains forbidden red-team runtime, harness execution, adversarial test execution, autonomous execution, broad autonomy, global switch, tool/shell/browser/connector/network/plugin/mobile/remote/model/memory/context route, control, dependency, alpha, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m140_higher_autonomy_red_team_freeze_route_boundary",
                    "M140 Higher-Autonomy Red-Team Freeze Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m140_higher_autonomy_red_team_freeze_route_boundary",
                    "M140 adds no higher-autonomy red-team freeze, red-team runtime, harness execution, adversarial test, autonomous execution, multi-user, browser action, connector action, tool execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M140 route boundary drifted or exposed red-team runtime, harness execution, adversarial test, autonomous execution, multi-user, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m140_roadmap_currentness",
                    "M140 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m140_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M140 implemented and keep M141-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M140 or imply M141 multi-user product runtime, tenant/workspace sharing, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m141_multi_user_product_boundary_contracts",
                    "M141 Multi-User Product Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m141_multi_user_product_boundary_contracts",
                    "M141 defines contract-only, review-only, deterministic, local-only, safe-ref-only multi-user product boundary records exact-bound to accepted M101-M140 refs, user/workspace/tenant/role/privacy boundary refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M141 multi-user product boundary contracts are missing, weak, unsafe, not exact-bound, or imply multi-user runtime, account tenancy, auth runtime, workspace sharing, identity federation, execution, routes, controls, dependencies, M142 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m141_multi_user_product_boundary_static_safety",
                    "M141 Multi-User Product Boundary Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m141_multi_user_product_boundary_static_safety",
                    "M141 source keeps the multi-user product boundary contract-only, review-only, deterministic, local-only, safe-ref-only, product-boundary-only, no-effect, and route-free.",
                    "M141 source contains forbidden multi-user runtime, account tenancy, tenant runtime, workspace sharing, identity federation, auth/session, connector/tool/shell/browser/network/plugin/mobile/remote/model/memory/context route, control, dependency, alpha privacy review, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m141_multi_user_product_boundary_route_boundary",
                    "M141 Multi-User Product Boundary Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m141_multi_user_product_boundary_route_boundary",
                    "M141 adds no multi-user, account tenancy, tenant, workspace sharing, identity federation, auth, alpha privacy review, browser action, connector action, tool execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M141 route boundary drifted or exposed multi-user runtime, tenancy, workspace sharing, identity federation, auth, alpha privacy review, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m141_roadmap_currentness",
                    "M141 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m141_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M140 and Checkpoint M141 implemented and keep M142-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M141 or imply M142 alpha privacy review runtime, multi-user runtime, account tenancy, workspace sharing, auth runtime, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m142_alpha_privacy_review_contracts",
                    "M142 Alpha Privacy Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m142_alpha_privacy_review_contracts",
                    "M142 defines contract-only, review-only, deterministic, local-only, safe-ref-only alpha privacy review records exact-bound to accepted M101-M141 refs, privacy review refs, data boundary refs, disclosure review refs, consent review refs, retention review refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M142 alpha privacy review contracts are missing, weak, unsafe, not exact-bound, or imply privacy review execution, alpha privacy sign-off, alpha UI runtime, raw private content access, routes, controls, dependencies, M143 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m142_alpha_privacy_review_static_safety",
                    "M142 Alpha Privacy Review Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m142_alpha_privacy_review_static_safety",
                    "M142 source keeps alpha privacy review contract-only, review-only, deterministic, local-only, safe-ref-only, alpha-privacy-review-only, no-effect, and route-free.",
                    "M142 source contains forbidden privacy review execution, alpha sign-off, alpha UI runtime, raw private content, tool/shell/browser/connector/network/plugin/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m142_alpha_privacy_review_route_boundary",
                    "M142 Alpha Privacy Review Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m142_alpha_privacy_review_route_boundary",
                    "M142 adds no alpha privacy review, privacy execution, raw privacy, alpha UI, app readiness, browser action, connector action, tool execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M142 route boundary drifted or exposed alpha privacy review runtime, raw privacy content, alpha UI, app readiness, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m142_roadmap_currentness",
                    "M142 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m142_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M141 and Checkpoint M142 implemented and keep M143-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M142 or imply M143 alpha UI/runtime, alpha release, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m143_alpha_ui_app_readiness_contracts",
                    "M143 Alpha UI and App Readiness",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m143_alpha_ui_app_readiness_contracts",
                    "M143 defines contract-only, review-only, deterministic, local-only, safe-ref-only alpha UI and app readiness records exact-bound to accepted M101-M142 refs, UI readiness refs, app readiness refs, privacy review refs, accessibility review refs, release blocker refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M143 alpha UI/app readiness contracts are missing, weak, unsafe, not exact-bound, or imply UI runtime, app readiness execution, app build/signing, App Store Connect, TestFlight upload, release, routes, controls, dependencies, M144 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m143_alpha_ui_app_readiness_static_safety",
                    "M143 Alpha UI and App Readiness Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m143_alpha_ui_app_readiness_static_safety",
                    "M143 source keeps alpha UI/app readiness contract-only, review-only, deterministic, local-only, safe-ref-only, alpha-ui-app-readiness-only, no-effect, and route-free.",
                    "M143 source contains forbidden alpha UI runtime, app readiness execution, app build/signing, App Store Connect, TestFlight upload, release, tool/shell/browser/connector/network/plugin/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m143_alpha_ui_app_readiness_route_boundary",
                    "M143 Alpha UI and App Readiness Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m143_alpha_ui_app_readiness_route_boundary",
                    "M143 adds no alpha UI, app readiness, app build/signing, App Store Connect, TestFlight upload, release, plugin marketplace, browser action, connector action, tool execution, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M143 route boundary drifted or exposed alpha UI runtime, app readiness execution, app build/signing, App Store Connect, TestFlight upload, release, plugin marketplace, browser, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m143_roadmap_currentness",
                    "M143 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m143_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M142, Checkpoint M143, Checkpoint M144, Checkpoint M145, and Checkpoint M146 implemented and keep M147 implemented and M148-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M143 or imply M144 plugin marketplace runtime, alpha release, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m144_plugin_marketplace_policy_draft_contracts",
                    "M144 Plugin Marketplace Policy Draft",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m144_plugin_marketplace_policy_draft_contracts",
                    "M144 defines contract-only, review-only, deterministic, local-only, safe-ref-only, policy-draft-only, disabled-by-default plugin marketplace policy draft records exact-bound to accepted M101-M143 refs, marketplace policy refs, publisher policy refs, listing review refs, provenance review refs, signature review refs, sandbox review refs, permission mapping refs, approval policy refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M144 plugin marketplace policy draft contracts are missing, weak, unsafe, not exact-bound, or imply marketplace runtime, publishing, plugin install, plugin enablement, plugin execution, external plugin authority, package import, network plugin fetch, routes, controls, dependencies, M145 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m144_plugin_marketplace_policy_draft_static_safety",
                    "M144 Plugin Marketplace Policy Draft Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m144_plugin_marketplace_policy_draft_static_safety",
                    "M144 source keeps plugin marketplace policy draft contract-only, review-only, deterministic, local-only, safe-ref-only, policy-draft-only, disabled-by-default, no-effect, and route-free.",
                    "M144 source contains forbidden marketplace runtime, marketplace publish, plugin install, plugin enablement, plugin execution, external plugin authority/loading, package import, runtime import, network plugin fetch, package download, artifact upload, tool/shell/browser/connector/network/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m144_plugin_marketplace_policy_draft_route_boundary",
                    "M144 Plugin Marketplace Policy Draft Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m144_plugin_marketplace_policy_draft_route_boundary",
                    "M144 adds no plugin marketplace, marketplace publish, marketplace install, plugin install, plugin enablement, plugin execution, plugin runtime, package import/download/upload, network, browser, connector, tool execution, mobile, remote, model, memory, context, or production authority routes.",
                    "M144 route boundary drifted or exposed marketplace runtime, marketplace publish, plugin install, plugin enablement, plugin execution, external plugin loading, package import/download/upload, network, browser, connector, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m144_roadmap_currentness",
                    "M144 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m144_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M143, Checkpoint M144, Checkpoint M145, and Checkpoint M146 implemented and keep M147 implemented and M148-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M144 or imply M145 enterprise/pro runtime, marketplace runtime, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m145_enterprise_pro_safety_modes_contracts",
                    "M145 Enterprise/Pro Safety Modes",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m145_enterprise_pro_safety_modes_contracts",
                    "M145 defines contract-only, review-only, deterministic, local-only, safe-ref-only, safety-modes-only, disabled-by-default Enterprise/Pro safety mode records exact-bound to accepted M101-M144 refs, enterprise safety mode refs, pro safety mode refs, workspace boundary refs, role policy refs, authority ceiling refs, feature availability refs, escalation policy refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M145 Enterprise/Pro safety mode contracts are missing, weak, unsafe, not exact-bound, or imply enterprise runtime, pro runtime, safety mode runtime, plan enforcement, billing runtime, account/tenant runtime, auth runtime, routes, controls, dependencies, M146 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m145_enterprise_pro_safety_modes_static_safety",
                    "M145 Enterprise/Pro Safety Modes Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m145_enterprise_pro_safety_modes_static_safety",
                    "M145 source keeps Enterprise/Pro safety modes contract-only, review-only, deterministic, local-only, safe-ref-only, safety-modes-only, disabled-by-default, no-effect, and route-free.",
                    "M145 source contains forbidden enterprise runtime, pro runtime, safety mode runtime, plan enforcement, billing runtime, account/tenant runtime, auth runtime, connector runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m145_enterprise_pro_safety_modes_route_boundary",
                    "M145 Enterprise/Pro Safety Modes Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m145_enterprise_pro_safety_modes_route_boundary",
                    "M145 adds no enterprise/pro runtime, safety mode enable/enforce, plan enforcement, billing, account tenant, role runtime, auth/login, workspace sharing, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M145 route boundary drifted or exposed enterprise/pro runtime, safety mode enforcement, plan enforcement, billing, account tenant, auth, workspace sharing, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m145_roadmap_currentness",
                    "M145 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m145_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M144, Checkpoint M145, and Checkpoint M146 implemented and keep M147 implemented and M148-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M145 or imply M146 billing runtime, plan enforcement, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m146_billing_plan_boundary_contracts",
                    "M146 Billing/Plan Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m146_billing_plan_boundary_contracts",
                    "M146 defines contract-only, review-only, deterministic, local-only, safe-ref-only, billing-boundary-only, disabled-by-default billing/plan boundary records exact-bound to accepted M101-M145 refs, billing boundary refs, plan boundary refs, entitlement boundary refs, pricing disclosure refs, payment provider boundary refs, upgrade/downgrade policy refs, support/refund policy refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M146 billing/plan boundary contracts are missing, weak, unsafe, not exact-bound, or imply payment processing, checkout runtime, subscription management, plan enforcement, billing runtime, external billing provider, account-plan runtime, entitlement runtime, pricing runtime, routes, controls, dependencies, M147 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m146_billing_plan_boundary_static_safety",
                    "M146 Billing/Plan Boundary Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m146_billing_plan_boundary_static_safety",
                    "M146 source keeps billing/plan boundary contract-only, review-only, deterministic, local-only, safe-ref-only, billing-boundary-only, disabled-by-default, no-effect, and route-free.",
                    "M146 source contains forbidden payment processing, checkout runtime, subscription management, plan enforcement, billing runtime, external billing provider, account-plan runtime, entitlement runtime, pricing runtime, auth runtime, connector runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m146_billing_plan_boundary_route_boundary",
                    "M146 Billing/Plan Boundary Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m146_billing_plan_boundary_route_boundary",
                    "M146 adds no billing runtime, payment, checkout, subscription, invoice, entitlement, plan enforcement, account-plan, external billing provider, auth/login, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M146 route boundary drifted or exposed billing runtime, payment, checkout, subscription, invoice, entitlement, plan enforcement, account-plan, external billing provider, auth, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m146_roadmap_currentness",
                    "M146 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m146_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M145 and Checkpoint M146 implemented and keep M147 implemented and M148-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M146 or imply M147 public-docs automation, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m147_public_docs_wiki_readiness_contracts",
                    "M147 Public Docs + Wiki Readiness",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m147_public_docs_wiki_readiness_contracts",
                    "M147 defines contract-only, review-only, deterministic, local-only, safe-ref-only, docs-readiness-only, disabled-by-default public docs + wiki readiness records exact-bound to accepted M101-M146 refs, public doc refs, wiki readiness refs, docs index refs, canonical map refs, release note refs, disclosure review refs, publishing checklist refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M147 public docs + wiki readiness contracts are missing, weak, unsafe, not exact-bound, or imply public publishing, wiki publishing, wiki automation, GitHub wiki runtime, docs-site deploy, external distribution, artifact upload, release publishing, docs runtime, routes, controls, dependencies, M148 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m147_public_docs_wiki_readiness_static_safety",
                    "M147 Public Docs + Wiki Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m147_public_docs_wiki_readiness_static_safety",
                    "M147 source keeps public docs + wiki readiness contract-only, review-only, deterministic, local-only, safe-ref-only, docs-readiness-only, disabled-by-default, no-effect, and route-free.",
                    "M147 source contains forbidden public publishing, wiki publishing, wiki automation, GitHub wiki runtime, docs deploy, external distribution, artifact upload, release publishing, docs runtime, auth runtime, connector runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m147_public_docs_wiki_readiness_route_boundary",
                    "M147 Public Docs + Wiki Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m147_public_docs_wiki_readiness_route_boundary",
                    "M147 adds no public publishing, wiki publishing, wiki automation, GitHub wiki, docs deploy, external distribution, artifact upload, release publishing, auth/login, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M147 route boundary drifted or exposed public publishing, wiki publishing, wiki automation, GitHub wiki, docs deploy, external distribution, artifact upload, release publishing, auth, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m147_roadmap_currentness",
                    "M147 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m147_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M146 and Checkpoint M147 implemented and keep M148-M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M147 or imply M148 external security automation, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m148_external_security_review_contracts",
                    "M148 External Security Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m148_external_security_review_contracts",
                    "M148 defines contract-only, review-only, deterministic, local-only, safe-ref-only, external-security-review-only, disabled-by-default security review records exact-bound to accepted M101-M147 refs, security review refs, threat model refs, review scope refs, evidence index refs, finding summary refs, disclosure review refs, remediation plan refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M148 external security review contracts are missing, weak, unsafe, not exact-bound, or imply external vendor handoff, security vendor handoff, review automation, scanner runtime, vulnerability scanning, repository export, artifact export, issue export, security review runtime, routes, controls, dependencies, M149 work, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m148_external_security_review_static_safety",
                    "M148 External Security Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m148_external_security_review_static_safety",
                    "M148 source keeps external security review contract-only, review-only, deterministic, local-only, safe-ref-only, external-security-review-only, disabled-by-default, no-effect, and route-free.",
                    "M148 source contains forbidden external vendor handoff, security vendor handoff, external review automation, scanner runtime, vulnerability scan, repository export, artifact export, issue export, security review runtime, auth runtime, connector runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, beta, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m148_external_security_review_route_boundary",
                    "M148 External Security Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m148_external_security_review_route_boundary",
                    "M148 adds no external security review runtime, external vendor handoff, security vendor handoff, scanner runtime, vulnerability scan, repository export, artifact export, issue export, auth/login, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M148 route boundary drifted or exposed external security review runtime, vendor handoff, scanner runtime, vulnerability scan, repository export, artifact export, issue export, auth, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m148_roadmap_currentness",
                    "M148 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m148_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M147, Checkpoint M148, and Checkpoint M149 implemented and keep M150 planned/provisional, with M150 still reserved as v1.2.0-alpha.",
                    "Active roadmap docs are stale for Checkpoint M148 or imply M149 release-candidate execution, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m149_alpha_release_candidate_freeze_contracts",
                    "M149 Alpha Release Candidate Freeze",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m149_alpha_release_candidate_freeze_contracts",
                    "M149 defines contract-only, review-only, freeze-only, deterministic, local-only, safe-ref-only, alpha-release-candidate-freeze-only, disabled-by-default records exact-bound to accepted M101-M148 refs, release candidate refs, freeze checklist refs, alpha readiness refs, evidence index refs, blocker summary refs, signoff review refs, M150 promotion gate refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M149 alpha release candidate freeze contracts are missing, weak, unsafe, not exact-bound, or imply release publication, release tags, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, M150 release, release automation, routes, controls, dependencies, M150 execution, or production authority.",
                    "critical",
                ),
        build(
                    "m149_alpha_release_candidate_freeze_static_safety",
                    "M149 Alpha Release Candidate Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m149_alpha_release_candidate_freeze_static_safety",
                    "M149 source keeps alpha release candidate freeze contract-only, review-only, freeze-only, deterministic, local-only, safe-ref-only, alpha-release-candidate-freeze-only, disabled-by-default, no-effect, and route-free.",
                    "M149 source contains forbidden release publication, release tag, tag creation, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, M150 release, release automation, auth runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m149_alpha_release_candidate_freeze_route_boundary",
                    "M149 Alpha Release Candidate Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m149_alpha_release_candidate_freeze_route_boundary",
                    "M149 adds no alpha release candidate freeze runtime, release publication, release tag, tag creation, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, M150 release, release automation, auth/login, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M149 route boundary drifted or exposed release candidate runtime, release publication, release tag, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, M150 release, release automation, auth, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m149_roadmap_currentness",
                    "M149 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m149_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M148 and Checkpoint M149 implemented and preserve M150 as the v1.2.0-alpha alpha target with beta future.",
                    "Active roadmap docs are stale for Checkpoint M149 or imply M150 release publication, beta release, or production authority.",
                    "critical",
                ),
        build(
                    "m150_ultimate_ai_agent_alpha_contracts",
                    "M150 Ultimate AI Agent Alpha",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m150_ultimate_ai_agent_alpha_contracts",
                    "M150 defines contract-only, review-only, alpha-target-only, deterministic, local-only, safe-ref-only, disabled-by-default records exact-bound to accepted M101-M149 refs, alpha target refs, M149 release candidate freeze refs, alpha readiness refs, evidence index refs, blocker summary refs, signoff review refs, beta promotion gate refs, audit, replay, revocation, kill-switch, and no-effect receipt bindings.",
                    "M150 alpha target contracts are missing, weak, unsafe, not exact-bound, or imply release publication, release tags, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, release automation, routes, controls, dependencies, beta execution, or production authority.",
                    "critical",
                ),
        build(
                    "m150_ultimate_ai_agent_alpha_static_safety",
                    "M150 Ultimate AI Agent Alpha Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m150_ultimate_ai_agent_alpha_static_safety",
                    "M150 source keeps Ultimate AI Agent Alpha contract-only, review-only, alpha-target-only, deterministic, local-only, safe-ref-only, disabled-by-default, no-effect, and route-free.",
                    "M150 source contains forbidden release publication, release tag, tag creation, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, release automation, auth runtime, tool/shell/browser/network/mobile/remote/model/memory/context route, control, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m150_ultimate_ai_agent_alpha_route_boundary",
                    "M150 Ultimate AI Agent Alpha Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m150_ultimate_ai_agent_alpha_route_boundary",
                    "M150 adds no alpha target runtime, release publication, release tag, tag creation, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, release automation, auth/login, connector, network, plugin, mobile, remote, model, memory, context, or production authority routes.",
                    "M150 route boundary drifted or exposed alpha target runtime, release publication, release tag, artifact build/upload/export, external distribution, App Store/TestFlight submission, beta release, release automation, auth, connector, network, model, memory, context, or production authority routes.",
                    "critical",
                ),
        build(
                    "m150_roadmap_currentness",
                    "M150 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m150_roadmap_currentness",
                    "Active roadmap docs mark Checkpoint M149 and M150 implemented, with M150 recorded as v1.2.0-alpha target acceptance and beta still future.",
                    "Active roadmap docs are stale for M150 or imply release publication, beta release, or production authority.",
                    "critical",
                ),
    ]
