from __future__ import annotations

from typing import Any, Callable

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


def criteria(build: Callable[..., Any]) -> list[Any]:
    return [
        build(
                    "m11_runtime_readiness_files_present",
                    "M11 Runtime Readiness Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m11_runtime_readiness_files_present",
                    "Runtime readiness contracts, matrix, smoke report validation, API tests, and docs are present.",
                    "M11 runtime readiness package, tests, or docs are missing.",
                    "critical",
                ),
        build(
                    "m11_runtime_capability_matrix_safe",
                    "M11 Runtime Capability Matrix Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_runtime_capability_matrix_safe",
                    "Capability matrix marks live/cloud/remote/mobile/plugin surfaces as dry-run, planned-disabled, manual-only, simulated-only, or blocked.",
                    "Capability matrix implies new runtime execution, cloud, secrets, or provider readiness.",
                    "critical",
                ),
        build(
                    "m11_manual_smoke_report_validation_safe",
                    "M11 Manual Smoke Report Validation Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_manual_smoke_report_validation_safe",
                    "Manual smoke report validation accepts safe summaries and rejects raw prompts, secrets, remote endpoints, execution claims, and authoritative model output.",
                    "Manual smoke report validation accepted unsafe report content.",
                    "critical",
                ),
        build(
                    "m11_no_production_readiness_claim",
                    "M11 No Production Readiness Claim",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_no_production_readiness_claim",
                    "Readiness report remains non-production and non-authoritative.",
                    "Runtime readiness report claims production, real model, remote execution, mobile sensor, plugin, or truth authority readiness.",
                    "critical",
                ),
        build(
                    "m11_runtime_api_status_validation_only",
                    "M11 Runtime API Status Validation Only",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m11_runtime_api_status_validation_only",
                    "Runtime API exposes only readiness, capability matrix, and smoke-report validation routes with no execute/run/connect/dispatch/enable route.",
                    "Runtime API exposes a forbidden runtime execution or plugin enablement route.",
                    "critical",
                ),
        build(
                    "m11_no_smoke_script_execution_in_gate",
                    "M11 No Smoke Script Execution In Gate",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_no_smoke_script_execution_in_gate",
                    "verify_all.py and run_foundation_gate.py do not execute the manual local loopback smoke script.",
                    "Gate or verifier invokes local_loopback_smoke.py.",
                    "critical",
                ),
        build(
                    "m11_no_runtime_expansion_imports",
                    "M11 No Runtime Expansion Imports",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_no_runtime_expansion_imports",
                    "Runtime readiness code has no provider SDK, network, tokenizer, billing, shell, or eval/exec capability.",
                    "Runtime readiness code imports or calls forbidden runtime expansion APIs.",
                    "critical",
                ),
        build(
                    "m11_no_remote_mesh_mobile_or_plugin_enablement",
                    "M11 No Remote Mesh Mobile Or Plugin Enablement",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m11_no_remote_mesh_mobile_or_plugin_enablement",
                    "M11 does not enable live remote mesh/tailnet, mobile sensors, Codex plugins, native builds, or computer-use automation.",
                    "M11 source/docs imply live mesh, mobile sensor, plugin, native build, or computer-use enablement.",
                    "critical",
                ),
        build(
                    "m12_control_center_files_present",
                    "M12 Control Center Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m12_control_center_files_present",
                    "Control Center contracts, API tests, no-execution tests, docs, and release docs are present.",
                    "M12 Control Center files are missing.",
                    "critical",
                ),
        build(
                    "m12_control_center_manifest_read_only",
                    "M12 Control Center Manifest Read Only",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m12_control_center_manifest_read_only",
                    "Control Center manifest surfaces are read-only, preview-only, validation-only, planned-disabled, blocked, or not implemented.",
                    "Control Center manifest implies execution, plugin, mobile, remote, model, provider, or frontend capability.",
                    "critical",
                ),
        build(
                    "m12_control_center_dashboard_secret_safe",
                    "M12 Control Center Dashboard Secret Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m12_control_center_dashboard_secret_safe",
                    "Control Center dashboard is summary-only and contains no secret-like values or production readiness claims.",
                    "Control Center dashboard leaks unsafe data or claims production/runtime readiness.",
                    "critical",
                ),
        build(
                    "m12_control_center_action_preview_no_execution",
                    "M12 Control Center Action Preview No Execution",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m12_control_center_action_preview_no_execution",
                    "Control Center action previews never execute and deny execute, remote, mobile, plugin, credential, mutation, model, and provider claims.",
                    "Control Center action preview allowed execution or unsafe capability claims.",
                    "critical",
                ),
        build(
                    "m12_control_center_api_read_only",
                    "M12 Control Center API Read Only",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m12_control_center_api_read_only",
                    "Control Center API exposes only read-only, preview-only, exact Today-to-Action envelope, exact Action Inbox decision-state, exact Chat durable receipt/proposal handoff, exact memory review/context proposal, and exact memory feedback receipt routes with no execute/run/connect/dispatch/enable route.",
                    "Control Center API exposes an unsafe execution route or unsafe route metadata.",
                    "critical",
                ),
        build(
                    "m12_no_frontend_dependencies",
                    "M12 No Root Frontend Dependencies",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m12_no_frontend_dependencies",
                    "No root frontend package, node_modules, Vite/Next/shadcn/Tailwind, iOS, or macOS build setup is added to the Python Agent Core.",
                    "Root frontend or native build dependency/configuration was added.",
                    "critical",
                ),
        build(
                    "m12_no_runtime_network_mobile_plugin_expansion",
                    "M12 No Runtime Network Mobile Plugin Expansion",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m12_no_runtime_network_mobile_plugin_expansion",
                    "Control Center source has no runtime execution, network, provider, tokenizer, billing, remote dispatch, mobile sensor, plugin enablement, shell, or browser automation capability.",
                    "Control Center source contains forbidden runtime/network/mobile/plugin expansion capability.",
                    "critical",
                ),
        build(
                    "m13_web_control_center_files_present",
                    "M13 Web Control Center Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m13_web_control_center_files_present",
                    "M13 React/Vite shell, typed API layer, mock fixtures, tests, docs, and safety policy files are present.",
                    "M13 Web Control Center shell files are missing.",
                    "critical",
                ),
        build(
                    "m13_web_shell_read_only_preview_only",
                    "M13 Web Shell Read Only Preview Only",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_web_shell_read_only_preview_only",
                    "Frontend dependencies and source remain limited to a local read-only/preview-only shell with no unsafe controls or integrations.",
                    "M13 frontend source or dependencies imply execution, plugin, remote, mobile, native, browser, Chrome, or provider capability.",
                    "critical",
                ),
        build(
                    "m13_action_preview_ui_posts_only_to_preview",
                    "M13 Action Preview UI Posts Only To Preview",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_action_preview_ui_posts_only_to_preview",
                    "The frontend declares only explicitly scoped, allowlisted POST targets.",
                    "M13 frontend declares an unsafe or additional POST target.",
                    "critical",
                ),
        build(
                    "m13_mock_data_safe_non_authoritative",
                    "M13 Mock Data Safe Non Authoritative",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_mock_data_safe_non_authoritative",
                    "Mock frontend fixtures are visibly mock, non-authoritative, and keep runtime, remote, mobile, plugin, and native capabilities disabled or blocked.",
                    "M13 mock frontend data claims unsafe authority or leaks secret-like values.",
                    "critical",
                ),
        build(
                    "m13_no_tracked_generated_or_native_artifacts",
                    "M13 No Tracked Generated Or Native Artifacts",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_no_tracked_generated_or_native_artifacts",
                    "Frontend build output, node_modules, coverage, env files, and native/mobile project artifacts remain ignored/untracked and native files are absent.",
                    "M13 generated, env, or native/mobile artifacts are present in the release boundary.",
                    "critical",
                ),
        build(
                    "m13_backend_api_contract_unchanged",
                    "M13 Backend API Contract Unchanged",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m13_backend_api_contract_unchanged",
                    "The normalized historical API boundary stays at 79 paths while exact post-milestone read-only/preview-only Control Center routes are explicitly allowlisted and no new execution route appears.",
                    "M13 changed backend API route count or exposed unsafe Control Center routes.",
                    "critical",
                ),
        build(
                    "m13_frontend_no_sensitive_browser_apis",
                    "M13 Frontend No Sensitive Browser APIs",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_frontend_no_sensitive_browser_apis",
                    "Frontend implementation uses no browser storage, credential, cookie, clipboard write, notification, push, camera, microphone, or location APIs.",
                    "M13 frontend source uses sensitive browser storage, credentials, cookies, clipboard write, notification, push, camera, microphone, or location APIs.",
                    "critical",
                ),
        build(
                    "m13_control_center_frontend_safety_verifier_passes",
                    "M13 Control Center Frontend Safety Verifier Passes",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_control_center_frontend_safety_verifier_passes",
                    "scripts/verify_control_center_frontend.py passes and is wired into the release safety boundary.",
                    "Control Center frontend safety verifier failed or is missing.",
                    "critical",
                ),
        build(
                    "m13_frontend_ci_covers_local_checks",
                    "M13 Frontend CI Covers Local Checks",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_frontend_ci_covers_local_checks",
                    "CI runs Control Center npm ci, typecheck, lint, test, and build inside apps/control-center without browser, native, deploy, or external smoke automation.",
                    "Control Center frontend CI coverage is missing or includes forbidden browser/native/deploy automation.",
                    "critical",
                ),
        build(
                    "m13_browser_smoke_readiness_manual_local_only",
                    "M13 Browser Smoke Readiness Manual Local Only",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m13_browser_smoke_readiness_manual_local_only",
                    "Local browser smoke readiness is documented as manual, local-only, preview-only, non-authoritative, and unauthenticated-profile-free.",
                    "Browser smoke documentation is missing or implies unsafe browser, production, external, execution, or secret capture behavior.",
                    "critical",
                ),
        build(
                    "m13_browser_smoke_readiness_verifier_passes",
                    "M13 Browser Smoke Readiness Verifier Passes",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m13_browser_smoke_readiness_verifier_passes",
                    "scripts/verify_control_center_browser_smoke_readiness.py passes and remains static/readiness-only.",
                    "Control Center browser smoke readiness verifier failed or is missing.",
                    "critical",
                ),
        build(
                    "m14_local_backend_api_base_policy",
                    "M14 Local Backend API Base Policy",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m14_local_backend_api_base_policy",
                    "Web Control Center API base URL policy allows only relative, localhost, 127.0.0.1, and ::1 bases while blocking external or secret-like absolute URLs.",
                    "M14 frontend API base policy is missing or permits unsafe external/secret-like API bases.",
                    "critical",
                ),
        build(
                    "m14_connection_states_visible_and_safe",
                    "M14 Connection States Visible And Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m14_connection_states_visible_and_safe",
                    "Web Control Center shows unknown, checking, live, degraded, mock fallback, and offline-safe connection states with mock data marked non-authoritative.",
                    "M14 connection states are missing, unclear, or imply production authority.",
                    "critical",
                ),
        build(
                    "m14_backend_api_contract_unchanged",
                    "M14 Backend API Contract Unchanged",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m14_backend_api_contract_unchanged",
                    "The normalized historical API boundary stays at 79 paths while exact post-milestone Control Center routes are explicitly classified and no unsafe execution, dispatch, approval, or event route appears.",
                    "M14 changed backend API route count or exposed an out-of-scope backend route.",
                    "critical",
                ),
        build(
                    "m15_approval_receipt_event_ui_safe",
                    "M15 Approval Receipt Event UI Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m15_approval_receipt_event_ui_safe",
                    "Approval queue, receipt viewer, and event viewer UI files exist, remain read-only/preview-only, show redacted summaries, expose no approval execution controls, reject authority-bypass copy and raw sensitive fields, and pass the frontend safety verifier.",
                    "M15 approval, receipt, or event viewer UI is missing or violates the read-only/preview-only safety boundary.",
                    "critical",
                ),
        build(
                    "m16_event_timeline_trace_viewer_safe",
                    "M16 Event Timeline Trace Viewer Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m16_event_timeline_trace_viewer_safe",
                    "Event timeline and run/receipt trace viewer files exist, remain read-only/preview-only, show a redacted timeline with safe refs and Foundation Gate evidence summaries, expose no execution or export controls, reject raw payloads and credential-like fields, and pass the frontend safety verifier.",
                    "M16 event timeline or run/receipt trace viewer is missing or violates the read-only redaction safety boundary.",
                    "critical",
                ),
        build(
                    "m17_evidence_file_memory_viewer_safe",
                    "M17 Evidence File Memory Viewer Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m17_evidence_file_memory_viewer_safe",
                    "Evidence, file ref, and memory viewer files exist, remain read-only/preview-only, show summary-only refs with redacted metadata, treat memory as recall and not authority, expose no raw file, memory, evidence, prompt, provider, credential, mutation, filesystem browse, or execution controls, and pass the frontend safety verifier.",
                    "M17 evidence, file ref, or memory viewer is missing or violates the read-only summary-only redaction safety boundary.",
                    "critical",
                ),
        build(
                    "m17_evidence_file_memory_viewer_hardening_safe",
                    "M17 Evidence File Memory Viewer Hardening Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m17_evidence_file_memory_viewer_hardening_safe",
                    "M17 evidence, file ref, and memory viewers keep alternate mock refs visibly mock and redacted, expose accessible selected-card state, keep OpenAPI path count at 78, add no backend routes, and pass the frontend safety verifier.",
                    "M17 evidence/file/memory hardening is missing alternate safe refs, selected-state reviewability, frontend verifier coverage, or unchanged OpenAPI evidence.",
                    "critical",
                ),
        build(
                    "m18_local_runtime_manual_smoke_surface_safe",
                    "M18 Local Runtime Manual Smoke Surface Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m18_local_runtime_manual_smoke_surface_safe",
                    "M18 backend-owned local runtime status and manual smoke report validation-only surfaces exist, keep OpenAPI path count at 78, expose exact approved focused pytest receipts without broad runtime controls, show no raw smoke reports, and pass the frontend safety verifier.",
                    "M18 local runtime or manual smoke surface is missing, changed backend routes, or violates the exact-approved runtime and validation-only safety boundary.",
                    "critical",
                ),
        build(
                    "m19_mobile_companion_contract_planning_safe",
                    "M19 Mobile Companion Contract Planning Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m19_mobile_companion_contract_planning_safe",
                    "M19 mobile companion is contract/API planning only, adds no mobile app, no native build workflow, no sensor access, no mobile approval execution, keeps contacts/calendar planned-disabled and future-broker-only, rejects secret-like metadata refs, blocks external sends, rejects OS permission integration and background services, requires a future Device Capability Broker before sensors, keeps OpenAPI path count at 78, and leaves M20 planned.",
                    "M19 mobile companion planning is missing or violates the contract-only, no-native, no-sensor, no-authority boundary.",
                    "critical",
                ),
        build(
                    "m20_device_capability_broker_contract_safe",
                    "M20 Device Capability Broker Contract Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m20_device_capability_broker_contract_safe",
                    "M20 Device Capability Broker is contract-only, adds no sensor access, no OS permission integration, no native app, no runtime broker, no backend routes, rejects silent capture, raw payloads, automatic memory writes, external sends, background services, notification runtime, permission runtime claims, device-client authority, and enabled and implemented capability flags are rejected, keeps OpenAPI path count at 78, and leaves M21 planned.",
                    "M20 Device Capability Broker contract is missing or violates the contract-only, no-device-runtime, no-sensor, no-authority boundary.",
                    "critical",
                ),
    ]
