from __future__ import annotations

from typing import Any, Callable

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


def criteria(build: Callable[..., Any]) -> list[Any]:
    return [
        build(
                    "m151_local_openwebui_test_shell_contracts",
                    "M151 Local OpenWebUI Test Shell",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m151_local_openwebui_test_shell_contracts",
                    "M151 defines a local-dev-only, disabled-by-default, localhost-only OpenWebUI shell smoke path with deterministic `uaa-safe-local` responses and no provider call, tool execution, memory write, context injection, external network, raw prompt logging, dependency, or production authority.",
                    "M151 local OpenWebUI test shell contracts are missing, unsafe, not disabled by default, not localhost-only, or imply provider/model/tool/memory/context/network/raw-prompt/dependency/production authority.",
                    "critical",
                ),
        build(
                    "m151_local_openwebui_test_shell_route_boundary",
                    "M151 Local OpenWebUI Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m151_local_openwebui_test_shell_route_boundary",
                    "M151 exposes only `GET /v1/models` and `POST /v1/chat/completions` for local OpenWebUI smoke testing, while preserving blocked production markers and forbidden runtime route denial.",
                    "M151 route boundary is missing the local smoke endpoints or exposes OpenWebUI/provider/tool/memory/context/execution production authority.",
                    "critical",
                ),
        build(
                    "m151_local_openwebui_test_shell_launcher",
                    "M151 Local OpenWebUI Launcher",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m151_local_openwebui_test_shell_launcher",
                    "The developer launcher provides explicit `uaa openwebui doctor/start/status/logs/stop` commands, binds OpenWebUI to localhost, and keeps the UAA gateway opt-in.",
                    "The M151 launcher path is missing, binds unsafely, starts implicitly, or grants OpenWebUI authority beyond local smoke testing.",
                    "critical",
                ),
        build(
                    "m152_local_model_management_contracts",
                    "M152 Local Model Management",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m152_local_model_management_contracts",
                    "M152 defines a post-M151, contract-only, review-only, metadata-only, local-only, safe-ref-only, disabled-by-default, route-free, no-effect local model management charter for model refs, model profile refs, model artifact refs, inert Hugging Face search preview terms, injected hardware summaries, llama.cpp settings plans, deterministic injected-candidate ranking, redacted observability summaries, and future freeze refs.",
                    "M152 local model management contracts are missing, unsafe, not route-free, not disabled by default, or imply Hugging Face network search/download, llama.cpp import/server, subprocess execution, model load/call, backend routes, Control Center execute controls, dependencies, memory/context writes, or production authority.",
                    "critical",
                ),
        build(
                    "m152_local_model_management_static_safety",
                    "M152 Local Model Management Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m152_local_model_management_static_safety",
                    "M152 source contains no live Hugging Face client, llama.cpp import/server, model download/load/call, subprocess, network client, dependency, backend route addition, Control Center execute control, memory/context write, or production-authority fragments.",
                    "M152 source contains forbidden live local model management runtime, network, subprocess, download, llama.cpp, Hugging Face client, model call, route, Control Center execute, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m152_local_model_management_route_boundary",
                    "M152 Local Model Management Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m152_local_model_management_route_boundary",
                    "M152 adds no model management, Hugging Face search, model download/load/unload/delete, llama.cpp server, provider call, model call, runtime execution, or Control Center execute routes; only the pre-existing M151 local smoke gateway remains allowed.",
                    "M152 route boundary drifted or exposed local model management, Hugging Face search, model download/load/unload/delete, llama.cpp server, provider call, model call, runtime execution, or Control Center execute authority.",
                    "critical",
                ),
        build(
                    "m153_m165_local_model_management_progression",
                    "M153-M165 Local Model Management Progression",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m153_m165_local_model_management_progression",
                    "M153-M165 are recorded as one local model management progression: M153-M159 safe_contract checkpoints, M160-M161 live_bounded_read_only metadata checkpoints, M162 live_exact_approved_acquisition, M163 live_llama_cpp_supervisor, M164 live_openai_gateway, and M165 live_settings_tuning, all contract-first, route-free, no-effect at the progression layer, and denied from unapproved downloads, unsafe subprocess/process execution, non-loopback llama.cpp server, unsafe prompt processing, unsafe model calls, unapproved settings apply/restart, backend authority routes, Control Center execute controls, dependencies, memory/context/tool authority, and production authority.",
                    "M153-M165 local model management progression contracts are missing, unsafe, not exact-bound, not lane-bound, not route-free, or imply unapproved downloads, subprocess/process execution, llama.cpp import/server, prompt processing, model calls, settings apply/restart, backend routes, Control Center execute controls, dependencies, memory/context/tool authority, or production authority.",
                    "critical",
                ),
        build(
                    "m160_bounded_hf_gguf_search_static_safety",
                    "M160 Bounded Hugging Face GGUF Search",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m160_bounded_hf_gguf_search_static_safety",
                    "M160 permits exactly one core-only, stdlib-only, bounded, unauthenticated, HTTPS GET Hugging Face GGUF metadata search adapter with safe structured results, while preserving no downloads, no auth/token/cookie handling, no raw response storage, no model card storage, no model/provider call, no subprocess, no llama.cpp, no routes, no Control Center controls, no dependencies, no memory/context/tool authority, and no production authority.",
                    "M160 bounded Hugging Face GGUF search is missing, unsafe, not bounded, uses forbidden SDK/dependency/auth/download/model/runtime behavior, exposes raw data, adds routes or controls, or grants production authority.",
                    "critical",
                ),
        build(
                    "m161_local_system_probe_static_safety",
                    "M161 Local System Capability Probe",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m161_local_system_probe_static_safety",
                    "M161 permits exactly one core-only, stdlib-only, local read-only, redacted bucket probe for OS/arch, CPU, RAM, VRAM if safely available, backend/device family, disk budget, and power/thermal hints, while preserving no serials, usernames, raw paths, environment dumps, broad scans, subprocesses, network, downloads, model/provider calls, routes, Control Center controls, dependencies, or production authority.",
                    "M161 local system capability probe is missing, unsafe, not bucketed/redacted, uses forbidden inventory/subprocess/network/dependency/model behavior, exposes raw host data, adds routes or controls, or grants production authority.",
                    "critical",
                ),
        build(
                    "m162_exact_approved_gguf_acquisition_static_safety",
                    "M162 Exact-Approved GGUF Acquisition",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m162_exact_approved_gguf_acquisition_static_safety",
                    "M162 permits exactly one core-only, stdlib-only, exact user-approved Hugging Face GGUF artifact acquisition adapter into a UAA-owned cache with pinned revision, exact filename, explicit shard/mmproj refs, fake transport tests, and optional env-gated live smoke, while preserving no auth by default, no token use, no raw URL/path/response storage, no model/provider calls, no llama.cpp process, no subprocess, no routes, no controls, no dependencies, and no production authority.",
                    "M162 GGUF acquisition is missing, unsafe, not exact-approved, not cache-bound, uses forbidden SDK/dependency/auth/model/runtime behavior, exposes raw paths or URLs, adds routes or controls, or grants production authority.",
                    "critical",
                ),
        build(
                    "m166_local_model_production_readiness_contracts",
                    "M166 Local Model Production Readiness Contracts",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m166_local_model_production_readiness_contracts",
                    "M166 defines an evidence-bound local model production readiness gate that grants production authority only when live install/run, OpenWebUI E2E, security review, packaging, operational rollback, and load-test evidence are all green, redacted, exact-scope-bound, revocable, replay-safe, audit-bound, rollback-bound, and blocker-free.",
                    "M166 local model production readiness contracts are missing, unsafe, not exact-bound, not evidence-bound, or fail to grant production authority only from green redacted evidence.",
                    "critical",
                ),
        build(
                    "m166_local_model_production_readiness_static_safety",
                    "M166 Local Model Production Readiness Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m166_local_model_production_readiness_static_safety",
                    "M166 source keeps production readiness route-free and dependency-free, blocks raw prompt/provider/credential/path/log exports, and permits production authority only through the typed green release gate.",
                    "M166 source contains forbidden production readiness route, raw export, dependency, or unsafe authority fragments.",
                    "critical",
                ),
        build(
                    "m166_local_model_production_readiness_route_boundary",
                    "M166 Local Model Production Readiness Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m166_local_model_production_readiness_route_boundary",
                    "M166 adds no production release-gate, go-live, deploy, rollback execution, package build, load-test run, security-scan run, or OpenWebUI E2E execution routes.",
                    "M166 route boundary drifted or exposed production release-gate, go-live, deploy, rollback execution, package, load-test, security-scan, OpenWebUI E2E, or authority routes.",
                    "critical",
                ),
        build(
                    "m167_live_model_production_hardening_contracts",
                    "M167 Live Model Production Hardening Contracts",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m167_live_model_production_hardening_contracts",
                    "M167 requires reviewed live evidence for real model matrix testing across Apple Silicon, CPU-only, low RAM, discrete GPU, and limited disk profiles, plus installer/runtime packaging, selection quality validation, tuning advisor hardening, OpenWebUI real E2E, load and soak tests, and operational controls, while inheriting production authority only from M166.",
                    "M167 live model production hardening contracts are missing, unsafe, not reviewed-live-evidence-bound, incomplete across required hardware profiles and hardening lanes, or grant new production authority.",
                    "critical",
                ),
        build(
                    "m167_live_model_production_hardening_static_safety",
                    "M167 Live Model Production Hardening Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m167_live_model_production_hardening_static_safety",
                    "M167 source keeps live hardening route-free and dependency-free, blocks raw prompt/provider/credential/path/log exports, blocks report-triggered downloads/runtime execution, and permits no new authority beyond the M166 gate.",
                    "M167 source contains forbidden live hardening routes, raw export, dependency, runtime execution, download, or unsafe authority fragments.",
                    "critical",
                ),
        build(
                    "m167_live_model_production_hardening_route_boundary",
                    "M167 Live Model Production Hardening Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m167_live_model_production_hardening_route_boundary",
                    "M167 adds no live model hardening, model matrix, llama-server install/update, selection calibration, tuning apply, load soak, OpenWebUI E2E, or authority routes.",
                    "M167 route boundary drifted or exposed live model hardening, model matrix, llama-server install/update, selection calibration, tuning apply, load soak, OpenWebUI E2E, or authority routes.",
                    "critical",
                ),
    ]
