from __future__ import annotations

from typing import Any, Callable

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


def criteria(build: Callable[..., Any]) -> list[Any]:
    return [
        build(
                    "api_manifest_endpoint_present",
                    "API Manifest Endpoint Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_api_manifest_endpoint_present",
                    "/api/manifest exposes typed metadata for the current API boundary.",
                    "API manifest endpoint is missing or invalid.",
                ),
        build(
                    "openapi_contract_valid",
                    "OpenAPI Contract Valid",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_openapi_contract_valid",
                    "OpenAPI generation succeeds, matches the active version, and route inventory is valid.",
                    "OpenAPI contract verification failed.",
                    "critical",
                ),
        build(
                    "api_operation_ids_unique",
                    "API Operation IDs Unique",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_api_operation_ids_unique",
                    "All API routes have unique stable operation IDs.",
                    "API operation IDs are missing or duplicated.",
                    "critical",
                ),
        build(
                    "forbidden_runtime_routes_absent",
                    "Forbidden Runtime Routes Absent",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_forbidden_runtime_routes_absent",
                    "API boundary exposes no runtime model-call, provider-call, web-fetch, browser, scanner, or tool-execution routes.",
                    "Forbidden runtime route was detected.",
                    "critical",
                ),
        build(
                    "agents_md_guidance_present",
                    "AGENTS Guidance Present",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_agents_md_guidance_present",
                    "AGENTS.md and API boundary docs define workspace and API contract standards.",
                    "AGENTS.md or API boundary documentation is missing.",
                ),
        build(
                    "runtime_agent_config_loading_absent",
                    "Runtime Agent Config Loading Absent",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_runtime_agent_config_loading_absent",
                    "Runtime source does not load AGENTS.md, agent config files, or workspace config at request time.",
                    "Runtime agent configuration loading was detected.",
                    "critical",
                ),
        build(
                    "m8_model_runtime_files_present",
                    "M8 Model Runtime Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m8_model_runtime_files_present",
                    "M8 simulated model runtime contracts, validation, simulator, and adapter modules exist.",
                    "Required M8 model runtime files are missing.",
                ),
        build(
                    "m8_runtime_kinds_stub_only",
                    "M8 Runtime Kinds Stub Only",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m8_runtime_kinds_stub_only",
                    "Model runtime adapter kinds are limited to simulated and stub variants.",
                    "A non-stub model runtime kind was detected.",
                    "critical",
                ),
        build(
                    "m8_model_runtime_no_real_calls",
                    "M8 Model Runtime No Real Calls",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m8_model_runtime_no_real_calls",
                    "Model runtime source has no provider SDK, network, tokenizer, billing, shell, or live runtime call path.",
                    "A real model/runtime integration was detected in M8 source.",
                    "critical",
                ),
        build(
                    "m8_simulation_endpoint_safe",
                    "M8 Simulation Endpoint Safe",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m8_simulation_endpoint_safe",
                    "/model-runtime/simulate exists and is explicitly simulated.",
                    "The M8 simulation endpoint is missing or unsafe.",
                    "critical",
                ),
        build(
                    "m8_runtime_responses_simulated_only",
                    "M8 Runtime Responses Simulated Only",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m8_runtime_responses_simulated_only",
                    "Model runtime responses are marked simulated and are not truth authority.",
                    "A model runtime response was not clearly simulated.",
                    "critical",
                ),
        build(
                    "m8_runtime_secret_prompt_blocked",
                    "M8 Runtime Secret Prompt Blocked",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m8_runtime_secret_prompt_blocked",
                    "Secret-like prompt summaries are rejected before simulation.",
                    "Secret-like runtime prompt content was accepted.",
                    "critical",
                ),
        build(
                    "m8_api_validation_secret_echo_absent",
                    "M8 API Validation Secret Echo Absent",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m8_api_validation_secret_echo_absent",
                    "M8 API validation errors do not echo secret-like manifest or request payload values.",
                    "M8 API validation errors echoed secret-like input.",
                    "critical",
                ),
        build(
                    "m85_approval_authority_files_present",
                    "M8.5 Approval Authority Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m85_approval_authority_files_present",
                    "M8.5 approval request, grant, validation, authority, policy, and receipt modules exist.",
                    "Required M8.5 approval authority files are missing.",
                    "critical",
                ),
        build(
                    "m85_arbitrary_approval_refs_rejected",
                    "M8.5 Arbitrary Approval Refs Rejected",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_arbitrary_approval_refs_rejected",
                    "LocalApprovalAuthority rejects arbitrary approval_ref strings.",
                    "An arbitrary approval_ref was accepted as authority.",
                    "critical",
                ),
        build(
                    "m85_local_approval_grant_validates",
                    "M8.5 Local Approval Grant Validates",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_local_approval_grant_validates",
                    "A scoped LocalApprovalAuthority grant validates for its exact subject/action/resource.",
                    "A valid local/dev approval grant did not validate.",
                    "critical",
                ),
        build(
                    "m85_expired_revoked_approval_denies",
                    "M8.5 Expired Revoked Approval Denies",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_expired_revoked_approval_denies",
                    "Expired and revoked approval grants are denied.",
                    "Expired or revoked approval was accepted.",
                    "critical",
                ),
        build(
                    "m85_router_uses_valid_approval_grant",
                    "M8.5 Router Uses Valid Approval Grant",
                    FoundationGateCategory.model_router,
                    "FoundationGateEvaluator.check_m85_router_uses_valid_approval_grant",
                    "Model Router can use a valid local/dev approval grant for sensitive cloud route metadata decisions.",
                    "Model Router did not honor a valid approval grant.",
                    "critical",
                ),
        build(
                    "m85_runtime_factory_rejects_arbitrary_approval",
                    "M8.5 Runtime Factory Rejects Arbitrary Approval",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_runtime_factory_rejects_arbitrary_approval",
                    "Model runtime request factory rejects non-test approval refs without a validated approval decision.",
                    "Model runtime factory accepted an arbitrary approval ref.",
                    "critical",
                ),
        build(
                    "m85_tool_broker_rejects_arbitrary_approval",
                    "M8.5 Tool Broker Rejects Arbitrary Approval",
                    FoundationGateCategory.tool_broker,
                    "FoundationGateEvaluator.check_m85_tool_broker_rejects_arbitrary_approval",
                    "Tool Broker keeps high-risk actions approval-required for arbitrary approval refs.",
                    "Tool Broker accepted an arbitrary approval ref.",
                    "critical",
                ),
        build(
                    "m85_no_real_auth_oauth_network",
                    "M8.5 No Real Auth OAuth Network",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_no_real_auth_oauth_network",
                    "Approval authority source has no production auth, OAuth, network, provider SDK, or persistence imports.",
                    "M8.5 added real auth, OAuth, network, or persistence code.",
                    "critical",
                ),
        build(
                    "m85_approval_api_secret_echo_absent",
                    "M8.5 Approval API Secret Echo Absent",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m85_approval_api_secret_echo_absent",
                    "Approval API validation errors do not echo secret-like payload values.",
                    "Approval API validation echoed secret-like input.",
                    "critical",
                ),
        build(
                    "m9_loopback_runtime_files_present",
                    "M9 Loopback Runtime Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m9_loopback_runtime_files_present",
                    "M9 loopback endpoint, policy, transport, and local adapter files exist.",
                    "Required M9 loopback runtime files are missing.",
                    "critical",
                ),
        build(
                    "m9_non_loopback_endpoints_denied",
                    "M9 Non Loopback Endpoints Denied",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_non_loopback_endpoints_denied",
                    "Remote hosts, URL credentials, and secret-like query parameters are denied.",
                    "A non-loopback or credential-bearing endpoint was accepted.",
                    "critical",
                ),
        build(
                    "m9_non_loopback_policy_override_denied",
                    "M9 Non Loopback Policy Override Denied",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_non_loopback_policy_override_denied",
                    "Caller-supplied allowed_hosts and deny_non_loopback=false cannot authorize remote hosts.",
                    "A caller policy override authorized a non-loopback endpoint.",
                    "critical",
                ),
        build(
                    "m9_loopback_policy_model_rejects_hostile_inputs",
                    "M9 Loopback Policy Model Rejects Hostile Inputs",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_loopback_policy_model_rejects_hostile_inputs",
                    "LoopbackRuntimePolicy rejects deny_non_loopback=false and non-loopback allowed_hosts.",
                    "Loopback runtime policy accepted a hostile weakening input.",
                    "critical",
                ),
        build(
                    "m9_public_and_private_ip_endpoints_denied",
                    "M9 Public And Private IP Endpoints Denied",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_public_and_private_ip_endpoints_denied",
                    "Private LAN and public IP endpoints are denied by loopback endpoint validation.",
                    "A private LAN or public IP endpoint was accepted.",
                    "critical",
                ),
        build(
                    "m9_approval_api_uses_public_authority_helper",
                    "M9 Approval API Uses Public Authority Helper",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_approval_api_uses_public_authority_helper",
                    "Approval API loads validation grants through a public LocalApprovalAuthority helper.",
                    "Approval API mutates LocalApprovalAuthority private grant state directly.",
                    "critical",
                ),
        build(
                    "m9_arbitrary_approval_refs_denied",
                    "M9 Arbitrary Approval Refs Denied",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_arbitrary_approval_refs_denied",
                    "Arbitrary approval_ref strings cannot authorize local loopback execution.",
                    "An arbitrary approval_ref authorized local loopback execution.",
                    "critical",
                ),
        build(
                    "m9_fake_transport_only_in_gate",
                    "M9 Fake Transport Only In Gate",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m9_fake_transport_only_in_gate",
                    "Foundation Gate uses fake transport only and M9 runtime code has no requests/httpx/provider SDK/tokenizer/billing imports.",
                    "M9 introduced a real provider, network, tokenizer, billing, or gate transport path.",
                    "critical",
                ),
        build(
                    "m9_simulated_fallback_available",
                    "M9 Simulated Fallback Available",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m9_simulated_fallback_available",
                    "Blocked local loopback execution returns simulated fallback when policy requires it.",
                    "M9 simulated fallback is unavailable.",
                    "critical",
                ),
        build(
                    "m9_model_output_not_truth_authority",
                    "M9 Model Output Not Truth Authority",
                    FoundationGateCategory.truth,
                    "FoundationGateEvaluator.check_m9_model_output_not_truth_authority",
                    "Local loopback and fallback responses are marked non-authoritative.",
                    "M9 model output was treated as truth authority.",
                    "critical",
                ),
        build(
                    "m10_manual_smoke_files_present",
                    "M10 Manual Smoke Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m10_manual_smoke_files_present",
                    "Manual local loopback smoke policy, transport, script, and tests exist.",
                    "Required M10 manual smoke files are missing.",
                    "critical",
                ),
        build(
                    "m10_stdlib_network_isolated",
                    "M10 Stdlib Network Isolated",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m10_stdlib_network_isolated",
                    "Stdlib network import is isolated to the manual loopback smoke transport.",
                    "M10 introduced broad runtime network or provider imports.",
                    "critical",
                ),
        build(
                    "m10_gate_and_verify_do_not_call_smoke_script",
                    "M10 Gate And Verify Do Not Call Smoke Script",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m10_gate_and_verify_do_not_call_smoke_script",
                    "Foundation Gate and verify_all do not invoke the manual smoke script.",
                    "Gate or verification invokes manual local loopback smoke execution.",
                    "critical",
                ),
        build(
                    "m10_public_api_has_no_smoke_execute_endpoint",
                    "M10 Public API Has No Smoke Execute Endpoint",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m10_public_api_has_no_smoke_execute_endpoint",
                    "Public API exposes smoke validation only and no smoke execute endpoint.",
                    "Public API exposes a real local loopback smoke execution route.",
                    "critical",
                ),
        build(
                    "m10_fixed_prompt_and_loopback_policy_enforced",
                    "M10 Fixed Prompt And Loopback Policy Enforced",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m10_fixed_prompt_and_loopback_policy_enforced",
                    "Manual smoke rejects arbitrary prompts and non-loopback endpoints.",
                    "Manual smoke accepted arbitrary prompt content or a non-loopback endpoint.",
                    "critical",
                ),
        build(
                    "m10_smoke_approval_required",
                    "M10 Smoke Approval Required",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m10_smoke_approval_required",
                    "Manual smoke requires a scoped valid local approval decision.",
                    "Manual smoke permitted missing or arbitrary approval refs.",
                    "critical",
                ),
        build(
                    "m10_smoke_response_not_truth_authority",
                    "M10 Smoke Response Not Truth Authority",
                    FoundationGateCategory.truth,
                    "FoundationGateEvaluator.check_m10_smoke_response_not_truth_authority",
                    "Manual smoke responses are marked non-authoritative and omit prompt content.",
                    "Manual smoke response was treated as truth authority or leaked prompt content.",
                    "critical",
                ),
        build(
                    "m105_remote_worker_files_present",
                    "M10.5 Remote Worker Files Present",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m105_remote_worker_files_present",
                    "Remote worker foundation schemas, policies, registries, dry-run code, and tests exist.",
                    "Required M10.5 remote worker foundation files are missing.",
                    "critical",
                ),
        build(
                    "m105_remote_capabilities_default_safe",
                    "M10.5 Remote Capabilities Default Safe",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_remote_capabilities_default_safe",
                    "Remote worker risky capabilities default false and cannot approve actions or run critical work.",
                    "Remote worker risky capabilities default unsafe or permit remote approval.",
                    "critical",
                ),
        build(
                    "m105_unknown_node_and_transport_denied",
                    "M10.5 Unknown Node And Transport Denied",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_unknown_node_and_transport_denied",
                    "Unknown remote nodes and transports are denied.",
                    "Unknown remote node or transport was accepted.",
                    "critical",
                ),
        build(
                    "m105_planned_transports_disabled",
                    "M10.5 Planned Transports Disabled",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_planned_transports_disabled",
                    "Planned tailnet and LAN transports remain disabled and metadata-only.",
                    "A planned remote transport was enabled.",
                    "critical",
                ),
        build(
                    "m105_dry_run_dispatches_nothing",
                    "M10.5 Dry Run Dispatches Nothing",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_dry_run_dispatches_nothing",
                    "Remote worker dry-runs create inert results with no job transfer, tool call, network connection, or subagent launch.",
                    "Remote worker dry-run performed a forbidden action.",
                    "critical",
                ),
        build(
                    "m105_no_remote_network_or_background_execution",
                    "M10.5 No Remote Network Or Background Execution",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_no_remote_network_or_background_execution",
                    "Remote worker source contains no live network, process, listener, scheduler, or background runtime imports.",
                    "Remote worker source contains live network or background execution code.",
                    "critical",
                ),
        build(
                    "m105_no_remote_subagents_tools_or_approvals",
                    "M10.5 No Remote Subagents Tools Or Approvals",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_no_remote_subagents_tools_or_approvals",
                    "Remote workers cannot launch subagents, execute tools, or approve actions.",
                    "Remote worker policy permits subagents, tool execution, or approval.",
                    "critical",
                ),
        build(
                    "m105_remote_output_untrusted",
                    "M10.5 Remote Output Untrusted",
                    FoundationGateCategory.truth,
                    "FoundationGateEvaluator.check_m105_remote_output_untrusted",
                    "Remote dry-run output is marked untrusted and never treated as control authority.",
                    "Remote worker output was treated as trusted authority.",
                    "critical",
                ),
        build(
                    "m105_api_routes_are_dry_run_only",
                    "M10.5 API Routes Are Dry Run Only",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m105_api_routes_are_dry_run_only",
                    "Remote worker API exposes status, validation, and dry-run routes only.",
                    "Remote worker API exposes a live execution route.",
                    "critical",
                ),
        build(
                    "m105_docs_foundation_only",
                    "M10.5 Docs Foundation Only",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m105_docs_foundation_only",
                    "Release docs state M10.5 is foundation-only with no live remote networking or execution.",
                    "M10.5 docs are missing or imply live remote execution.",
                    "critical",
                ),
        build(
                    "m105_remote_tailnet_enable_flag_rejected",
                    "M10.5 Remote Tailnet Enable Flag Rejected",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_remote_tailnet_enable_flag_rejected",
                    "Remote worker policy rejects remote_tailnet_enabled=true as unsupported in M10.5.",
                    "Remote worker policy accepted remote_tailnet_enabled=true as supported.",
                    "critical",
                ),
        build(
                    "m105_remote_personal_data_enable_flag_rejected",
                    "M10.5 Remote Personal Data Enable Flag Rejected",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_remote_personal_data_enable_flag_rejected",
                    "Remote worker policy rejects remote_personal_data_enabled=true as unsupported in M10.5.",
                    "Remote worker policy accepted remote_personal_data_enabled=true as supported.",
                    "critical",
                ),
        build(
                    "m105_remote_worker_api_extra_fields_forbidden",
                    "M10.5 Remote Worker API Extra Fields Forbidden",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m105_remote_worker_api_extra_fields_forbidden",
                    "Remote worker API wrapper models reject unexpected top-level fields without leaking secret-like values.",
                    "Remote worker API wrapper models accepted extra fields or leaked secret-like input.",
                    "critical",
                ),
        build(
                    "m143_private_mesh_taxonomy_open_source_first",
                    "v0.14.3 Private Mesh Taxonomy Open Source First",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m143_private_mesh_taxonomy_open_source_first",
                    "Private mesh taxonomy includes planned Headscale, generic WireGuard, and Tailscale metadata with open-source-first selection policy.",
                    "Private mesh taxonomy is missing open-source-first planned provider metadata.",
                    "critical",
                ),
        build(
                    "m143_planned_mesh_transports_disabled",
                    "v0.14.3 Planned Mesh Transports Disabled",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m143_planned_mesh_transports_disabled",
                    "Planned private mesh transports remain disabled, planned-only, no-network, no-credential, and no-dispatch.",
                    "A planned private mesh transport was enabled or dispatch/network capable.",
                    "critical",
                ),
        build(
                    "m143_no_live_mesh_integrations",
                    "v0.14.3 No Live Mesh Integrations",
                    FoundationGateCategory.security,
                    "FoundationGateEvaluator.check_m143_no_live_mesh_integrations",
                    "No Headscale, Tailscale, WireGuard, mesh command, private IP, auth key, node key, token, or live network integration exists.",
                    "A live private mesh integration or private transport secret marker was detected.",
                    "critical",
                ),
    ]
