from __future__ import annotations

from typing import Any, Callable

from ultimate_ai_agent.core.gate.enums import FoundationGateCategory


def criteria(build: Callable[..., Any]) -> list[Any]:
    return [
        build(
                    "m67_revocation_kill_switch_contract_review",
                    "M67 Revocation + Kill Switch Contract Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m67_revocation_kill_switch_contract_review",
                    "M67 revocation and kill-switch records are contract-only, review-only, exact-bound to scoped approval bundles, replay-safe, and non-authoritative.",
                    "M67 revocation/kill-switch contracts are missing, weak, or imply live activation, authority, session stop, execution, or side effects.",
                    "critical",
                ),
        build(
                    "m67_revocation_kill_switch_static_safety",
                    "M67 Revocation + Kill Switch Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m67_revocation_kill_switch_static_safety",
                    "M67 keeps revocation and kill-switch artifacts review-only and blocks activation, session stop, process kill, routes, execution, routes, dependencies, memory/context writes, model calls, and production authority.",
                    "M67 source contains revocation activation, kill-switch activation, session stop, process kill, route, execution, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m67_revocation_kill_switch_route_boundary",
                    "M67 Revocation + Kill Switch Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m67_revocation_kill_switch_route_boundary",
                    "M67 adds no revocation, kill-switch, session-stop, process-kill, autonomy activation, context, memory, tool, shell, browser, plugin, network, background-worker, raw-file, or execution backend routes.",
                    "M67 route boundary drifted or exposed revocation, kill-switch, session-stop, execution, network, background-worker, or production authority.",
                    "critical",
                ),
        build(
                    "m67_roadmap_currentness",
                    "M67 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m67_roadmap_currentness",
                    "Active roadmap docs mark v0.71.0/M67 implemented and keep M68-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.71.0/M67 or imply M68+ implementation, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m68_autonomy_risk_classifier_contract_review",
                    "M68 Autonomy Risk Classifier Contract Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m68_autonomy_risk_classifier_contract_review",
                    "M68 risk classifier contracts are deterministic, review-only, exact-bound to M66/M67 records, derive highest risk, and remain non-authoritative.",
                    "M68 risk classifier contracts are missing, weak, allow risk downgrades, or imply policy activation, authority, execution, or side effects.",
                    "critical",
                ),
        build(
                    "m68_autonomy_risk_classifier_static_safety",
                    "M68 Autonomy Risk Classifier Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m68_autonomy_risk_classifier_static_safety",
                    "M68 keeps risk classification contract-only and blocks authority, routes, policy/session activation, execution, background workers, memory/context writes, model calls, and production authority.",
                    "M68 source contains risk authority, route, activation, execution, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m68_autonomy_risk_classifier_route_boundary",
                    "M68 Autonomy Risk Classifier Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m68_autonomy_risk_classifier_route_boundary",
                    "M68 adds no risk-classification, autonomy activation, policy activation, session start, revocation, kill-switch, context, memory, tool, shell, browser, plugin, network, background-worker, raw-file, or execution backend routes.",
                    "M68 route boundary drifted or exposed classifier, autonomy activation, execution, network, background-worker, or production authority.",
                    "critical",
                ),
        build(
                    "m68_roadmap_currentness",
                    "M68 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m68_roadmap_currentness",
                    "Active roadmap docs mark v0.72.0/M68 implemented and keep M69-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.72.0/M68 or imply M69+ implementation, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m69_low_risk_autonomous_dry_run_contract_review",
                    "M69 Low-Risk Autonomous Dry Run Contract Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m69_low_risk_autonomous_dry_run_contract_review",
                    "M69 low-risk autonomous dry-run contracts are exact-bound to M68 risk decisions, review-only, dry-run-only, low-risk-only, and non-authoritative.",
                    "M69 low-risk autonomous dry-run contracts are missing, weak, accept higher risk, or imply policy activation, session start, authority, execution, or side effects.",
                    "critical",
                ),
        build(
                    "m69_low_risk_autonomous_dry_run_static_safety",
                    "M69 Low-Risk Autonomous Dry Run Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m69_low_risk_autonomous_dry_run_static_safety",
                    "M69 keeps low-risk dry runs contract-only and blocks policy/session activation, autonomous actions, background workers, execution, routes, memory/context writes, model calls, and production authority.",
                    "M69 source contains low-risk dry-run authority, route, activation, execution, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m69_low_risk_autonomous_dry_run_route_boundary",
                    "M69 Low-Risk Autonomous Dry Run Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m69_low_risk_autonomous_dry_run_route_boundary",
                    "M69 adds no dry-run start, dry-run execute, autonomy activation, policy activation, session start, context, memory, tool, shell, browser, plugin, network, background-worker, raw-file, or execution backend routes.",
                    "M69 route boundary drifted or exposed dry-run start, autonomy activation, execution, network, background-worker, or production authority.",
                    "critical",
                ),
        build(
                    "m69_roadmap_currentness",
                    "M69 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m69_roadmap_currentness",
                    "Active roadmap docs mark v0.73.0/M69 implemented and keep M70-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.73.0/M69 or imply M70+ implementation, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m70_autonomy_foundation_freeze_review",
                    "M70 Autonomy Foundation Freeze Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m70_autonomy_foundation_freeze_review",
                    "M70 freezes the accepted M61-M69 autonomy foundation as review-only, freeze-only, deterministic, and non-authoritative.",
                    "M70 autonomy foundation freeze contracts are missing, weak, or imply policy activation, session start, execution, background workers, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m70_autonomy_foundation_freeze_static_safety",
                    "M70 Autonomy Foundation Freeze Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m70_autonomy_foundation_freeze_static_safety",
                    "M70 source keeps the autonomy foundation freeze contract-only and blocks policy/session activation, autonomous actions, dry-run execution, background workers, routes, memory/context writes, model calls, and production authority.",
                    "M70 source contains autonomy foundation authority, activation, execution, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m70_autonomy_foundation_freeze_route_boundary",
                    "M70 Autonomy Foundation Freeze Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m70_autonomy_foundation_freeze_route_boundary",
                    "M70 adds no autonomy freeze activation, policy activation, session start, dry-run execution, context, memory, tool, shell, browser, plugin, network, raw-file, or execution backend routes.",
                    "M70 route boundary drifted or exposed freeze activation, autonomy activation, execution, network, background-worker, or production authority.",
                    "critical",
                ),
        build(
                    "m70_roadmap_currentness",
                    "M70 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m70_roadmap_currentness",
                    "Active roadmap docs mark v0.74.0/M70 implemented and keep M71-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.74.0/M70 or imply M71+ implementation, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m71_network_tool_contract_review",
                    "M71 Network Tool Contract Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m71_network_tool_contract_review",
                    "M71 adds contract-only, review-only network tool contract review with allowlisted read-only HTTP fetch as an M72 candidate only.",
                    "M71 network tool contract review is missing, weak, or implies network calls, HTTP fetch execution, routes, dependencies, Control Center controls, or production authority.",
                    "critical",
                ),
        build(
                    "m71_network_tool_contract_static_safety",
                    "M71 Network Tool Contract Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m71_network_tool_contract_static_safety",
                    "M71 source keeps network tools disabled by default and blocks HTTP fetch, unrestricted/authenticated network actions, credentials/cookies, raw responses, browser automation, model calls, tool execution, routes, dependencies, and production authority.",
                    "M71 source contains network execution, route, credential, raw-response, browser, model, tool, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m71_network_tool_contract_route_boundary",
                    "M71 Network Tool Contract Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m71_network_tool_contract_route_boundary",
                    "M71 adds no network fetch/request, HTTP fetch/request, tool execution, browser, plugin, memory, context, or execution backend routes.",
                    "M71 route boundary drifted or exposed network/runtime execution, browser/plugin execution, context injection, memory write, or production authority.",
                    "critical",
                ),
        build(
                    "m71_roadmap_currentness",
                    "M71 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m71_roadmap_currentness",
                    "Active roadmap docs mark v0.75.0/M71 implemented and keep M72-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.75.0/M71 or imply M72+ implementation, production authority, unrestricted network tools, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m72_read_only_http_fetch_tool",
                    "M72 Read-Only HTTP Fetch Tool",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m72_read_only_http_fetch_tool",
                    "M72 adds a bounded allowlisted read-only HTTP fetch tool that returns only redacted previews through the tool runtime adapter.",
                    "M72 read-only HTTP fetch tool is missing, weak, not allowlisted, not redacted-first, or implies unrestricted/authenticated network authority.",
                    "critical",
                ),
        build(
                    "m72_read_only_http_fetch_static_safety",
                    "M72 Read-Only HTTP Fetch Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m72_read_only_http_fetch_static_safety",
                    "M72 source allows only the named read-only HTTP fetch tool and blocks credentials, cookies, request bodies, non-GET methods, raw responses, downloads, context injection, memory writes, model calls, browser automation, routes, dependencies, and production authority.",
                    "M72 source contains broad network execution, route, credential, raw-response, browser, model, tool, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m72_read_only_http_fetch_route_boundary",
                    "M72 Read-Only HTTP Fetch Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m72_read_only_http_fetch_route_boundary",
                    "M72 adds no network fetch/request, HTTP fetch/request, tool execution, browser, plugin, memory, context, or execution backend routes.",
                    "M72 route boundary drifted or exposed network/runtime execution, browser/plugin execution, context injection, memory write, or production authority.",
                    "critical",
                ),
        build(
                    "m72_roadmap_currentness",
                    "M72 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m72_roadmap_currentness",
                    "Active roadmap docs mark v0.76.0/M72 implemented and keep M73-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.76.0/M72 or imply M73+ implementation, production authority, unrestricted network tools, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m73_browser_automation_contract_review",
                    "M73 Browser Automation Contract Review",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m73_browser_automation_contract_review",
                    "M73 adds contract-only, review-only browser automation contract review with observe-only adapter as an M74 candidate only.",
                    "M73 browser automation contract review is missing, weak, or implies browser runtime, navigation, click, profile access, routes, dependencies, Control Center controls, or production authority.",
                    "critical",
                ),
        build(
                    "m73_browser_automation_contract_static_safety",
                    "M73 Browser Automation Contract Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m73_browser_automation_contract_static_safety",
                    "M73 source keeps browser automation disabled by default and blocks observe, navigation, clicks, form fill, screenshots, DOM reads, authenticated profiles, downloads/uploads, remote browser control, network interception, routes, dependencies, and production authority.",
                    "M73 source contains browser runtime, profile, screenshot, DOM, route, dependency, execution, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m73_browser_automation_contract_route_boundary",
                    "M73 Browser Automation Contract Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m73_browser_automation_contract_route_boundary",
                    "M73 adds no browser observe, click, navigation, screenshot, session, tool execution, network, memory, context, or execution backend routes.",
                    "M73 route boundary drifted or exposed browser runtime, tool execution, context injection, memory write, network expansion, or production authority.",
                    "critical",
                ),
        build(
                    "m73_roadmap_currentness",
                    "M73 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m73_roadmap_currentness",
                    "Active roadmap docs mark v0.77.0/M73 implemented and keep M74-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.77.0/M73 or imply M74+ implementation, browser execution, production authority, unrestricted network tools, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m74_browser_observe_only_adapter",
                    "M74 Browser Observe-Only Adapter",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m74_browser_observe_only_adapter",
                    "M74 adds an injected-observation browser observe-only adapter that returns redacted visible text and safe refs only.",
                    "M74 browser observe-only adapter is missing, weak, unredacted, or implies browser control, routes, profile access, network interception, execution, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m74_browser_observe_only_static_safety",
                    "M74 Browser Observe-Only Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m74_browser_observe_only_static_safety",
                    "M74 source allows only local observe-only output and blocks navigation, clicks, form fill, screenshots, raw DOM, authenticated profiles, downloads/uploads, remote browser control, network interception, routes, dependencies, and production authority.",
                    "M74 source contains browser control, raw DOM/screenshot/profile, route, dependency, execution, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m74_browser_observe_only_route_boundary",
                    "M74 Browser Observe-Only Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m74_browser_observe_only_route_boundary",
                    "M74 adds no browser observe, click, navigation, screenshot, session, tool execution, network, memory, context, or execution backend routes.",
                    "M74 route boundary drifted or exposed browser observe/control, tool execution, context injection, memory write, network expansion, or production authority.",
                    "critical",
                ),
        build(
                    "m74_roadmap_currentness",
                    "M74 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m74_roadmap_currentness",
                    "Active roadmap docs mark v0.78.0/M74 implemented and keep M75-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.78.0/M74 or imply M75+ implementation, browser execution, production authority, unrestricted network tools, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m75_browser_action_dry_run_planner",
                    "M75 Browser Action Dry-Run Planner",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m75_browser_action_dry_run_planner",
                    "M75 adds a deterministic browser action dry-run planner that produces reviewable action plans without browser execution.",
                    "M75 browser action dry-run planner is missing, weak, or implies browser execution, profile access, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m75_browser_action_dry_run_static_safety",
                    "M75 Browser Action Dry-Run Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m75_browser_action_dry_run_static_safety",
                    "M75 source allows only dry-run browser action planning and blocks action execution, browser sessions, screenshots, raw DOM, routes, dependencies, and production authority.",
                    "M75 source contains browser action execution, browser session, raw DOM/screenshot/profile, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m75_browser_action_dry_run_route_boundary",
                    "M75 Browser Action Dry-Run Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m75_browser_action_dry_run_route_boundary",
                    "M75 adds no browser action planner, browser action execution, click, navigation, screenshot, tool execution, network, memory, context, or execution backend routes.",
                    "M75 route boundary drifted or exposed browser action planning/execution, tool execution, context injection, memory write, network expansion, or production authority.",
                    "critical",
                ),
        build(
                    "m75_roadmap_currentness",
                    "M75 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m75_roadmap_currentness",
                    "Active roadmap docs mark v0.79.0/M75 implemented and keep M76-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.79.0/M75 or imply M76+ implementation, browser execution, production authority, unrestricted network tools, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m76_openwebui_runtime_bridge_v1",
                    "M76 OpenWebUI Runtime Bridge v1",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m76_openwebui_runtime_bridge_v1",
                    "M76 adds a review-only OpenWebUI runtime bridge v1 envelope over safe refs without live OpenWebUI calls, model/provider calls, raw payloads, memory writes, context injection, tool execution, routes, dependencies, or production authority.",
                    "M76 OpenWebUI runtime bridge v1 is missing, weak, or implies runtime calls, authority bypass, raw prompt/provider payload exposure, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m76_openwebui_runtime_bridge_static_safety",
                    "M76 OpenWebUI Runtime Bridge Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m76_openwebui_runtime_bridge_static_safety",
                    "M76 source allows only review-only OpenWebUI bridge envelope planning and blocks OpenWebUI runtime calls, provider/model calls, tool execution, memory writes, context injection, credentials/cookies, raw payloads, routes, dependencies, and production authority.",
                    "M76 source contains OpenWebUI runtime call, provider/model call, tool execution, memory write, context injection, credential/cookie, raw payload, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m76_openwebui_runtime_bridge_route_boundary",
                    "M76 OpenWebUI Runtime Bridge Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m76_openwebui_runtime_bridge_route_boundary",
                    "M76 adds no OpenWebUI runtime bridge, handoff, chat send, model/provider, tool execution, memory write, context injection, raw payload, or execution backend routes.",
                    "M76 route boundary drifted or exposed OpenWebUI runtime bridge/handoff, chat send, model/provider calls, tool execution, context injection, memory write, raw payload, or production authority.",
                    "critical",
                ),
        build(
                    "m76_roadmap_currentness",
                    "M76 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m76_roadmap_currentness",
                    "Active roadmap docs mark v0.80.0/M76 implemented and keep M77-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.80.0/M76 or imply M77+ implementation, OpenWebUI handoff execution, model/provider authority, tool execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m77_openwebui_safe_handoff_execution",
                    "M77 OpenWebUI Safe Handoff Execution",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m77_openwebui_safe_handoff_execution",
                    "M77 adds exact-bound OpenWebUI safe handoff execution inside Agent Core without live OpenWebUI calls, model/provider calls, raw payloads, memory writes, context injection, tool execution, backend routes, dependencies, or production authority.",
                    "M77 OpenWebUI safe handoff execution is missing, weak, or implies runtime calls, authority bypass, raw prompt/provider payload exposure, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m77_openwebui_safe_handoff_static_safety",
                    "M77 OpenWebUI Safe Handoff Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m77_openwebui_safe_handoff_static_safety",
                    "M77 source allows only exact-bound Agent Core safe handoff records and blocks OpenWebUI runtime calls, provider/model calls, tool execution, memory writes, context injection, credentials/cookies, raw payloads, routes, dependencies, and production authority.",
                    "M77 source contains OpenWebUI runtime call, provider/model call, tool execution, memory write, context injection, credential/cookie, raw payload, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m77_openwebui_safe_handoff_route_boundary",
                    "M77 OpenWebUI Safe Handoff Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m77_openwebui_safe_handoff_route_boundary",
                    "M77 adds no OpenWebUI handoff, chat send, model/provider, tool execution, memory write, context injection, raw payload, or execution backend routes.",
                    "M77 route boundary drifted or exposed OpenWebUI handoff, chat send, model/provider calls, tool execution, context injection, memory write, raw payload, or production authority.",
                    "critical",
                ),
        build(
                    "m77_roadmap_currentness",
                    "M77 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m77_roadmap_currentness",
                    "Active roadmap docs mark v0.81.0/M77 implemented and keep M78-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.81.0/M77 or imply M78+ implementation, OpenWebUI runtime calls, model/provider authority, tool execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m78_plugin_manifest_security_model",
                    "M78 Plugin Manifest Security Model",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m78_plugin_manifest_security_model",
                    "M78 adds plugin manifest security model contracts that require source/provenance, declared permissions, static review, sandbox test plans, Tool Broker mapping, Event Ledger logging, version pinning, revocation, and high-risk human approval while keeping plugins disabled.",
                    "M78 plugin manifest security model is missing, weak, or implies plugin installation, enablement, execution, runtime import, dependencies, routes, or production authority.",
                    "critical",
                ),
        build(
                    "m78_plugin_manifest_static_safety",
                    "M78 Plugin Manifest Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m78_plugin_manifest_static_safety",
                    "M78 source allows only plugin manifest security review contracts and blocks plugin installation, enablement, execution, runtime imports, network/model/browser/shell/mobile/remote access, credentials/cookies, raw payload exposure, dependencies, and production authority.",
                    "M78 source contains plugin runtime, install, enablement, execution, credential, raw payload, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m78_plugin_manifest_route_boundary",
                    "M78 Plugin Manifest Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m78_plugin_manifest_route_boundary",
                    "M78 adds no plugin install, enablement, execution, permission-grant, runtime import, tool execution, context injection, memory write, shell, or backend routes.",
                    "M78 route boundary drifted or exposed plugin install/enable/execute, tool execution, context injection, memory write, shell, or production authority.",
                    "critical",
                ),
        build(
                    "m78_roadmap_currentness",
                    "M78 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m78_roadmap_currentness",
                    "Active roadmap docs mark v0.82.0/M78 implemented and keep M79-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.82.0/M78 or imply M79+ implementation, plugin install/enable/execute, shell execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m79_plugin_install_review",
                    "M79 Plugin Install Review Disabled By Default",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m79_plugin_install_review",
                    "M79 adds exact-bound plugin install review contracts layered on the M78 manifest security decision while keeping plugin install, enablement, execution, runtime import, routes, dependencies, and production authority disabled.",
                    "M79 plugin install review is missing, weak, or implies plugin installation, enablement, execution, runtime import, dependencies, routes, or production authority.",
                    "critical",
                ),
        build(
                    "m79_plugin_install_static_safety",
                    "M79 Plugin Install Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m79_plugin_install_static_safety",
                    "M79 source allows only plugin install review contracts and blocks plugin installation, enablement, execution, runtime imports, network/model/browser/shell/mobile/remote access, credentials/cookies, raw payload exposure, dependencies, and production authority.",
                    "M79 source contains plugin runtime, install, enablement, execution, credential, raw payload, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m79_plugin_install_route_boundary",
                    "M79 Plugin Install Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m79_plugin_install_route_boundary",
                    "M79 adds no plugin install, install-review submission, enablement, execution, permission-grant, runtime import, tool execution, context injection, memory write, shell, or backend routes.",
                    "M79 route boundary drifted or exposed plugin install/review/enable/execute, tool execution, context injection, memory write, shell, or production authority.",
                    "critical",
                ),
        build(
                    "m79_roadmap_currentness",
                    "M79 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m79_roadmap_currentness",
                    "Active roadmap docs mark v0.83.0/M79 implemented and keep M80-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.83.0/M79 or imply M80+ implementation, plugin install/enable/execute, shell execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m80_network_browser_openwebui_hardening_freeze_review",
                    "M80 Network/Browser/OpenWebUI Hardening Freeze",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m80_network_browser_openwebui_hardening_freeze_review",
                    "M80 freezes accepted M71-M79 network, browser, OpenWebUI, and plugin-adjacent review boundaries without adding runtime authority.",
                    "M80 hardening freeze is missing, weak, or implies unrestricted network access, browser action execution, OpenWebUI authority, plugin runtime behavior, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m80_network_browser_openwebui_hardening_freeze_static_safety",
                    "M80 Network/Browser/OpenWebUI Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m80_network_browser_openwebui_hardening_freeze_static_safety",
                    "M80 source allows only freeze contracts and blocks unrestricted network, browser action execution, OpenWebUI authority, plugin runtime behavior, credentials/cookies, shell, background workers, routes, dependencies, and production authority.",
                    "M80 source contains network/browser/OpenWebUI/plugin runtime, credential, raw payload, route, dependency, background-worker, shell, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m80_network_browser_openwebui_hardening_freeze_route_boundary",
                    "M80 Network/Browser/OpenWebUI Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m80_network_browser_openwebui_hardening_freeze_route_boundary",
                    "M80 adds no network expansion, browser action, OpenWebUI execute/context/memory, plugin install/enable/execute, shell, or backend routes.",
                    "M80 route boundary drifted or exposed network expansion, browser action, OpenWebUI execute/context/memory, plugin install/enable/execute, shell, or production authority.",
                    "critical",
                ),
        build(
                    "m80_roadmap_currentness",
                    "M80 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m80_roadmap_currentness",
                    "Active roadmap docs mark v0.84.0/M80 implemented and keep M81-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.84.0/M80 or imply M81+ implementation, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m81_runtime_sandbox_spec_contract",
                    "M81 Runtime Sandbox Spec",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m81_runtime_sandbox_spec_contract",
                    "M81 defines runtime sandbox spec-only contracts while keeping runtime sandbox execution, command proposal, command execution, subprocess/shell/process spawn, side effects, routes, dependencies, M82, and production authority disabled.",
                    "M81 runtime sandbox spec is missing, weak, or implies runtime sandbox execution, command proposals, command execution, subprocess/shell/process spawn, routes, dependencies, M82 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m81_runtime_sandbox_spec_static_safety",
                    "M81 Runtime Sandbox Spec Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m81_runtime_sandbox_spec_static_safety",
                    "M81 source allows only spec contracts and blocks runtime sandbox execution, command proposal, command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, and production authority.",
                    "M81 source contains runtime sandbox execution, command proposal/execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m81_runtime_sandbox_spec_route_boundary",
                    "M81 Runtime Sandbox Spec Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m81_runtime_sandbox_spec_route_boundary",
                    "M81 adds no sandbox run/execute, command proposal/execute, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M81 route boundary drifted or exposed sandbox run/execute, command proposal/execute, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m81_roadmap_currentness",
                    "M81 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m81_roadmap_currentness",
                    "Active roadmap docs keep v0.85.0/M81 implemented while later command work remains contract-only and non-executing.",
                    "Active roadmap docs are stale for v0.85.0/M81 or imply command execution, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m82_command_proposal_contract",
                    "M82 Command Proposal Contracts",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m82_command_proposal_contract",
                    "M82 defines proposal-only command proposal contracts with structured argv preview, safe-summary-only receipt plans, and no command execution, subprocess, shell, process spawn, side effects, routes, dependencies, or authority.",
                    "M82 command proposal contracts are missing, weak, or imply command execution, subprocess/shell/process spawn, raw command storage, routes, dependencies, M83 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m82_command_proposal_static_safety",
                    "M82 Command Proposal Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m82_command_proposal_static_safety",
                    "M82 source allows only command proposal contracts and blocks command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command receipts, and production authority.",
                    "M82 source contains command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m82_command_proposal_route_boundary",
                    "M82 Command Proposal Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m82_command_proposal_route_boundary",
                    "M82 adds no command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M82 route boundary drifted or exposed command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m82_roadmap_currentness",
                    "M82 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m82_roadmap_currentness",
                    "Active roadmap docs mark v0.86.0/M82 implemented and keep M83-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.86.0/M82 or imply M83+ implementation, command execution, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m83_shell_dry_run_classifier_contract",
                    "M83 Shell Dry-Run Classifier",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m83_shell_dry_run_classifier_contract",
                    "M83 defines classifier-only shell dry-run classification contracts over M82 proposals with safe-summary-only receipt plans and no dry-run execution, command execution, subprocess, shell, process spawn, side effects, routes, dependencies, or authority.",
                    "M83 shell dry-run classifier contracts are missing, weak, or imply dry-run execution, command execution, subprocess/shell/process spawn, raw command storage, routes, dependencies, M84 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m83_shell_dry_run_classifier_static_safety",
                    "M83 Shell Dry-Run Classifier Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m83_shell_dry_run_classifier_static_safety",
                    "M83 source allows only shell dry-run classification contracts and blocks dry-run execution, command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command receipts, and production authority.",
                    "M83 source contains dry-run execution, command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m83_shell_dry_run_classifier_route_boundary",
                    "M83 Shell Dry-Run Classifier Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m83_shell_dry_run_classifier_route_boundary",
                    "M83 adds no shell dry-run, command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M83 route boundary drifted or exposed shell dry-run, command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m83_roadmap_currentness",
                    "M83 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m83_roadmap_currentness",
                    "Active roadmap docs mark v0.87.0/M83 implemented and keep M84-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.87.0/M83 or imply M84+ implementation, command execution, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m84_sandboxed_echo_noop_command_contract",
                    "M84 Sandboxed Echo/No-Op Command",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m84_sandboxed_echo_noop_command_contract",
                    "M84 defines in-process sandboxed echo/no-op command contracts over M83 no-effect classifications with safe-summary-only receipt plans and no command execution, subprocess, shell, process spawn, side effects, routes, dependencies, or authority.",
                    "M84 sandboxed echo/no-op contracts are missing, weak, or imply shell/subprocess/process execution, raw command/output storage, routes, dependencies, M85 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m84_sandboxed_echo_noop_static_safety",
                    "M84 Sandboxed Echo/No-Op Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m84_sandboxed_echo_noop_static_safety",
                    "M84 source allows only in-process sandboxed echo/no-op contracts and blocks command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/output receipts, and production authority.",
                    "M84 source contains command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command/output receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m84_sandboxed_echo_noop_route_boundary",
                    "M84 Sandboxed Echo/No-Op Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m84_sandboxed_echo_noop_route_boundary",
                    "M84 adds no sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M84 route boundary drifted or exposed sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m84_roadmap_currentness",
                    "M84 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m84_roadmap_currentness",
                    "Active roadmap docs mark v0.88.0/M84 implemented and keep M85-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.88.0/M84 or imply M85+ implementation, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m85_read_only_command_allowlist_contract",
                    "M85 Read-Only Command Allowlist",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m85_read_only_command_allowlist_contract",
                    "M85 defines contract-only, review-only read-only command allowlist decisions over exact M84 sandboxed echo/no-op command decisions with safe-ref-only receipt plans and no command execution, subprocess, shell, process spawn, side effects, routes, dependencies, or authority.",
                    "M85 read-only command allowlist contracts are missing, weak, or imply shell/subprocess/process execution, raw command/output storage, routes, dependencies, M86 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m85_read_only_command_allowlist_static_safety",
                    "M85 Read-Only Command Allowlist Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m85_read_only_command_allowlist_static_safety",
                    "M85 source allows only read-only command allowlist contracts and blocks command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/output receipts, and production authority.",
                    "M85 source contains command execution, process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command/output receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m85_read_only_command_allowlist_route_boundary",
                    "M85 Read-Only Command Allowlist Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m85_read_only_command_allowlist_route_boundary",
                    "M85 adds no command allowlist, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M85 route boundary drifted or exposed command allowlist, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m85_roadmap_currentness",
                    "M85 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m85_roadmap_currentness",
                    "Active roadmap docs mark v0.89.0/M85 implemented and keep M86-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.89.0/M85 or imply M86+ implementation, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m86_shell_approval_gate_contract",
                    "M86 Shell Approval Gate v1",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m86_shell_approval_gate_contract",
                    "M86 defines contract-only, review-only shell approval gate decisions over exact M85 read-only command allowlist decisions and exact scoped approval bundles, with safe-ref-only receipt plans and no shell/subprocess/process/command execution, side effects, routes, dependencies, or authority.",
                    "M86 shell approval gate contracts are missing, weak, or imply shell/subprocess/process/command execution, raw command/output storage, routes, dependencies, M87 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m86_shell_approval_gate_static_safety",
                    "M86 Shell Approval Gate Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m86_shell_approval_gate_static_safety",
                    "M86 source allows only shell approval gate contracts and blocks command execution, shell/subprocess/process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/output receipts, and production authority.",
                    "M86 source contains command execution, shell/subprocess/process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command/output receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m86_shell_approval_gate_route_boundary",
                    "M86 Shell Approval Gate Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m86_shell_approval_gate_route_boundary",
                    "M86 adds no shell approval, command allowlist, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M86 route boundary drifted or exposed shell approval, command allowlist, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m86_roadmap_currentness",
                    "M86 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m86_roadmap_currentness",
                    "Active roadmap docs mark v0.90.0/M86 implemented and keep M87-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.90.0/M86 or imply M87+ implementation, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m87_sandboxed_command_audit_replay_contract",
                    "M87 Sandboxed Command Audit Replay",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m87_sandboxed_command_audit_replay_contract",
                    "M87 defines contract-only, review-only, replay-view-only sandboxed command audit replay decisions over exact M86 shell approval gate decisions, with exact replay step binding, safe-ref-only receipt plans, and no replay runner, shell/subprocess/process/command execution, side effects, routes, dependencies, or authority.",
                    "M87 sandboxed command audit replay contracts are missing, weak, or imply replay running, shell/subprocess/process/command execution, raw command/output storage, routes, dependencies, M88 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m87_sandboxed_command_audit_replay_static_safety",
                    "M87 Sandboxed Command Audit Replay Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m87_sandboxed_command_audit_replay_static_safety",
                    "M87 source allows only sandboxed command audit replay contracts and blocks replay runners, replay execution, command execution, shell/subprocess/process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/output receipts, and production authority.",
                    "M87 source contains replay runner, replay execution, command execution, shell/subprocess/process spawning, filesystem/network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command/output receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m87_sandboxed_command_audit_replay_route_boundary",
                    "M87 Sandboxed Command Audit Replay Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m87_sandboxed_command_audit_replay_route_boundary",
                    "M87 adds no shell replay, command audit replay, sandbox command replay, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M87 route boundary drifted or exposed shell replay, command audit replay, sandbox command replay, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m87_roadmap_currentness",
                    "M87 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m87_roadmap_currentness",
                    "Active roadmap docs mark v0.91.0/M87 implemented and keep M88-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.91.0/M87 or imply M88+ implementation, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m88_mutating_command_proposal_contract",
                    "M88 Mutating Command Proposal",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m88_mutating_command_proposal_contract",
                    "M88 defines contract-only, proposal-only, review-only mutating command proposal decisions over exact M87 sandboxed command audit replay decisions, with safe mutation scope refs, safe-ref-only receipt plans, and no command execution, filesystem mutation, routes, dependencies, or authority.",
                    "M88 mutating command proposal contracts are missing, weak, or imply command execution, filesystem mutation, raw command/output storage, routes, dependencies, M89 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m88_mutating_command_proposal_static_safety",
                    "M88 Mutating Command Proposal Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m88_mutating_command_proposal_static_safety",
                    "M88 source allows only mutating command proposal review contracts and blocks command execution, shell/subprocess/process spawning, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/output receipts, and production authority.",
                    "M88 source contains command execution, shell/subprocess/process spawning, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw-command/output receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m88_mutating_command_proposal_route_boundary",
                    "M88 Mutating Command Proposal Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m88_mutating_command_proposal_route_boundary",
                    "M88 adds no mutating command, sandbox command mutation, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or backend routes.",
                    "M88 route boundary drifted or exposed mutating command, sandbox command mutation, sandbox command execution, shell, process spawn, filesystem mutation, network, browser, plugin, remote, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m88_roadmap_currentness",
                    "M88 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m88_roadmap_currentness",
                    "Active roadmap docs mark v0.92.0/M88 implemented and keep M89-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.92.0/M88 or imply M89+ implementation, command execution, filesystem mutation, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m89_emergency_stop_process_kill_safety_contract",
                    "M89 Emergency Stop + Process Kill Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m89_emergency_stop_process_kill_safety_contract",
                    "M89 defines contract-only, review-only emergency stop and process kill safety decisions over exact M88 mutating command proposal decisions, with safe target refs, safe-ref-only receipt plans, and no emergency stop execution, process kill, process signal, shell/subprocess/process spawning, routes, dependencies, or authority.",
                    "M89 emergency stop/process kill safety contracts are missing, weak, or imply emergency stop execution, process kill, process signaling, shell/subprocess/process spawning, raw PID/signal storage, routes, dependencies, M90 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m89_emergency_stop_process_kill_static_safety",
                    "M89 Emergency Stop + Process Kill Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m89_emergency_stop_process_kill_static_safety",
                    "M89 source allows only emergency stop and process kill safety review contracts and blocks actual emergency stop, process kill, process signal, command execution, shell/subprocess/process spawning, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw PID/signal receipts, and production authority.",
                    "M89 source contains emergency stop execution, process kill, process signal, command execution, shell/subprocess/process spawning, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw PID/signal receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m89_emergency_stop_process_kill_route_boundary",
                    "M89 Emergency Stop + Process Kill Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m89_emergency_stop_process_kill_route_boundary",
                    "M89 adds no emergency stop, process kill, process signal, process spawn, command execution, shell, filesystem mutation, memory, context, tool, or backend routes.",
                    "M89 route boundary drifted or exposed emergency stop, process kill, process signal, process spawn, command execution, shell, filesystem mutation, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m89_roadmap_currentness",
                    "M89 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m89_roadmap_currentness",
                    "Active roadmap docs mark v0.93.0/M89 implemented and keep M90-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.93.0/M89 or imply M90+ implementation, process kill execution, shell execution, subprocess execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m90_shell_subprocess_hardening_freeze_contract",
                    "M90 Shell/Subprocess Hardening Freeze",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m90_shell_subprocess_hardening_freeze_contract",
                    "M90 defines contract-only, review-only, freeze-only shell/subprocess hardening decisions over exact M89 Emergency Stop + Process Kill Safety decisions, with safe hardening refs, safe-ref-only receipt plans, and no command, shell, subprocess, process spawn, emergency stop, process kill, process signal, routes, dependencies, or authority.",
                    "M90 shell/subprocess hardening freeze contracts are missing, weak, or imply command execution, shell/subprocess execution, process spawning, emergency stop execution, process kill/signal, raw command/shell/PID storage, routes, dependencies, M91 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m90_shell_subprocess_static_safety",
                    "M90 Shell/Subprocess Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m90_shell_subprocess_static_safety",
                    "M90 source allows only shell/subprocess hardening freeze review contracts and blocks actual command execution, shell/subprocess/process spawning, emergency stop, process kill/signal, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, routes, dependencies, background workers, raw command/shell/PID receipts, and production authority.",
                    "M90 source contains command execution, shell/subprocess/process spawning, emergency stop, process kill/signal, filesystem mutation, network/tool/browser/plugin/remote/model/context/memory authority, route, dependency, background-worker, raw command/shell/PID receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m90_shell_subprocess_route_boundary",
                    "M90 Shell/Subprocess Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m90_shell_subprocess_route_boundary",
                    "M90 adds no shell, subprocess, command execution, process spawn, emergency stop, process kill, process signal, filesystem mutation, memory, context, tool, or backend routes.",
                    "M90 route boundary drifted or exposed shell, subprocess, command execution, process spawn, emergency stop, process kill, process signal, filesystem mutation, memory, context, tool, or production authority.",
                    "critical",
                ),
        build(
                    "m90_roadmap_currentness",
                    "M90 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m90_roadmap_currentness",
                    "Active roadmap docs mark v0.94.0/M90 implemented and keep M91-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.94.0/M90 or imply M91+ implementation, command execution, shell execution, subprocess execution, process kill execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m91_autonomous_tool_execution_contract",
                    "M91 Autonomous Tool Execution Contract",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m91_autonomous_tool_execution_contract",
                    "M91 defines contract-only, review-only autonomous tool execution contract decisions over exact M90 Shell/Subprocess Hardening Freeze decisions, with safe contract refs, safe-ref-only receipt plans, and no real tool execution, autonomous session start, routes, dependencies, or authority.",
                    "M91 autonomous tool execution contracts are missing, weak, or imply real tool execution, autonomous session start, background worker, command/shell/subprocess execution, raw tool/provider payload storage, routes, dependencies, M92 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m91_autonomous_tool_execution_static_safety",
                    "M91 Autonomous Tool Execution Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m91_autonomous_tool_execution_static_safety",
                    "M91 source allows only autonomous tool execution contract review metadata and blocks actual tool execution, autonomous session start, background workers, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, routes, dependencies, raw payload receipts, and production authority.",
                    "M91 source contains tool/autonomous execution, autonomous session start, background worker, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, route, dependency, raw payload receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m91_autonomous_tool_execution_route_boundary",
                    "M91 Autonomous Tool Execution Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m91_autonomous_tool_execution_route_boundary",
                    "M91 adds no tool execution, tool-runtime execution, autonomy tool execution, session start, command execution, shell, memory, context, or backend routes.",
                    "M91 route boundary drifted or exposed tool execution, tool-runtime execution, autonomy tool execution, session start, command execution, shell, memory, context, or production authority.",
                    "critical",
                ),
        build(
                    "m91_roadmap_currentness",
                    "M91 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m91_roadmap_currentness",
                    "Active roadmap docs mark v0.95.0/M91 implemented and keep M92-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.95.0/M91 or imply M92+ implementation, real tool execution, session start, command execution, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m92_low_risk_tool_autonomy_single_session",
                    "M92 Low-Risk Tool Autonomy Single Session",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m92_low_risk_tool_autonomy_single_session",
                    "M92 defines low-risk tool autonomy single-session review contracts over exact M91 Autonomous Tool Execution Contract decisions and exact M69 low-risk dry-run records, with safe-ref-only receipt plans and no real tool execution, session start, routes, dependencies, or authority.",
                    "M92 low-risk tool autonomy contracts are missing, weak, or imply real tool execution, autonomous session start, multi-tool runs, background workers, command/shell/subprocess execution, raw tool/provider payload storage, routes, dependencies, M93 implementation, or production authority.",
                    "critical",
                ),
        build(
                    "m92_low_risk_tool_autonomy_static_safety",
                    "M92 Low-Risk Tool Autonomy Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m92_low_risk_tool_autonomy_static_safety",
                    "M92 source allows only low-risk tool autonomy single-session review metadata and blocks actual tool execution, session start, additional sessions, background workers, multi-tool execution, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, routes, dependencies, raw payload receipts, and production authority.",
                    "M92 source contains low-risk tool autonomy enablement, real tool execution, session start, additional sessions, background workers, multi-tool execution, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, route, dependency, raw payload receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m92_low_risk_tool_autonomy_route_boundary",
                    "M92 Low-Risk Tool Autonomy Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m92_low_risk_tool_autonomy_route_boundary",
                    "M92 adds no tool execution, tool-runtime execution, autonomy tool execution, session start/run/execute, sessions, memory, context, or backend routes.",
                    "M92 route boundary drifted or exposed tool execution, tool-runtime execution, autonomy tool execution, session start/run/execute, sessions, memory, context, or production authority.",
                    "critical",
                ),
        build(
                    "m92_roadmap_currentness",
                    "M92 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m92_roadmap_currentness",
                    "Active roadmap docs mark v0.96.0/M92 implemented and keep M93-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.96.0/M92 or imply M93+ implementation, real tool execution, multi-tool real runs, session start, command execution, shell execution, browser click execution, plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m93_multi_tool_dry_run_promotion",
                    "M93 Multi-Tool Dry-Run Promotion",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m93_multi_tool_dry_run_promotion",
                    "M93 defines review-only dry-run to real-run promotion contracts with exact M92 binding, matching dry-run/real-run plan refs and hashes, exact non-wildcard promotion approval, safe-ref-only receipts, and no real execution.",
                    "M93 dry-run promotion contracts are missing, weak, or imply unapproved real execution, wildcard approval, plan drift, session start, shell/network/browser/plugin execution, routes, dependencies, or production authority.",
                    "critical",
                ),
        build(
                    "m93_multi_tool_dry_run_promotion_static_safety",
                    "M93 Multi-Tool Dry-Run Promotion Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m93_multi_tool_dry_run_promotion_static_safety",
                    "M93 source allows only review-only promotion metadata and blocks real-run execution, tool execution, session start, background workers, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, routes, dependencies, raw payload receipts, and production authority.",
                    "M93 source contains dry-run promotion enablement, real-run execution, tool execution, session start, command/shell/subprocess execution, filesystem mutation, network/browser/plugin/remote/model/context/memory authority, route, dependency, raw payload receipt, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m93_multi_tool_dry_run_promotion_route_boundary",
                    "M93 Multi-Tool Dry-Run Promotion Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m93_multi_tool_dry_run_promotion_route_boundary",
                    "M93 adds no promotion, real-run execution, tool execution, autonomy session, memory, context, shell, browser, plugin, or backend routes.",
                    "M93 route boundary drifted or exposed promotion, real-run execution, tool execution, autonomy session, memory, context, shell, browser, plugin, or production authority.",
                    "critical",
                ),
        build(
                    "m93_roadmap_currentness",
                    "M93 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m93_roadmap_currentness",
                    "Active roadmap docs mark v0.97.0/M93 implemented and keep M94-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.97.0/M93 or imply M94+ implementation, real-run execution, browser click execution, shell/network/plugin execution, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m94_low_risk_browser_clicks",
                    "M94 Low-Risk Browser Clicks",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m94_low_risk_browser_clicks",
                    "M94 defines low-risk browser click contracts with exact M93 promotion binding, exact click approval, scoped session, allowlisted page/action, safe refs only, injected transport, audit, revocation, and no broad browser automation.",
                    "M94 low-risk browser click contracts are missing, weak, or imply forms, typing, purchases, downloads, auth, account changes, credential/cookie access, raw DOM, broad navigation, routes, dependencies, M95 work, or production authority.",
                    "critical",
                ),
        build(
                    "m94_low_risk_browser_clicks_static_safety",
                    "M94 Low-Risk Browser Clicks Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m94_low_risk_browser_clicks_static_safety",
                    "M94 source allows only scoped low-risk click contracts and blocks forms, typing, purchases, downloads, auth, account changes, credentials/cookies, raw DOM, screenshots, broad navigation, shell/network/plugin/model/context/memory authority, routes, dependencies, and production authority.",
                    "M94 source contains forbidden browser action, broad automation, route, dependency, credential/cookie, raw DOM, shell/network/plugin/model/context/memory, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m94_low_risk_browser_clicks_route_boundary",
                    "M94 Low-Risk Browser Clicks Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m94_low_risk_browser_clicks_route_boundary",
                    "M94 adds no browser click, browser form, browser download, browser auth, tool execution, memory, context, shell, plugin, or backend routes.",
                    "M94 route boundary drifted or exposed browser click/form/download/auth, tool execution, memory, context, shell, plugin, or production authority.",
                    "critical",
                ),
        build(
                    "m94_roadmap_currentness",
                    "M94 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m94_roadmap_currentness",
                    "Active roadmap docs mark v0.98.0/M94 implemented and keep M95-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.98.0/M94 or imply M95+ implementation, unrestricted network tools, plugin execution, recurring automation, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m95_authless_network_tool_expansion",
                    "M95 Authless Network Tool Expansion",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m95_authless_network_tool_expansion",
                    "M95 defines exact-scope authless read-only network expansion contracts over allowlisted HTTPS GET targets with redirect controls, bounded redacted output, audit, revocation, and transport injection, while performing no network call.",
                    "M95 authless network expansion contracts are missing, weak, or imply unrestricted network tools, authenticated requests, credential material, cookies, request bodies, mutations, private network access, downloads, routes, dependencies, M96 work, or production authority.",
                    "critical",
                ),
        build(
                    "m95_authless_network_tool_expansion_static_safety",
                    "M95 Authless Network Tool Expansion Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m95_authless_network_tool_expansion_static_safety",
                    "M95 source allows only authless read-only network proposal contracts and blocks authenticated network access, credential headers, cookies, request bodies, POST/PUT/PATCH/DELETE mutations, private networks, downloads, browser forms, shell/plugin/model/context/memory authority, routes, dependencies, and production authority.",
                    "M95 source contains forbidden authenticated network, credential/header/cookie, request-body, network mutation, private network, download/export, browser form, shell/plugin/model/context/memory, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m95_authless_network_tool_expansion_route_boundary",
                    "M95 Authless Network Tool Expansion Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m95_authless_network_tool_expansion_route_boundary",
                    "M95 adds no network request, network mutation, browser form/download/auth, tool execution, memory, context, shell, plugin, or backend routes.",
                    "M95 route boundary drifted or exposed network request/mutation, browser form/download/auth, tool execution, memory, context, shell, plugin, or production authority.",
                    "critical",
                ),
        build(
                    "m95_roadmap_currentness",
                    "M95 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m95_roadmap_currentness",
                    "Active roadmap docs mark v0.99.0/M95 implemented and keep M96-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v0.99.0/M95 or imply M96+ implementation, external plugin execution, recurring automation, mobile permission runtime, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m96_plugin_execution_sandbox",
                    "M96 Plugin Execution Sandbox",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m96_plugin_execution_sandbox",
                    "M96 allows only a deterministic built-in test plugin sandbox with manifest permission checks, audit receipt, revocation binding, and safe refs.",
                    "M96 plugin execution sandbox contracts are missing, weak, or imply external plugins, marketplace plugins, arbitrary code, runtime imports, network fetch, secret access, raw plugin payloads, routes, dependencies, M97 work, or production authority.",
                    "critical",
                ),
        build(
                    "m96_plugin_execution_sandbox_static_safety",
                    "M96 Plugin Execution Sandbox Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m96_plugin_execution_sandbox_static_safety",
                    "M96 source allows only the built-in test plugin sandbox and blocks external plugin loading, marketplace plugins, arbitrary plugin code, runtime imports, network fetch, shell/network/browser/model/memory/context authority, routes, dependencies, and production authority.",
                    "M96 source contains forbidden external plugin, marketplace, arbitrary-code, import, fetch, shell/network/browser/model/memory/context, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m96_plugin_execution_sandbox_route_boundary",
                    "M96 Plugin Execution Sandbox Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m96_plugin_execution_sandbox_route_boundary",
                    "M96 adds no plugin execute, plugin load, plugin marketplace, shell, network, memory, context, or backend routes.",
                    "M96 route boundary drifted or exposed plugin execute/load/marketplace, shell, network, memory, context, or production authority.",
                    "critical",
                ),
        build(
                    "m96_roadmap_currentness",
                    "M96 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m96_roadmap_currentness",
                    "Active roadmap docs mark v1.0.0/M96 implemented and keep M97-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v1.0.0/M96 or imply M97+ implementation, recurring automation, mobile permission runtime, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m97_recurring_automation_contracts",
                    "M97 Recurring Automation Contracts",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m97_recurring_automation_contracts",
                    "M97 defines recurring automation contracts only, with approval renewal, expiration, stop conditions, audit, revocation, safe refs, and disabled-by-default status.",
                    "M97 recurring automation contracts are missing, weak, or imply recurrence runtime, background workers, cron/daemon/scheduler behavior, side effects, routes, dependencies, M98 work, or production authority.",
                    "critical",
                ),
        build(
                    "m97_recurring_automation_static_safety",
                    "M97 Recurring Automation Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m97_recurring_automation_static_safety",
                    "M97 source keeps recurring automation contract-only and blocks recurrence runtime, background workers, cron, schedulers, shell/network/browser/plugin/model/memory/context authority, routes, dependencies, and production authority.",
                    "M97 source contains forbidden recurrence runtime, background worker, cron/scheduler, shell/network/browser/plugin/model/memory/context, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m97_recurring_automation_route_boundary",
                    "M97 Recurring Automation Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m97_recurring_automation_route_boundary",
                    "M97 adds no recurring automation run/start/execute, scheduler, cron, background worker, shell, network, memory, context, tool, plugin, or backend routes.",
                    "M97 route boundary drifted or exposed recurring automation runtime, scheduler, cron, background worker, shell, network, memory, context, tool, plugin, or production authority.",
                    "critical",
                ),
        build(
                    "m97_roadmap_currentness",
                    "M97 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m97_roadmap_currentness",
                    "Active roadmap docs mark v1.1.0/M97 implemented and keep M98-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v1.1.0/M97 or imply M98+ implementation, recurrence runtime, background execution, mobile permission runtime, production authority, or broad autonomy.",
                    "critical",
                ),
        build(
                    "m98_scoped_recurring_low_risk_automation",
                    "M98 Scoped Recurring Low-Risk Automation",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m98_scoped_recurring_low_risk_automation",
                    "M98 defines scoped low-risk read-only recurring automation contracts with strict cadence, renewal, stop conditions, audit, revocation, and kill switch refs.",
                    "M98 scoped recurring low-risk automation contracts are missing, weak, or imply schedulers, background workers, recurring runtime execution, mutating tasks, credential/account actions, shell/network/browser writes, routes, dependencies, M99 work, or production authority.",
                    "critical",
                ),
        build(
                    "m98_scoped_recurring_low_risk_automation_static_safety",
                    "M98 Scoped Recurring Low-Risk Automation Static Safety",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m98_scoped_recurring_low_risk_automation_static_safety",
                    "M98 source keeps scoped recurring automation low-risk, read-only, safe-ref-only, and blocks scheduler, background worker, recurring runtime, mutating, credential/account, write, route, dependency, and production-authority fragments.",
                    "M98 source contains forbidden scheduler, background worker, recurring runtime, mutating, credential/account, shell/network/browser write, route, dependency, or production-authority fragments.",
                    "critical",
                ),
        build(
                    "m98_scoped_recurring_low_risk_automation_route_boundary",
                    "M98 Scoped Recurring Low-Risk Automation Route Boundary",
                    FoundationGateCategory.contracts,
                    "FoundationGateEvaluator.check_m98_scoped_recurring_low_risk_automation_route_boundary",
                    "M98 adds no recurring automation run/start/execute/collect/worker/scheduler, shell, network, memory, context, tool, plugin, or backend routes.",
                    "M98 route boundary drifted or exposed recurring automation runtime, worker, scheduler, shell, network, memory, context, tool, plugin, or production authority.",
                    "critical",
                ),
        build(
                    "m98_roadmap_currentness",
                    "M98 Roadmap Currentness",
                    FoundationGateCategory.documentation,
                    "FoundationGateEvaluator.check_m98_roadmap_currentness",
                    "Active roadmap docs mark v1.2.0/M98 implemented and keep M99-M100 planned/provisional only.",
                    "Active roadmap docs are stale for v1.2.0/M98 or imply M99+ implementation, recurrence runtime, background execution, mobile permission runtime, production authority, or broad autonomy.",
                    "critical",
                ),
    ]
