"""ECO-000 coherent-app ecosystem contracts.

This package defines additive planning and acceptance vocabulary. It does not
provide repositories, routes, connector runtime, execution, or authority.
"""

from ultimate_ai_agent.core.ecosystem.contracts import (
    ECO_000_CONTRACT_VERSION,
    AppId,
    AtomicityPosture,
    BoardProjection,
    CardSubject,
    CapabilityCatalogRelationship,
    CanonicalEntityRef,
    CanonicalOwnerId,
    ChangeOperation,
    ChangeSetPlan,
    ConflictPrecondition,
    CompensationPlan,
    EntityKind,
    EntityLink,
    EntityLinkKind,
    EntityVersion,
    OperationResultStatus,
    PrivacyScope,
    ProductAcceptanceStatus,
    ProductRenderAcceptance,
    Projection,
    RollbackPlan,
    SourceProvenance,
    StandaloneAppMaturity,
    TimelineProjection,
    WorkspaceScope,
)
from ultimate_ai_agent.core.ecosystem.ownership import (
    CANONICAL_OWNER_BY_ENTITY_KIND,
    CANONICAL_OWNERSHIP_REGISTRY,
    CanonicalOwnershipAssignment,
    CanonicalOwnershipRegistry,
    canonical_owner_for,
    validate_unique_canonical_ownership,
)

__all__ = [
    "ECO_000_CONTRACT_VERSION",
    "AppId",
    "AtomicityPosture",
    "BoardProjection",
    "CardSubject",
    "CANONICAL_OWNER_BY_ENTITY_KIND",
    "CANONICAL_OWNERSHIP_REGISTRY",
    "CapabilityCatalogRelationship",
    "CanonicalEntityRef",
    "CanonicalOwnerId",
    "CanonicalOwnershipAssignment",
    "CanonicalOwnershipRegistry",
    "ChangeOperation",
    "ChangeSetPlan",
    "ConflictPrecondition",
    "CompensationPlan",
    "EntityKind",
    "EntityLink",
    "EntityLinkKind",
    "EntityVersion",
    "OperationResultStatus",
    "PrivacyScope",
    "ProductAcceptanceStatus",
    "ProductRenderAcceptance",
    "Projection",
    "RollbackPlan",
    "SourceProvenance",
    "StandaloneAppMaturity",
    "TimelineProjection",
    "WorkspaceScope",
    "canonical_owner_for",
    "validate_unique_canonical_ownership",
]
