"""Policy-controlled WebAccessGateway package."""

from .adapters import (
    DisabledProviderAdapterShell,
    DisabledProviderShellContract,
    DisabledProviderShellStatus,
    disabled_provider_adapter_shell_catalog,
    disabled_provider_adapter_shells,
)
from .contracts import (
    SourceMetadata,
    WebAccessAdapterKind,
    WebAccessAuditRecord,
    WebAccessAuthorityMode,
    WebAccessEvidenceBundle,
    WebAccessNetworkLane,
    WebAccessPolicyDecision,
    WebAccessPolicyStatus,
    WebAccessRequest,
    WebAccessRequestKind,
    WebAccessResult,
    WebAccessRiskClass,
)
from .gateway import WebAccessGateway, create_default_web_access_gateway
from .policy import WebAccessPolicy
from .runtime_authority import (
    WEB_RUNTIME_AUTHORITY_PROMOTION_LADDER,
    WEB_RUNTIME_AUTHORITY_PROMOTION_LADDER_STATUSES,
    WEB_RUNTIME_CANONICAL_NOUNS,
    WEB_RUNTIME_PROMOTION_STEPS,
    WEB_RUNTIME_REQUIRED_OPERATOR_LABELS,
    WEB_RUNTIME_REQUIRED_SIDE_EFFECTS,
    WebApprovalLinkageContract,
    WebCatalogManifestVisibilityContract,
    WebDurableAuditStorageContract,
    WebOperatorStateContract,
    WebOperatorStateLabel,
    WebPromotionStep,
    WebPromotionStepContract,
    WebProviderDiagnosticContract,
    WebRuntimeCostGovernorPostureContract,
    WebRuntimeAuditRecordContract,
    WebRuntimeAuthorityContract,
    WebRuntimeNoun,
    WebRuntimePromotionLadderStep,
    WebRuntimePromotionLadderStepContract,
    WebSideEffectKind,
    WebSideEffectLedgerContract,
    WebSideEffectLedgerState,
    build_web_runtime_authority_contract,
)

__all__ = [
    "SourceMetadata",
    "DisabledProviderAdapterShell",
    "DisabledProviderShellContract",
    "DisabledProviderShellStatus",
    "WEB_RUNTIME_AUTHORITY_PROMOTION_LADDER",
    "WEB_RUNTIME_AUTHORITY_PROMOTION_LADDER_STATUSES",
    "WEB_RUNTIME_CANONICAL_NOUNS",
    "WEB_RUNTIME_PROMOTION_STEPS",
    "WEB_RUNTIME_REQUIRED_OPERATOR_LABELS",
    "WEB_RUNTIME_REQUIRED_SIDE_EFFECTS",
    "WebAccessAdapterKind",
    "WebAccessAuditRecord",
    "WebAccessAuthorityMode",
    "WebAccessEvidenceBundle",
    "WebAccessGateway",
    "WebAccessNetworkLane",
    "WebAccessPolicy",
    "WebAccessPolicyDecision",
    "WebAccessPolicyStatus",
    "WebAccessRequest",
    "WebAccessRequestKind",
    "WebAccessResult",
    "WebAccessRiskClass",
    "WebApprovalLinkageContract",
    "WebCatalogManifestVisibilityContract",
    "WebDurableAuditStorageContract",
    "WebOperatorStateContract",
    "WebOperatorStateLabel",
    "WebPromotionStep",
    "WebPromotionStepContract",
    "WebProviderDiagnosticContract",
    "WebRuntimeCostGovernorPostureContract",
    "WebRuntimeAuditRecordContract",
    "WebRuntimeAuthorityContract",
    "WebRuntimeNoun",
    "WebRuntimePromotionLadderStep",
    "WebRuntimePromotionLadderStepContract",
    "WebSideEffectKind",
    "WebSideEffectLedgerContract",
    "WebSideEffectLedgerState",
    "create_default_web_access_gateway",
    "build_web_runtime_authority_contract",
    "disabled_provider_adapter_shell_catalog",
    "disabled_provider_adapter_shells",
]
