import type { NewsSignalsAdoptionMutationPreview, NewsSignalsAdoptionView } from "../api/types";

export const workspace: NewsSignalsAdoptionView = {
  schema_version: "uaa-news-signals-adoption.v1",
  contract_ref: "contract-ref:queue-v2-q34-news-signals-adoption:v1",
  status: "blocked_no_graduated_source",
  storage_status: "missing",
  revision: 0,
  current_state_ref: "state-ref:news-signals-adoption:empty",
  can_undo: false,
  local_manual_intake_enabled: true,
  backend_owned: true,
  external_content_untrusted: true,
  live_fetch_enabled: false,
  authenticated_source_enabled: false,
  background_polling_enabled: false,
  model_summarization_enabled: false,
  connector_write_enabled: false,
  action_authority_granted: false,
  summary: {
    schema_version: "uaa-news-signals-read-model.v1",
    contract_ref: "contract-ref:queue-v2-q24-news-signals:v1",
    status: "blocked_no_graduated_source",
    backend_owned: true,
    read_only: true,
    local_artifact_snapshot_only: true,
    external_content_untrusted: true,
    live_fetch_enabled: false,
    authenticated_source_enabled: false,
    background_polling_enabled: false,
    model_summarization_enabled: false,
    connector_write_enabled: false,
    action_authority_granted: false,
    observed_at: "2026-09-09T12:00:00Z",
    source_readiness: [],
    items: [],
    freshness_counts: { fresh: 0, stale: 0, unknown: 0 },
    conflicting_claim_refs: [],
    today_projection: {
      projection_ref: "projection-ref:q24:today",
      item_refs: [],
      bounded_limit: 3,
      read_only: true,
    },
    morning_briefing_projection: {
      projection_ref: "projection-ref:q24:morning-briefing",
      candidate_refs: [],
      bounded_limit: 5,
      review_required: true,
      read_only: true,
    },
    safe_summary: "A bounded local News summary for review.",
    blocked_state_refs: ["blocked-state-ref:q24:no-graduated-news-source"],
    evidence_refs: ["evidence-ref:q24:safe-artifacts-only"],
  },
  active_items_page: {
    offset: 0,
    limit: 100,
    total_items: 0,
    returned_items: 0,
    has_previous: false,
    has_next: false,
    search_applied: false,
    items: [],
  },
  preferences: [],
  archived_items: [],
  next_safe_action: "Register the first local redacted artifact source.",
  evidence_refs: ["evidence-ref:q34:local-redacted-intake-only"],
};

export const preview: NewsSignalsAdoptionMutationPreview = {
  schema_version: "uaa-news-signals-adoption-preview.v1",
  contract_ref: "contract-ref:queue-v2-q34-news-signals-adoption:v1",
  action: "register_source",
  target_ref: null,
  source_ref: "source-ref:q34:official",
  signal_ref: null,
  expected_revision: 0,
  resulting_revision: 1,
  current_state_ref: "state-ref:news-signals-adoption:empty",
  payload_fingerprint_ref: "payload-fingerprint-ref:q34:official",
  preview_ref: "preview-ref:q34:official",
  approval_ref: "approval-ref:q34:official",
  safe_summary: "Register one local redacted artifact source.",
  external_network_read_performed: false,
  authenticated_source_access_performed: false,
  model_call_performed: false,
  external_write_performed: false,
  production_authority_granted: false,
};
